### ISSUE TITLE
python_terminal plugin can segfault

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1009]
There have been multiple reports of serious problems with this plugin.  My brother Speed reports segfaults.

**Comment by technatica** [comment]
This was once again a showstopper for me.

A default install of Leo segfaults because python_terminal.py is enabled by default. I had to copy an old myLeoSettings.leo file that has it disabled into the .leo folder in my home directory to get Leo to start.

The error message was totally not helpful. Luckily I knew what the problem was.

"Segmentation Fault"

**Comment by edreamleo** [comment]
Rev b2a88971f in devel works around this problem by not enabling the python_terminal plugin by default.  This should have been done long ago.

**Comment by edreamleo** [comment]
This plugin will not exist in Leo 6.0, because the far superior pyzo code will be used instead.

**Comment by edreamleo** [comment]
I am going to close this issue.  In Leo 6.0 the pyzo Shell will replace the python_terminal plugin.
