### ISSUE TITLE
Crash in json scanner

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1098]
From Josef: I can't load the simplest JSON file into Leo, I always get an error message like:
```
Exception running JSON_Scanner
Traceback (most recent call last):

   File "/home/dalcolmo/bin/leo-editor/leo/core/leoApp.py", line 1530, in scanner_for_ext_cb
    return scanner.run(s, parent)

   File "/home/dalcolmo/bin/leo-editor/leo/plugins/importers/leo_json.py", line 61, in run
    ok = self.scan(s, parent)

   File "/home/dalcolmo/bin/leo-editor/leo/plugins/importers/leo_json.py", line 130, in scan
    for d2 in d.get('nodes', []):

AttributeError: 'list' object has no attribute 'get'
```
I tried with something as simple as: [{"abc":"PC","xyz":"blabla"}]  in a file.

**Comment by dalcolmo** [comment]
leo_json.py uses @auto to write a leo subtree to a json file and read it back. This is an abuse of the @auto directive, in my view, because one assumes that @auto reads in an **arbitrary** file outlining it in the process, and saves it back the same way. E.g. @auto should (IMHO) be usable as a generic editor, **not** in order to store internals of Leo. Therefore I suggest to replace the use of @auto in leo_json.py to @leo-json.

**Comment by edreamleo** [comment]
At present, Leo's json scanner only handles .json files that Leo itself wrote.  That is, the scanner can only read files written by the leo/plugins/writers/leo_json.py plugin.  You could say this makes sense, because the reader is going to try to recreate a tree of nodes from the .json file, and this file is assumed to be a dict with certain keys.

So for now the workaround is to copy your .json text into one or more Leo nodes in an @auto x.json file.  Leo will read the file correctly when you restart the file, as I have just verified.

**Comment by edreamleo** [comment]
Rev 5eea4046 mostly fixes the problem.  If Leo didn't write the .json file, the `@auto` importer just puts repr(json.loads(s)) into the top-level node.  You can then optionally convert `@auto` to `@auto-json` for more control.

Please reopen only if you have a better way to suggest.
