### ISSUE TITLE
Support @adoc nodes and the adoc command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1147]
Not to be confused with [Joe Orr's documentation work](https://kaleguy.github.io/leosite-pilot/).

[AsciiDoctor](https://asciidoctor.org/docs/user-manual/) is clearly better than markdown for documentation. I prefer it to reStructuredText.

[AsciiDoctorJ](https://github.com/asciidoctor/asciidoctorj) allows access to AsciiDoctor from JS.

- [x] Add adoc command.  See leo/core/leoAsciiDoctor.py.
- [x] Automatically generate .html files from .adoc files.  See `@button ad` below.

**@button ad**
```
'''A prototype: convert .adoc files to .html files in c.p.'''
import os
paths = c.asciiDoctorCommands.ad_command(event=g.Bunch(p=p))
paths = [z.replace('/', os.path.sep) for z in paths]
input_paths = ' '.join(paths)
g.execute_shell_commands(['asciidoctor %s' % input_paths])
if 1: # optional: open .html files in the default browser.
    output_paths = ' '.join([z.replace('.adoc', '.html') for z in paths])
    g.execute_shell_commands([output_paths])
```

**Comment by maphew** [comment]
AsciiDoc as syntax with AsciiDoctor for handling is smarter and on my shortlist. See [Stop Using Markdown For Documentation](https://mister-gold.pro/posts/en/asciidoc-vs-markdown/) (read conclusion first then go back for details).

However I've not stepped up for serious AsciiDoc experimentation because the tools I've used so far for Markdown editing don't support it (Markdown Monster, Markdown Pad). I use tools primarily for 2 reasons: 
- paste image and have it converted to a referenced file
- insert link with a keyboard shortcut and have it converted to footnote style  (`[title][1]` ... `[1]: url`)

I'm sure both of these features could be done in Leo but I haven't mustered the wherewithal to begin tackling how. ;-)

**Comment by maphew** [comment]
discussion at https://groups.google.com/d/msg/leo-editor/M6JLWqZ9OmM/04ZOqIPFBQAJ

**Comment by edreamleo** [comment]
Reassigning to 6.0 because it would be good to do asap.  However, this should not be confused with [Joe Orr's documentation work](https://kaleguy.github.io/leosite-pilot/).
