### ISSUE TITLE
 Render pane fixed to bottom edge,  unable to drag it to a new location

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1208]
I have a PC running commit baf5d21 where the Render pane is fixed to the bottom edge,  and I am unable to drag it to a new location. All other panes can be moved.
Running clear-cache and deleting all file from .leo/db did not improve the problem.
Leo 6.0-devel, devel branch
Python 3.7.3, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by LewisNeal** [comment]
For the record - on a different PC (with later commit db34959) the Render pane can be moved. The issue may have been temporary.

**Comment by edreamleo** [comment]
On Mon, Jun 17, 2019 at 6:23 AM LewisNeal <notifications@github.com> wrote:

> I have a PC running commit baf5d21
> <https://github.com/leo-editor/leo-editor/commit/baf5d21a88986961d6f1f9ecc8ca3633a62a50af>
> where the Render pane is fixed to the bottom edge, and I am unable to drag
> it to a new location. All other panes can be moved.
>
This depends on @bool use-vr-dock setting. If it is False, the default, the
Render pane will "split" the body pane, and will not be moveable.

Yes, it *could* be made moveable, but that would be a bad idea, because
once moved it could not be "unmoved".  This appears to be a hole in the
QDockWidget interface: there is no way to detect a drag, and so no way to
split docks after they are created.

Edward

**Comment by LewisNeal** [comment]
I have control of the render pane now. Thanks for pointing to @bool use-vr-dock = True

**Comment by edreamleo** [comment]
@LewisNeal You're welcome.  Glad everything works as you wish.
