### ISSUE TITLE
Tree: multiple select drag and drop nodes only moves 1 node

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1252]
Recipe:

1. Select several child nodes using `shift` or `ctrl` click
2. drag and drop to a different parent node

Result: the only node moved is the one under the cursor when drag begins. I expect the entire selection to be moved.

There are 2 additional UI bugs revealed in the same recipe:

 a) The first item in the selection list is not highlighted
 b) While dragging the cursor changes to have a `[+]` added to it. Elsewhere in Windows this means you're about to do a Copy operation. The additional icon helper should be `[-]` or better `[🡒]`  because the node is being Moved.

```
Leo 6.0-b2-devel, desktop-links branch, build 19aef04dea
2019-07-12 00:30:28 -0700
Python 3.6.3, PyQt version 5.12.1
Windows 10 AMD64 (build 10.0.17763) SP0
```

**Comment by technatica** [comment]
I think that this was one of the first questions I ever asked about Leo on the forum. I found it jarring that it didn't behave the same way as every other application in this. I still run into it now and then in my workflow.

I would love to be able to Ctrl-Click on nodes to select them. Then it would be great to right click for the "cut/copy" options or drag and drop for the "Move, Copy, Link, Cancel" popup menu.

**Comment by edreamleo** [comment]
On Fri, Jul 12, 2019 at 10:14 PM Chris George <notifications@github.com>
wrote:

> I think that this was one of the first questions I ever asked about Leo on
> the forum. I found it jarring that it didn't behave the same way as every
> other application in this. I still run into it now and then in my workflow.
>
> I would love to be able to Ctrl-Click on nodes to select them. Then it
> would be great to right click for the "cut/copy" options or drag and drop
> for the "Move, Copy, Link, Cancel" popup menu.
>
I recently disabled the ability to select multiple nodes because find-next
was, in some situations, selecting too many nodes.

Yes, it would be possible to allow the user to select multiple nodes with
control-clicks, but clones make dragging multiple nodes problematic.  Not
all drags are valid.

I rarely want to drag nodes to *arbitrary* places.  Instead, I use cffm
(clone-find-flattened-marked) command to clone all marked nodes to a
top-level organizer node.  In that case, all the "clone move" operations
will be valid.

Edward
