### ISSUE TITLE
leoQt.py should return None for everything when in bridge

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1274]
The "bridge" branch contains ugly tests for g.in_bridge. Instead:

- [ ]  leoQt.py should return None for all values when g.in_bridge is True.

Hmm. It would be easy to do this by setting fail = g.in_bridge.  However, there is a comment:
```python
fail = False
    # New for TravisCI tests: allow imports from the Leo Bridge.
```

**How the bug arises**
 
```python
# in my (patched) pyzo.start:
 leo_x = pyzo_support.PyzoInterface()
 leo_x.patch_pyzo()

# In plugins pyzo_support.py:
def patch_pyzo(self):
    bridge = leoBridge.controller(
        gui='nullGui',
        loadPlugins=False, # True gives the error.
            # Some plugins import Qt, which causes this message:
                # Qt WebEngine seems to be initialized from a plugin.
                # Please set Qt::AA_ShareOpenGLContexts using 
                # QCoreApplication::setAttribute before constructing QGuiApplication.
        readSettings=True, # Debatable.
        verbose=False,
    )
    if bridge.isOpen():
        self.g = bridge.globals()
        # c = bridge.openLeoFile(path)
```

**Comment by btheado** [comment]
This change seems incompatible with the `elif self.guiName == 'qt'` section of leoBridge.createGui(). IOW, ff the bridge controller is instantiated with `gui='qt'`, then it fails with `AttributeError: 'NoneType' object has no attribute 'QObject'`.

I found this because I was playing with the bridge controller and saw the gui option and wondered if using the bridge with qt would be useful for anything, but found that it doesn't work. It doesn't seem like a pressing issue to me, I just thought I would report it.

**Comment by edreamleo** [comment]
@btheado Good catch.  In fact, it makes no sense whatever to use the qt gui in the bridge. 

Rev d8826e1 in devel fixes this buglet by removing the `elif self.guiName == 'qt'` code.
