### ISSUE TITLE
Mac pip install from pypi: launch scripts broken

### ISSUE THREAD

**Issue by xu4wang** [leo-editor/leo-editor#1288]
I just installed Leo by:

```
pip3 install leo
```
Tried to load a theme file from the "settings" -> "Open a theme file", However there is no file open, and I saw below error message from console.

```
WangXus-MacBook-Pro:leo-editor wangxu$ leo

setting leoID from os.getenv('USER'): 'wangxu'
Leo 6.0-final
objc[35116]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9f9e83d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1225e1f50). One of the two will be used. Which one is undefined.
python: can't open file 'launchLeo.py': [Errno 2] No such file or directory

```
I tried to workaround this by clone the source code, located the launchLeo.py file and start leo from that directory, however, same error.

any advice? Thanks, Xu

----
## Update Summary 
_2019-08-19, by Matt_
Installing Leo from PyPi (`pip install leo`) on MacOS doesn't work out of the box due to a complication with the leo launcher script and PATH. 

Installing from code remains the most reliable method:
```
pushd path/to/code
git clone https://github.com/leo-editor/leo-editor.git
#or curl https://github.com/leo-editor/leo-editor/archive/master.zip && unzip master.zip
pip install --editable path/to/code/leo-editor
```

Leaving open and as bug because it should work out of the box, however it may take some time to understand and fix as we don't have many Mac devs around.

**Comment by edreamleo** [comment]
On Fri, Aug 16, 2019 at 11:56 PM Wang Xu <notifications@github.com> wrote:

> I just installed Leo by:
>
> pip3 install leo
>
> ...

> any advice?
>

Matt is probably the one to answer this.  As always, the best way to
install Leo is by using git.

Edward

**Comment by maphew** [comment]
Edward, he did try a git clone after pip and that didn't work either. 

Xu what's the exact output of: `python3 path/to/cloned/leo-editor/launchLeo.py --version` ?

and then `python3 -v path/to/cloned/leo-editor/launchLeo.py --version` (added `-v `flag. Save as text file and attach) ?

**Comment by xu4wang** [comment]
I'd like to clarify that I also tried 

```
cd path/to/cloned/leo-editor/
python3 launchLeo.py
```
It works, the theme file can be open.

The issue maybe related to the pip3 installed leo. which is :

```
WangXus-MacBook-Pro:leo-editor wangxu$ which leo
/usr/local/bin/leo
WangXus-MacBook-Pro:leo-editor wangxu$ cat /usr/local/bin/leo
#!/usr/local/opt/python/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys

from leo.core.runLeo import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

> Edward, he did try a git clone after pip and that didn't work either.
> 
> Xu what's the exact output of: `python3 path/to/cloned/leo-editor/launchLeo.py --version` ?
> 
```
WangXus-MacBook-Pro:leo-editor wangxu$ python3 launchLeo.py --version

Leo 6.0-final, master branch, build db55bd00c9
2019-08-02 11:24:36 -0500
```
> and then `python3 -v path/to/cloned/leo-editor/launchLeo.py --version` (added `-v `flag. Save as text file and attach) ?

I upload the stderr output here.
[_v_output.txt](https://github.com/leo-editor/leo-editor/files/3512281/_v_output.txt)

**Comment by xu4wang** [comment]
> Edward, he did try a git clone after pip and that didn't work either.


More clarification. I tried 

```
cd path/to/cloned/leo-editor/
leo
```
the issue can be produced.

If I use:
```
cd path/to/cloned/leo-editor/
python3 launchLeo.py
```

there is no such issue.


> 
> Xu what's the exact output of: `python3 path/to/cloned/leo-editor/launchLeo.py --version` ?
> 
> and then `python3 -v path/to/cloned/leo-editor/launchLeo.py --version` (added `-v `flag. Save as text file and attach) ?

**Comment by maphew** [comment]
ok, so it is a problem with the launch pip creates. That helps narrow the search. It looks like pip is creating a Windows script for Mac. I'll see of I can dig out why.

**Comment by maphew** [comment]
My reading leads me to think a problem with PATH.

Find out where the pip installed version of leo is with `pip show leo`. Add that directory to PATH, and then try running the launcher `leo` again.  On windows it would be `PYTHONHOME/lib/site-packages`, I don't know about Mac equivalent. 

    export PATH="path/location/from/pip-show-leo:$PATH"
    leo

If that works then something here might help https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line. Setting PATH (should) set your system for all packages with console script installed from PyPi.

HOWEVER, since you've already cloned Leo you might as well just keep using this version since upgrading will be easier:

 1. uninstall from-pypi Leo: `pip uninstall leo`
 2. Re-install in editable mode: `pip install --editable path/to/leo/clone`
 3. Does `leo` from console work? 

If yes, then you're done. :) If no, then repeat above to add to PATH.
To upgrade Leo later, just update the source code cloned files with `git pull`.

If none of this works maybe ask on the mailing list if there's another Mac user who might have suggestions.

-matt

**Comment by xu4wang** [comment]
Thanks Matt.. I followed your "HOWEVER" instruction, and installed leo again from cloned version successfully.

**Comment by maphew** [comment]
Great! Did you need to alter PATH or did `leo` just work after `pip install -e ...`?

**Comment by maphew** [comment]
# Summary 
Installing Leo from PyPi (`pip install leo`) on MacOS doesn't work out of the box due to a complication with the leo launcher script and PATH. 

Installing from code remains the most reliable method:
```
pushd path/to/code
git clone https://github.com/leo-editor/leo-editor.git
#or curl https://github.com/leo-editor/leo-editor/archive/master.zip && unzip master.zip
pip install --editable path/to/code/leo-editor
```

Leaving open and as bug because it should work out of the box, however it may take some time to understand and fix as we don't have many Mac devs around.

**Comment by xu4wang** [comment]
> Great! Did you need to alter PATH or did `leo` just work after `pip install -e ...`?

I just work after `pip install...`.

**Comment by maphew** [comment]
## Possible fix for pypi-installed Leo
_untested recipe, see https://stackoverflow.com/a/48380776/14420 for more info_

Root problem is that the console scripts created when Leo is installed are not in PATH. To fix that add Python bin directories to path (changing _3.6_ to whatever version you have installed):

    python3.6 -m site &> /dev/null && PATH="$PATH:`python3.6 -m site --user-base`/bin"

----
_Closing until it comes up again; easy enough to re-open it when needed._
