### ISSUE TITLE
"scan_lines too many @first lines" warning in console

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1295]
I don't remember seeing this before:
```
Leo 6.1-devel, devel branch, build c25a42bb7b
2019-08-20 13:22:44 -0700
scan_lines too many @first lines
```
I get it when opening `leo\scripts\Desktop-integration.leo`. `Alt-x: cff`, `@first` only finds 2 nodes.

Log Window for same:
```
Leo 6.1-devel, devel branch, build c25a42bb7b
2019-08-20 13:22:44 -0700
Python 3.7.1, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17134) SP0
```
(also curious that log reports more version info than console)

**Comment by edreamleo** [comment]
@maphew Is this repeatable?  If so, please send the .leo file and the relevant external file.

**Comment by maphew** [comment]
yes it's repeatable. File is ./leo/scripts/Desktop-integration.leo in devel branch. Sorry I omitted that it's in the Leo repo earlier.

**Comment by maphew** [comment]
well, I'm not seeing it anymore. closing until it shows up again.

**Comment by edreamleo** [comment]
Heh.  I *do* see it.  I'll attempt a fix before pulling anything.

**Comment by edreamleo** [comment]
The culprit was an `@first` directive in the "main" node in @file remove-desktop-links.leox.

Rev 2a6eb41a in devel gives a better error message.  Here it is:

scan_lines too many @first lines: C:/leo.repo/leo-editor/leo/scripts/remove-desktop-links.leox
@first is valid only at the start of @<file> nodes
```
first_lines: []
lines[start:i+2]:
[
    '#@+node:mhw.20190808083026.1: * @file remove-desktop-links.leox\n',
    '#@@language python\n',
    '#@@tabwidth -4\n',
    '#@+others\n',
    '#@+node:mhw.20190808083336.1: ** main\n',
    '#@@first\n'
]
```
Replacing  '#@@first\n' by  '###@@first\n' disables the message.  You will see the line:
`###@@first` at the start of the main node.

Clearly, the `@first` directive should be in the node `@file remove-desktop-links.leox`, but I'm not sure what the desired line is.  That's for you, Matt.

**Comment by edreamleo** [comment]
I have just created #1297. Leo should warn if @first or @last appear outside the root @<file> node.

**Comment by maphew** [comment]
Aaaah, I get it now. Thanks.

**Comment by edreamleo** [comment]
Furthermore, Leo should warn if `@first` or `@last` appears in an `@clean` tree. See #1307.
