### ISSUE TITLE
quickMove plugin destroys clones when moving nodes

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1328]
Select a cloned node.
Right-click over node, select Move > Move to > Top of file.leo

Once moved, the cloned node is no longer a clone but a copy.

_Leo Log Window
Leo 6.1-devel, devel branch, build 4ef0a80ae6
2019-09-13 10:27:14 -0700
Python 3.7.4, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0_

**EKR**: This is a bug in the quickMove plugin.

**Comment by LewisNeal** [comment]
If I use the cffm command, and move the new organizer node using right-click as above , all the child clones are changed to copies.

**Comment by edreamleo** [comment]
This is likely a bug in the code executed from the popup menu, not a bug in Leo's core.

**Comment by edreamleo** [comment]
The culprits are the to_other and copy_recursively methods.

I do not intend to rewrite this plugin any time soon.

The workaround is clear: cut-node, followed by paste-retaining-clones.

**Comment by edreamleo** [comment]
Let me restate the situation as I see it:

1. I can not recommend this plugin in its present state.
2. Users can easily move nodes with cut-node, followed by paste-retaining-clones.
3. The to_other and copy_recursively methods are misguided.  Instead of *coping* nodes, they should use low-level position methods.

To unlink: call p._adjustPositionBeforeUnlink followed by p._unlink.
To relink: call one of p2._linkAfter, p2._linkAsNthChild or p2._linkAsRoot, where p2 depends on the operation.

Do cff _adjustPositionBeforeUnlink to see how it should be used.
