### ISSUE TITLE
External adoc file not created  when tools not present

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1372]
I created a new node `@adoc somefilename.adoc`, put in some content, and pressed Save. The .leo file saved but no external file was created. I expected an external file to be created containing the same contents as the body pane in Leo.

**EKR**:  Leo does *not* automatically write `@adoc` nodes when saving a file.  Instead, you must use the `adoc` command to write the file. This is how `@rst` and `@pandoc` nodes work.  It won't change.

**Comment by edreamleo** [comment]
@maphew I think I agree :-)

**Comment by edreamleo** [comment]
Here is the second part of Matt's original report:

After lots of flailing around I eventually I tried `Alt-X: adoc [enter]` -- AHA! A useful message:
> adoc requires either asciidoctor or asciidoc3

My thought: `@adoc filename.ext` should always write something to disk even when a conversion tool is not available. This keeps convention with other external file directives, so users can rely on the convention and not have to learn special cases (and probably forget from time to time).

A warning that the output file is likely not valid/complete asciidoc because of the missing tools should be emitted.

Leo 6.1-devel, devel branch, build a6809b7721
2019-10-08 14:17:25 -0500
Python 3.7.1, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0

**Comment by edreamleo** [comment]
I am going to close this item.
