### ISSUE TITLE
Adoc writes to Scripts folder instead of .leo folder when no @path given

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1373]
In a .leo file that does not contain a `@path` directive the output of `Alt-X: adoc` is written to PYTHONHOME/Scripts. I expect it to go to the same folder that the .leo file is in.

Leo Log Window
Leo 6.1-devel, devel branch, build a6809b7721
2019-10-08 14:17:25 -0500
Python 3.7.1, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0

**Comment by edreamleo** [comment]
@maphew Definitely should be fixed, somehow.

**Comment by edreamleo** [comment]
Fixed at 6a88140 in devel.

**Comment by maphew** [comment]
I confirm it doesn't go to PYTHONHOME now, instead it goes to my HOME which is definitely better. (Leo 6.1-devel, devel branch, build c79238e4d2). 

What directive can I use in a .leo file to set @path to be relative current .leo file instead of hard coding it? Oh hang on, https://leoeditor.com/directives.html#index-37 says _"If no @path directives are in effect, the default path prefix is the directory containing the .leo file."_. 

This naturally leads e to "How do I figure what Leo's current path is?" which I tried to answer for myself. After an hour I give up for now, though the journey has been interesting. Thanks to a [thread back in 2011](https://groups.google.com/d/msg/leo-editor/TqMe0uBRiGY/4-meuQf3ZzYJ) I have these:

```
#g.es(c.getNodePath(c.topPosition())) # this one errors out.
g.es(c.getNodePath(p))
g.es(g.computeLeoDir())
g.es(g.scanAllAtPathDirectives(c,p))
g.es(g.computeLoadDir())
g.es(g.getBaseDirectory(c))
g.es(c.scanAllDirectives(p)['path'])
```

which for `leo\scripts\Desktop-integration.leo` yields:
```
D:/matt/code/leo-editor/leo/core
D:/matt/code/leo-editor/leo/scripts
D:/matt/code/leo-editor/leo
D:/matt/code/leo-editor/leo/scripts
D:/matt/code/leo-editor/leo/core
D:/matt/code/leo-editor/leo/core
D:/matt/code/leo-editor/leo/scripts
```
None of which are where the @adoc files were written, `C:\Users\Matt`.

Oh! now this is interesting: AFTER running the above g.es script subsequent executions of `Alt-X: adoc-with-preview` write to `D:/matt/code/leo-editor/leo/scripts`, which correponds to output of `g.es(c.getNodePath(p))`, `g.es(g.scanAllAtPathDirectives(c,p))`, and `g.es(c.scanAllDirectives(p)['path'])`

**Comment by maphew** [comment]
reproduced on a 2nd machine:
- run Leo, create new workbook, close other workbooks, exit leo
- run Leo
  - Create @adoc somefile.adoc node, put some body content in it
    - `Alt-X: adoc`
    - look for results in file system --> found in HOME folder
  - Create new node, fill with g.es(...) statements from previous post
    - `Ctrl-B` this node
  - Select @adoc headline, repeat `Alt-X: adoc`
    - this time output files are in same folder as .leo file (which is the desired result).

**Comment by edreamleo** [comment]
@maphew Thanks for this.  I'll fix this soon.

**Comment by edreamleo** [comment]
On Thu, Oct 10, 2019 at 5:25 PM matt wilkie <notifications@github.com>
wrote:

> *"If no @path <https://github.com/path> directives are in effect, the
> default path prefix is the directory containing the .leo file."*.
>
Right.  There may be a missing call to g.os_path_finalize_join.

> This naturally leads e to "How do I figure what Leo's current path is?"
>
I applaud your investigations. For any .leo file, c.fileName() is the full
path to the .leo file. The desired directory is:

    base_dir = os.path.dirname(c.fileName())

You (or Leo's code) should then use:

    g.os_path_finalize_join(base_dir, path_from_headline)

to compute the desired file.  Something like this will be the fix for #1373
<https://github.com/leo-editor/leo-editor/issues/1373>.

Edward

P.S.  In the bad old days, Leo *always* had to use g.os_path wrappers
rather than the corresponding os.path functions,  because the wrappers
handled unicode issues properly. Now that Leo uses Python 3.6+, Leo can, in
*some* cases, use os.path functions directly, without wrappers.

However, the g.os_path_finalize and g.os_path_finalize_join do more than
just os.path.join, so they should be used.  This should not be hard to
remember: there are no corresponding os.path.finalize_join functions.

EKR
------------------------------------------------------------------------------------------
Edward K. Ream: edreamleo@gmail.com Leo: http://leoeditor.com/
------------------------------------------------------------------------------------------

**Comment by edreamleo** [comment]
**Matt**: "If no @path directives are in effect, the default path prefix is the directory containing the .leo file."

Right.  There may be a missing call to g.os_path_finalize_join.

**Matt**: This naturally leads e to "How do I figure what Leo's current path is?"

I applaud your investigations. For any .leo file, `c.fileName()` is the full path to the .leo file. The desired directory is: 

    base_dir = os.path.dirname(c.fileName())

You (or Leo's code) should then use

    g.os_path_finalize_join(base_dir, path_from_headline)

to compute the desired file.  Something like this will be the fix for this issue.

Edward

P.S.  In the bad old days, Leo *always* had to use g.os_path wrappers rather than the corresponding os.path functions,  because the wrappers handled unicode issues properly. Now that Leo uses Python 3.6+, Leo can, in *some* cases, use os.path functions directly, without wrappers.

However, the g.os_path_finalize and g.os_path_finalize_join do more than just os.path.join, so they should be used.  This should not be hard to remember: there are no corresponding os.path.finalize_join functions.

EKR

**Comment by maphew** [comment]
Thank you for the educational info, much appreciated.

**Comment by maphew** [comment]
@edreamleo I think this path problem is more generic. I just had a similar thing happen with `@clean`:

**Event sequence:**

1. Run Leo. In default workbook (HOME/.leo/workbook.leo) create 2 new nodes, 2nd nested under first and is `@clean leo-gmail.py`; add some body content.
2. In 1st node body add `@path ~/code`
3. Save --> yields error message:
~~~
Traceback (most recent call last):

  File "c:\users\mattw\code\leo-editor\leo\core\leoGlobals.py", line 4105, in writeFile
    with open(fileName, 'wb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/mattw/.leo/~/code/leo-gmail.py'
~~~

4. Edit 1st node and change path to `@path ../code`
5. Save --> success. File is written:
~~~
created: C:/Users/mattw/code/leo-gmail.py
finished
 saved: workbook.leo
~~~

6. Modify external file `../code/leo-gmail.py` in a different editor.
7. Prompt: external file has changed. Reload? --> answer Yes --> traceback crash. Leo tried to load file from the 1st invalid path setting and not the 2nd (which Leo already used successfully in event [5]).
~~~
updating: @clean leo-gmail.py
exception writing: C:/Users/mattw/code/leo-gmail.py
Traceback (most recent call last):

  File "c:\users\mattw\code\leo-editor\leo\core\leoAtFile.py", line 1304, in write
    if not at.precheck(fileName, root):

  File "c:\users\mattw\code\leo-editor\leo\core\leoAtFile.py", line 2502, in precheck
    if not at.shouldPromptForDangerousWrite(fileName, root):

  File "c:\users\mattw\code\leo-editor\leo\core\leoAtFile.py", line 3051, in shouldPromptForDangerousWrite
    if os.path.samefile(k, fn) and p.h in d.get(k, set()):

  File "c:\apps\miniconda3\envs\leo-dev\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/mattw/.leo/~/code/leo-gmail.py'

finished
 saved: workbook.leo
~~~

8. Inspect Leo file. 1st path setting remains unchanged and correct.
9. Save --> success. Correctly used the 2nd path setting from event [5] this time:
~~~
created: C:/Users/mattw/code/leo-gmail.py
finished
 saved: workbook.leo
~~~

---
Leo 6.1-devel, devel branch, build c79238e4d2
2019-10-10 13:24:32 -0500
Python 3.6.2, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by edreamleo** [comment]
@maphew I have just created #1383 for the '~' problem.

**Comment by edreamleo** [comment]
Rev c513636 in devel aims to expand '~' everywhere.  I am going to close this issue.  Please reopen if necessary.

**Comment by maphew** [comment]
#1385 reveals there's still something wrong lurking in current @path determination.

**Comment by edreamleo** [comment]
@maphew Imo, there is no need to reopen this issue or #1138.

Indeed, Leo has no way of evaluating ~ if you kill Window's HOME var.

The relevant code is LM.computeHomeDir.  Take a look at the code, and the comments.

The *only* proper way to test for a missing .leoID.txt file is to remove that file!

**Comment by maphew** [comment]
In the recipe HOME var is not killed, it's reassigned to an new location.
Leo is creating .leo and .leoID.txt in the current dir instead of using the defined HOME.

Ohhh. I see. In my test the new HOME is pointing to a dir that doesn't exist, so Leo is falling back to using the current dir.

**Comment by edreamleo** [comment]
@maphew Feel free to suggest improvements in LM.computeHomeDir.  Having said that, mistakes in that method would be catastrophic, so I am inclined to leave it as it is.

**Comment by maphew** [comment]
I tried just adding a message "HOME not found, using current dir" but it's too noisy, repeating 5 times on startup. 

I don't think this segment will ever fire:
~~~
    if home and len(home) > 1 and home[0] == '%' and home[-1] == '%':
        # Get the indirect reference to the true home.
        home = os.getenv(home[1: -1], default=None)
~~~

...because I can't think of a situation where the preceeding `home = os.path.expandvars("~")` would ever return something begining and ending with `%`; the call is hardcoded to `~` and not using a var.

Also os.path.expandvars will never return None (according to [the docs](https://docs.python.org/3/library/os.path.html#os.path.expanduser) it returns the path unchanged if expansion fails), so `if home:` is redundant.

I don't know how to build tests to verify the validity of these opinions though so just leaving here as comments rather than a PR.

**Comment by edreamleo** [comment]
@maphew Thanks for your comments.  Let's leave things as they are unless somebody actually runs into problems.  In that case, we'll open a new issue.
