### ISSUE TITLE
Support path expressions in @rst, @adoc, @pandoc and @sphinx nodes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1398]
For example, `@adoc {{expr}}myFile.adoc`.

**Comment by jknGH** [comment]
Hi Edward

1) The call to asciidoctor seems to fail if the pathname (@adoc headline) contains a space

the fix might be as simple as:
{{{
diff --git a/leo/core/leoMarkup.py b/leo/core/leoMarkup.py
index 88c797fcb..681dc36d4 100644
--- a/leo/core/leoMarkup.py
+++ b/leo/core/leoMarkup.py
@@ -329,7 +329,7 @@ class MarkupCommands:
         assert asciidoctor_exec or asciidoc3_exec, g.callers()
         # Call the external program to write the output file.
         prog = 'asciidoctor' if asciidoctor_exec else 'asciidoc3'
-        command = f"{prog} {i_path} -o {o_path} -b html5"
+        command = f"{prog} \"{i_path}\" -o \"{o_path}\" -b html5"
             # The -e option deletes css.
         g.execute_shell_commands(command)
     #@+node:ekr.20191007043043.1: *4* markup.run_pandoc
}}}

Perhaps applies elsewhere as well? I only saw this because I accidentally left a space in the specified filename

2) I have also seemingly experienced issues where sometimes the @adoc pathname is treated as relative to my home directory, and sometime as relative to the Leo file! Seems a bit weird; I can't reproduce this at the moment, and the docs are a bit contradictory.

Thanks, Jon N

**Comment by edreamleo** [comment]
@jknGH I do get notifications.  Duplicate notifications are no problem.
