### ISSUE TITLE
The already open dialog can cause Leo to hang

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#145]
Iirc, choosing yes-to-all when Leo reports that a file is already open can cause Leo to hang or crash.

One option would simply be to eliminate the yes-to-all option.

Imo, the present code is too complicated.  I'm not sure I am responsible for all this code, but I may be responsible for removing it ;-)

**Comment by tbnorth** [comment]
On Fri, 27 Feb 2015 03:20:33 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> Iirc, choosing yes-to-all when Leo reports that a file is already
> open can cause Leo to hang or crash.

You need something reproducible here, I use yes-to-all on occasion and
haven't seen a problem.

> One option would simply be to eliminate the yes-to-all option.

It was added (by me, possibly) for a reason though, I typically have 4+
outlines open at a time, that's 8+ clicks to restart after a crash.
These are not necessarily Leo crashes, usually some sort of network /
power / shutdown event that didn't give Leo a chance to exit cleanly.
I wouldn't want to see it go.

> Imo, the present code is too complicated.

I can't remember it but I think I may have written it, anyway, given a
reproducible way of generating a hang, I'll try and take a look.

**Comment by edreamleo** [comment]
> You need something reproducible here, I use yes-to-all on occasion and haven't seen a problem.
@tbnorth Fair enough.  I'll see what I can find.

**Comment by edreamleo** [comment]
On Fri, Feb 27, 2015 at 11:04 AM, tbnorth <notifications@github.com> wrote:

> On Fri, 27 Feb 2015 03:20:33 -0800
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > Iirc, choosing yes-to-all when Leo reports that a file is already
> > open can cause Leo to hang or crash.
>
> You need something reproducible here, I use yes-to-all on occasion and
> haven't seen a problem.
>

​The problem happened to me yesterday, but when I tried to reproduce it all
went well.  This makes the problem more serious, not less.

Edward

**Comment by edreamleo** [comment]
Choosing no-to-all just now on Linux caused a segfault. So this is not a Windows-only problem.
Repeating did not cause a segfault: Leo exited gracefully.
Iirc, the "duplicate" Leo file was not actually open, which may be part of the problem: there was no fall-back.

**Comment by tbnorth** [comment]
You originally reported the problem for yes-to-all, so it's probably not a question of no fall-back with no-to-all, assuming that it's true that the problem is observed for both yes-to-all and no-to-all. I've just `xkilled` Leo several times without seeing the problem.

SegFault is indicative of something beyond a regular bug - has there always been a SegFault as part of this issue?

Also, no-to-all *should* result in Leo not starting, I'm fairly sure that outcome was discussed once. Maybe that needs changing, but I think that's the code's intent now.

Anyway, I did just see a reproducible bug, 3 outlines open, xkill Leo, start it again opening the three outlines from the command line, "first outline is open, open it again" - answering just No, not No to all, causes Leo to exit instead of asking the question again for the second outline.  I'll have a look at the code.

**Comment by edreamleo** [comment]
On Thu, Mar 5, 2015 at 8:29 AM, tbnorth <notifications@github.com> wrote:

> SegFault is indicative of something beyond a regular bug - has there
> always been a SegFault as part of this issue?
>
​Yes.  On Windows it's the dreaded "Python has stopped working" dialog.​


> Also, no-to-all *should* result in Leo not starting, I'm fairly sure that
> outcome was discussed once. Maybe that needs changing, but I think that's
> the code's intent now.
>
​I agree.​

> Anyway, I did just see a reproducible bug, 3 outlines open, xkill Leo,
> start it again opening the three outlines from the command line, "first
> outline is open, open it again" - answering just No, not No to all, causes
> Leo to exit instead of asking the question again for the second outline.
> I'll have a look at the code.
>
​Thanks.  I wouldn't call this a release blocker because it's been around
awhile without many complaints.  Still, segfaults don't look good ;-)

Edward

**Comment by tbnorth** [comment]
I can't see whey yes-to-all should cause a problem.  But I do see a problem with no(-to-all).

If you're opening multiple outlines from the command line and say *no* (not no-to-all) to the *first* outline (assuming that all are in an "already open" state because of a previous improper exit), then readOpenedLeoFile() will call g.app.closeLeoWindow(c.frame) which will call g.app.finishQuit() which, on my machine, makes further attempts to open dialogs fail (the bug I noted in my previous comment).

I wonder if my machine's failure to open a dialog could be a segfault on another machine? Anyway calling g.app.finishQuit() after being told not to open the *first* of more than one file from the command line is definitely wrong. In the no-to-all case it might be causing non-dialog related problems as the rest of the "load files from command line" loop executes.

So somehow g.app.finishQuit() needs to be called from g.app.closeLeoWindow() only if there are not more files to try loading from the command line list - an annoying encapsulation problem, but presumably a guard can fix it.

**Comment by tbnorth** [comment]
The guard might look like this:

In doPostPluginsInit() the `for fn in lm.files` loop could set g._loading_last_file True/False

In closeLeoWindow() `elif not g.app.unitTesting` at the bottom would become
`elif not g.app.unitTesting and getattr(g, '_loading_last_file') is not False`

Very ugly, *but* I have to stress it looks like this issue would arise any time you click 'no' *or* no-to-all for the first already open file.

If you can confirm that, i.e. try clicking No, No, No... instead of No to All, and still see the problem, that would corroborate my analysis.

**Comment by edreamleo** [comment]
On Thu, Mar 5, 2015 at 11:51 AM, tbnorth <notifications@github.com> wrote:

> The guard might look like this:
>

​Thanks for all this work,

​> v​
ery ugly, *but* I have to stress it looks like this issue would arise any
time you click 'no' *or* no-to-all for the first already open file.

If you can confirm that, i.e. try clicking No, No, No... instead of No to
All, and still see the problem, that would corroborate my analysis.

​I opened a 3 different .leo files in three separate tabs.

I then attempted to open the same three files.  I answered "no" *once* and
segfaulted.

Without closing the first invocation of Leo, I again attempted to open the
same three files. The first "no" cancelled the *entire* load, without
segfault.

HTH.

Edward​
​

**Comment by edreamleo** [comment]
On Thu, Mar 5, 2015 at 11:35 AM, tbnorth <notifications@github.com> wrote:

> I can't see whey yes-to-all should cause a problem. But I do see a problem
> with no(-to-all).
>
​Hmm. We might be able to simplify both the user dialog and the supporting
code.​ Imo, there are really only two use cases:

1. Mistakenly trying to reopen one or more files when some/all are already
opened.

2. Trying to reopen one or more .leo files when they have been closed
prematurely, say by closing their console.

In the first case, I want no-to-all.  In the second, yes-to-all.

Yes, one can imagine weird cases where some files were prematurely closed
and not others, but those boundary case are going to be rare, and
furthermore it will be even rarer that I'll know how to recover :-)  In
other words, in an emergency I'll be safer closing all Leo instances and
reloading, choosing yes-to-all if necessary.

So why not just have a dialog with two responses, "yes" and "no" and leave
it at that? The two responses would be equivalent to yes-to-all and
no-to-all behind the scenes.  From your recent remarks I gather that might
simplify matters considerably.  For sure, if you give me more than two
choices I am not going to know how to respond ;-)

Edward

**Comment by tbnorth** [comment]
That seems to confirm my findings, thanks. It seems that the segfault isn't an every time thing, but the incorrect program flow is what I'm seeing here, once g.app.finishQuit() is called dialogs don't open any more, myDialog.exec_() just returns immediately. Hence the cancelling of the whole load for one "No".

(In response to your more recent comment, I don't see a need to drop the "to all" options, the same fix is required with or without them, and any time you're actually running two instances of Leo not being able to individually select which files are opened could be  limiting.)

Do you want me to add the guard I mentioned above? The alternative would be to pass a parameter through about 5 layers of function calling to achieve the same effect. There are already some similar guards in the code base, and I suspect with a program as complex as Leo they're are reasonable pragmatism. Having said that, let me look at the parameter based approach, it might be cleaner.

**Comment by tbnorth** [comment]
Well duh, the guard can be an ivar of the LoadManager, that's clean enough, not *really* any different that tacking it on g, but it certainly looks a lot better.

**Comment by edreamleo** [comment]
On Thu, Mar 5, 2015 at 3:08 PM, tbnorth <notifications@github.com> wrote:

> That seems to confirm my findings, thanks.
> ​..
>
> I don't see a need to drop the "to all" options, the same fix is required
> with or without them
> ​...
>
> ​Ok.​

> Do you want me to add the guard I mentioned above? The alternative would
> be to pass a parameter through about 5 layers of function calling to
> achieve the same effect.
>
​If multiple modules must see the guard my preferences are:

1: an ivar of LoadManager (g.app.loadManager).
2: an ivar of LeoApp (g.app)
3. a global defined in leoGlobals.

Which one is easiest depends on the details of the load process. Having
said that, I would be surprised if an LoadManager ivar couldn't get the job
done.  That's what the LM is for.

> There are already some similar guards in the code base, and I suspect with
> a program as complex as Leo they're are reasonable pragmatism. Having said
> that, let me look at the parameter based approach, it might be cleaner.
>
​I doubt it, but the choice is yours.

Edward

**Comment by edreamleo** [comment]
Well done, Terry.  Many thanks for fixing this.
