### ISSUE TITLE
Add QWebEngine to list of requirements

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1468]
Starting with PyQt5.12, QWebEngine is not installed with ``pip install pyqt5``.  It has to be installed separately:
```
   pip install PyQtWebEngine
```

So please add PyQtWebEngine to the list of required modules.

**Comment by edreamleo** [comment]
@maphew What do you think, Matt.  Is this a reasonable thing to do?

**Comment by tbpassin** [comment]
Reference for this: https://www.riverbankcomputing.com/software/pyqtwebengine/download

They don't say that you need to do the separate install after 5.12 specifically, but the oldest version listed on the page is for 5.12.  I verified when this change started by installing QT5 v10, 11, 12, and  14.  QtWebEngine was present through  5.11.x, but not after that.

**Comment by tbpassin** [comment]
I just looked at requirements.txt, and it does specify pyqtwebengine after all:

```
pyqtwebengine==5.13.0     # via leo
```

I had tried installing PyQy5.14 by hand, and didn't get the webengine.  So I didn't realize that a full Leo install would bring it in.

Seems like this issue can be closed.

BTW, Leo seems to be working normally with PyQt5 V14.0.

**Comment by maphew** [comment]
I don't really like using `requirements.txt` because it hard codes version numbers and I don't want to track dependencies in two places (`setup.py`, `requirements.txt`). Though tonight I read that req.txt can be used without pinning the version if wanted, and/or, just tell it to read from setup.py. List is much shorter that way too.

@technatica git blame says you added requirements.txt. Do you still use it / need it? I'm going to use the technique at end of https://caremad.io/posts/2013/07/setup-vs-requirement/. Please let me know if this change causes a problem.

**Comment by maphew** [comment]
With 23ba97c9c7ad38bba1e3a7bf587cb47e6add5dea `pip install -r requirements.txt` and `pip install --editable leo` should yield identical results: a python environment with all Leo's dependencies, and Leo installed in editable mode.
