### ISSUE TITLE
ILeo errors not piped to Log and Do not show in Ipython console

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#156]
This one is pretty straight forward. If I run this command via Ctrl + B:

```
for ind in range(5):
    print("index:" + ind)
```

Without ILeo I get:

```
TypeError: cannot concatenate 'str' and 'int' objects
--------------------
  line 12: for ind in range(5):
* line 13:     print("index:" + ind)
  line 14: #@-leo
  line 15: 
```

But when run with ILeo via "ipython-exec" I get no notification of any error. Either in the ipython console or the Leo Log.

**Comment by edreamleo** [comment]
Thanks for this report.  I'd like to fix this before b1.

**Comment by edreamleo** [comment]
I spent several hours on this last night.  No solution in sight.  Here is the best workaround I could find.  It has problems, explained below.

```python

    # Bind g so it works with execute-script or ipython-exec.
    try:
        g
    except Exception:
        g = _leo.g
    # Print any exception without help from IPython.
    try:
        print(x)
    except Exception:
        g.es_print_exception() # Newly improved.
```

Any invocation of ``ipython-exec`` has two problems.  First, the output from stderr disappears (per this bug).  Second, the output of the print command (as in ``g.es_print_exception``) can appear (sometimes but not always) after the *next* invocation of ``ipython-exec``.

Neither I nor google has found truly a helpful explanation of what is going on. The next step will be to ask the IPython developers for help.

I am intending to fix this by Leo 5.1 final, or b2 if possible.

**Comment by JohnLunzer** [comment]
Thank you for your investigations.

**Comment by edreamleo** [comment]
Interesting, syntax errors *are* sent to the console.  For example,

```python
print('os
```
This generates the expected traceback on Windows, and a huge traceback on Linux.  Not sure why.

I've moved this item to the "Projects" list for Leo 5.2, meaning it can't be fixed in a few hours.  It will likely require deep study of the IPython sources.

**Comment by JohnLunzer** [comment]
After trying to craft a separate solution and studying the depth of how Spyder handles integrated IPython consoles I completely understand the decision and support it. 

I hope that I am able to find time to contribute to a solution but as I continue to use Leo my list things I want to improve has become longer by the day. Leo is more valuable right now as an Outlining Editor and PIM and it's what sets Leo apart from the rest of the field. I think my priorities have shifted away from trying to make Leo a full interactive python environment and more towards improving Leo's flow with outlines.

**Comment by edreamleo** [comment]
Rev bdce2b05 succeeds in showing errors to Leo's log and the console window from which Leo was launched.

Still unfinished: print a waning to IPython Qt Console.

**Comment by edreamleo** [comment]
The new code prints the same messages to the Qt Console as are printed to Leo's log pane.

**Notes**:

1. There is no obvious traceback object available anywhere. This is annoying, but it should not be a huge problem, because the offending code is in the .leo file. I am going to ask stack overflow...

2. While IPython is executing, sys.stderr goes to IPython's Qt pane, while sys.__stderr__ goes to the console window (if any) from which Leo was launched.

3. It's imperative to call stream.flush() for either sys.__stderr__ or sys.stderr.

**Comment by edreamleo** [comment]
ecc0270 looks like a complete solution. See [this discussion](http://stackoverflow.com/questions/36337983/how-to-get-sys-exc-traceback-form-ipython-shell-run-code/36375305#36375305) on Stack Overflow. For the first time, this issue looks completely resolved.

**Comment by JohnLunzer** [comment]
Very very good news indeed.
