### ISSUE TITLE
Notes re Leo's code base

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1585]
This issue will discuss why Leo's code base is as it is, and what I might do differently if I were to rewrite Leo now.

**Background**

Clearly, Leo's code base could be improved.  However, statements like "Leo's code base sucks" show a lack of engineering maturity. To be of any use, criticism must be specific.

**Factors complicating the code**

1. At startup, Leo must handle Leo settings embedded in various outlines.
2. Leo must define not only 'c', 'g', and 'p', but other "official" ivars such as
    'c.frame', 'c.frame.body', c.frame.log', 'c.frame.body.wrapper' etc.
3. Leo's core is almost completely separate from Leo's gui code.
    As a result, Leo supports multiple guis in a straightforward way.
4. Whenever possible, I have tried to maintain compatibility with older versions of Leo.
5. Scripts may update all parts of the gui.
6. Leo's clones complicate the tree code.
7. Leo's gui is complex, with support for multiple body editors and many kinds of syntax coloring.

**Improvements based on pyzo's code**

I think of Almar Klein as the "young genius" :-) It's always worth studying his code.

Leo uses the "has-a" design pattern, but pyzo's code shows the benefits of the "is-a" pattern. The code in pyzoSourceStructure.py is only one of many possible examples. 

The PyzoSourceStructure class *is* a QWidget, it doesn't *have* a QWidget. This simplifies everything. To make this work, all ivars unique to the PyzoSourceStructure class itself must start with a single underscore. Imo, this is a small price to pay.

The PyzoSourceStructure class uses QBoxLayout.addStretch to simplify layout. I wish I had known about this trick.

Most importantly, pyzo's code uses messages much more effectively than Leo does. This decouples pyzo's code more thoroughly than in Leo.

**Summary**

I have briefly mentioned several ways that I might have simplified Leo. There are many more.

Alas, there is no easy way of making wholesale changes to Leo's qt gui code. A rewrite would take months, at the least, and would surely introduce many bugs. Some of these bugs could cause data loss, as I know all too well from experience.

**Comment by tbpassin** [comment]
> Alas, there is no easy way of making wholesale changes to Leo's qt gui code. A rewrite would take months, at the least, and would surely introduce many bugs. Some of these bugs could cause data loss, as I know all too well from experience.

This is a perennial problem.  There comes a time when a complete rewrite or re-implementation would be best, but the size and complexity of the existing version makes that hard to pull off.  I recall that reading about a team that tried to re-implement an existing software system for a jet fighter.  I think that they wanted to show that some particular methodology would be superior.  They found that by the time they completed the system, the original version had evolved so that they had to play catch up again.  They never were able to catch up because of the ongoing evolution.

I had this experience myself on a small scale.  About 35 years ago, I wrote a piece of software that was basically a RPN calculator (modeled on my own HP calculator), but for waveforms instead of numbers.  It collected and analyzed data from an early digital oscilloscope.  It was written in Forth and ran on a 64k CPM machine.  Later I reimplemented it in Turbo Pascal in a PC.  That wasn't too hard since it was small.  It worked well enough, since it was functionally almost the same as the original, though it was slower than the Forth original.

Later again, I ported it to a Windows manager I had developed in Turbo Pascal for the PC.  I was able to use most of the previous code.  Later again, I rewrote the UI to work with Windows, once TurboPascal supported it. But I never liked that version and didn't use it much.

Later again, a few years ago, I bit the bullet and rewrote it in python using matplotlib, and some other python math and statistics libraries.  For the first time, I didn't write all the axis, graphing, and math code myself, and that simplified things.  This still took quite a bit of effort because it had gotten by this time up to maybe 10,000 lines of (Turbo Pascal) code.  Finally I have a very nice system that I really like using and that runs quickly enough for my taste. 

My point is that I had to re-implement the system several times to get something really good, and it was a big effort for one person just for 10,000 LOC.  Leo being so much larger, the effort would be hugely more.  And it's likely that the first try wouldn't really do the job.  It's the saying about how you have to build it a third time to really get what you want.

Of course, you have Leo itself to help ...

**Comment by edreamleo** [comment]
@tbpassin Thanks for these comments. Imo, the only safe way to make changes to existing code is to ensure the code is covered by unit tests. Not so easy for gui code, but is that's no real excuse...

**Comment by maphew** [comment]
I'm reminded of Joel Spolsky's "[Things you should never do](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/)" 

> ... making the single worst strategic mistake that any software company can make:
>They decided to rewrite the code from scratch.

which goes well with "[Reading code is like Reading the talmud](https://www.joelonsoftware.com/2000/05/26/reading-code-is-like-reading-the-talmud/)" and another post by different author I can't re-find. Anyway the gist is: you have to go slow to go fast when refactoring, but it still usually better than a wholesale rewrite. I notice that neither of them advocate "leave it alone, do nothing".

Not that I personally have written or re-written any code at scale. These expressions speak to me as if they carry truth though.

**Comment by edreamleo** [comment]
@maphew Thanks for your comments. I'll say more in an Engineering Notebook post.

**Comment by tbpassin** [comment]
And there's this, one of the best things I've read about rewrites -

https://www.onstartups.com/tabid/3339/bid/97052/how-to-survive-a-ground-up-rewrite-without-losing-your-sanity.aspx

**Comment by celtic-coder** [comment]
Hi @tbpassin,

> https://www.onstartups.com/tabid/3339/bid/97052/how-to-survive-a-ground-up-rewrite-without-losing-your-sanity.aspx

That is a brilliant article!
