### ISSUE TITLE
Find Previous will not continue if target word in headline

### ISSUE THREAD

**Issue by rossburnett** [leo-editor/leo-editor#164]
This only happens when clicking the 'Find Previous: F2' button.  If using F2 key, the search proceeds to the next hit.

**Comment by edreamleo** [comment]
Fixed at rev d9f56ca.  The fix was a fairly ugly hack applied to both the F2 and F3 button code.

**Comment by edreamleo** [comment]
I am going to reopen this.  The fixes will skip the selected headline, even though it might contain a match for the search.  Not terrible, but not great either.

This is a *much* harder problem than you might suppose: clicking a find *button* destroys focus, and that makes restarting a search difficult. I'll attempt a fix later today, but no guarantees. It is crucial that any fix not affect the rest of the very complicated find code. That could break the code that most people actually use :-)

**Comment by tbnorth** [comment]
On Wed, 25 Mar 2015 09:50:49 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> clicking a find *button* destroys focus

http://doc.qt.io/qt-4.8/qapplication.html#focusChanged

might tell you the previous focus?  I'm surprised

http://doc.qt.io/qt-4.8/qfocusevent.html

doesn't tell you what had focus before, but it seems not.

Cheers -Terry

**Comment by edreamleo** [comment]
@tbnorth Knowing the previous focus is useless, because the tree's edit (headline) widget is *destroyed* by the mouse click.  More details to follow in the discussion of the bug fix.

**Comment by edreamleo** [comment]
Rev cddd027 fixes this bug about as well as possible.  Here is the checkin log, slightly revised::

    A much better fix for bug # 146. All tests pass.
    
    This bug results from subtle differences between button searches and key searches:
    
    - Pressing the button changes focus, so...
    - The headline widget goes away, so c.edit_widget(p) is None, so...
    - initInteractiveCommands, gets None for w, so ins is None, so...
    - All headline searches start at the same place, so...
    - Headline searches can stall.
    
    The fixes:
    
    1. findButton and findPreviousButton:
        - These methods now move out of the selected node if was_in_headline is True.
        - The only way to do this is to set was_in_headline = False and the select the new node.
        - If the search fails, the methods must select the original node.
        - Restoring the original node can flash the outline, but there is no alternative.
    2. restore (the failure handler):
        - Previously, this method toggled was_in_headline. Now it sets it to False.
    3. showSuccess:
        - Sets was_in_headline to True if the success happened in the headline.

**Discussion**

Almost all the hacks are to ``findButton`` and ``findPreviousButton``.  Only the F2 and F3 **buttons** call these methods, so there is no way that changing these can change searches initiated by F2 and F3 **keys**.  This reduces the risk.

The only "real" changes to Leo's fundamental search code involve the ``was_in_headline`` ivar. **Any** change to this code is significant, but here the risk appears to be minimal. Indeed, this ivar is actually only used in the following code in ``focusInTree`` ::

    if self.buttonFlag and self.was_in_headline in (True,False):
           self.in_headline = self.was_in_headline
           val = self.was_in_headline

As you can see, ``self.buttonFlag`` guards this code, and this ivar is only True if the user pressed the button.  Therefore, it seems likely that the new code can only affect searches started with the F2 and F3 **buttons**.

I wouldn't bet my life on this analysis, but preliminary testing seems to indicate that all is well.

**Summary**

- The new hacks are much better than the old.  They seem to do the right thing in almost all situations.

- There are obscure ways in which switching between key-initiated and button initiated searches can stall the search.  This is an inevitable result of the ``was_in_headline`` state ivar.  Ideally, we want a *stateless* control of find/change commands, but that's not possible after button presses. 

- This bug was always a minor issue, even though newbies would likely encounter it more frequently than anyone else.  No one except a code tester is likely going to alternate between button-initiated and key-initiated searches, so the remaining problems are unlikely ever to bite anyone.

- I am going to close this bug now.  Please reopen if you encounter *any* problems with the code.  We certainly don't want find/replace problems in Leo 5.1 b1.

Edward
