### ISSUE TITLE
Unable to initialze bridge with gui='nullGui' with no PyQt4 installed.

### ISSUE THREAD

**Issue by osleg** [leo-editor/leo-editor#167]
I belive that leoBridge should provide access to leoBridge without using PyQt4 (correct me if I wrong)
As for now when trying to initialize controller with gui='nullGui' (which is default btw) leo fails on assertion at line 123@leoBridge.py
Further checking showed that leo just fail on lines 116/117 on import and initializing leoApp()
Is this expected behaviour? How should I run it without pyqt4 installed?

**Comment by edreamleo** [comment]
@osleg I agree, leoBridge should run without PyQt4, but I wouldn't be surprised if it didn't.  This issue has never come up before.  I'll look into this.  In the meantime, the workaround is to install PyQt4/5 :-)

**Comment by edreamleo** [comment]
Recent revs apparently fix this bug.  Please try things out and report your experiences.  I'll leave this issue open for awhile. The general strategy:

- The leoQt module now defines everything to be False or None when neither PyQt4 or 5 can be imported. When the ``strict`` switch is off (as at present), no exception will be thrown.

- Several of Leo's core files define a class only if a symbol imported from leoQt is not None.  This allows the files to be imported successfully even if Qt can not be imported.  These files will never be *used* in such circumstances, but it saves a lot of ``if`` statements if they can always be imported.

- Ditto for three plugins enabled by unitTest.leo.

**Aside**: there's not a big reason to make plugins work even when Qt does not exist.  It could even be called confusing and foolish.  However, I wanted unitTest.leo to run unchanged without raising any exceptions. In practice, the bridge either should disable all plugins (``loadPlugins=False``) or the .leo file loaded by the bridge should enable only those plugins that don't require a gui.

With these changes, the bridge can run unitTest.leo with no exceptions thrown.  Of course, lots of unit tests fail because those tests test the gui!

Here is my test file::

    '''A program to run unit tests with the leoBridge module.'''
    
    import leo.core.leoBridge as leoBridge
    
    def main ():
        tag = 'leoTestBridge'
    
        # Setting verbose=True prints messages that would be sent to the log pane.
        bridge = leoBridge.controller(
            gui='nullGui',
            loadPlugins=False,
            readSettings=False,
            silent=True,
            verbose=False) 
        if bridge.isOpen():
            g = bridge.globals()
            path = r'C:\leo.repo\leo-editor\leo\test\unitTest.leo'
            # path = g.os_path_abspath(g.os_path_join(
                # g.app.loadDir,'..','test','unitTest.leo'))
            c = bridge.openLeoFile(path)
            # print('%s %s' % (tag,c.shortFileName()))
            # print('===== enabled plugins: %s' % c.config.getEnabledPlugins())
            runUnitTests(c,g)
        print('done: %s' % tag)
    
    def runUnitTests (c,g):
        nodeName = 'Active unit tests' # The tests to run.
        try:
            import leo.core.leoTest as leoTest
            u = leoTest.TestManager(c)
            p = u.findNodeAnywhere(nodeName)
            if p:
                print('running unit tests in %s...' % nodeName)
                c.selectPosition(p)
                c.debugCommands.runSelectedUnitTestsLocally()
                print('unit tests complete')
            else:
                print('===== node not found: %s' % nodeName)
        except Exception:
            print('unexpected exception')
            g.es_print_exception()
            raise
    
    if __name__ == '__main__':
        main()

**Important**: there are several differences between this script and the one presently shown in the leoBridge documentation.  I'll update the docs tomorrow...

Edward

**Comment by osleg** [comment]
Thank you for fast response, will try it tonight and will report back

**Comment by edreamleo** [comment]
You're welcome.  It was an interesting puzzle.

**Comment by ktenney** [comment]
> there's not a big reason to make plugins work even when Qt does not exist.

I would like to be able to exploit the data store capability of Leo even on
server
machines, without any gui capability. I hope LeoBridge will be able to
function
in a text-only environment.

**Comment by edreamleo** [comment]
@ktenney 

::

    I would like to be able to exploit the data store capability of Leo even on server machines,
    without any gui capability.
    I hope LeoBridge will be able to function in a text-only environment.

Yes, of course.  But many plugins won't load in a text-only environment, and there is no real reason to modify so the load "nicely" in such environments.  If you are going to use the leoBridge module, then it should be *your* responsibility to enable only those plugins the don't use the Qt gui.

One way to do this is to set ``loadPlugins = False`` in the ctor for the BridgeController.

**Comment by edreamleo** [comment]
Disabling a single unit test allows all tests to run to completion from the bridge when PyQt **is** installed.

Enabling traces for the GeneralTestCase class in leoTest.py revealed that the crash was in the test: ``@test interfaces using API classes``.  It starts with the following code, which has no chance of working in the bridge:

```python
    import leo.core.leoFrame as leoFrame
    import leo.plugins.qt_text as qt_text
    from leo.core.leoQt import Qsci,QtWidgets
```
I am going to close this now.  Please feel free to reopen if there are further problems.
