### ISSUE TITLE
fcol when using @first directive is inaccurate

### ISSUE THREAD

**Issue by CandyAngel** [leo-editor/leo-editor#195]
When using the @first directive, fcol and col (in the statusbar) are the same, but this is inaccurate as fcol should be 0 for the first character after "@first " (rather than 7.. or 8, depending how you count it).

**Comment by edreamleo** [comment]
Fixed at rev c8adfe6.  Here is the checkin log:

```
Fixed bug 195: fcol when using @first directive is inaccurate.
1. p.textOffset returns None if no @<file> node is an ancestor.
2. p.textOffset never caches its result.
    In any case, it was quite wrong to cache results in positions.
3. Rewrote p.textOffset to simplify it.
4. QtStatusLineClass.update prints '' for fcol if p.textOffset returns None.
5. Changed unit tests accordingly.
```

**Comment by edreamleo** [comment]
Rev 681169c changes the adjustments.  

p.textOffset no longer adjusts section definitions because @others and section references can appear in the same node.  Everything will be fine in typical cases.  For example:

```python
<< section ref >>
class myClass:
    @others
```
But fcol can be wrong in section definition nodes in contrived examples:

```python
if 1:
    << section ref >>
    @others
```
The fcol in the definition node will start at 0, not 4. I'm not going to fix this nit.

**Comment by edreamleo** [comment]
As of rev aab6818, fcol appears to be accurate in all situations, including section definition nodes.

**Note**: The present code is not so forgiving about matching section references and definitions: they should match exactly, including whitespace and capitalization within << and >>.  Yes, it would be possible to use forgiving matches, but that might impact performance significantly.
