### ISSUE TITLE
Can't find /Users/swot/.leo/vr3/vr3_config.ini so VR3 cannot execute non-Python code

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1950]
At commit 949c37330a757b6a126f7fa2decc86cb8df62912

```
git reset --hard 949c37330a757b6a126f7fa2decc86cb8df62912
```

Markdown is not displayed correctly.

markdown code:

```
sudo journalctl -u memcached
```

display:

```
# #log sudo journalctl -u memcached
```

<font color="red">Can't find /Users/swot/.leo/vr3/vr3_config.ini so VR3 cannot execute non-Python code</font>

Leo Log Window
Leo 6.4-devel, devel branch, build 949c37330a
2021-05-19 10:46:09 -0400
Python 3.9.5, PyQt version 5.15.2
darwin
setting leoID from os.getenv('USER'): 'swot'
current dir: /Users/swot/app/leo-editor
load dir: /Users/swot/app/leo-editor/leo/core
global config dir: /Users/swot/app/leo-editor/leo/config
home dir: /Users/swot
reading settings in /Users/swot/app/leo-editor/leo/config/leoSettings.leo
reading settings in /Users/swot/.leo/myLeoSettings.leo
duplicate, (not conflicting) key bindings in myLeoSettings.leo
all    BackSpace do-nothing
text   BackSpace backward-delete-char
duplicate, (not conflicting) key bindings in myLeoSettings.leo
all    Delete do-nothing
text   Delete delete-char
reading settings in /Users/swot/.leo/themes/EKRDark_use.leo
==== found asciidoc3 processor: None
Can't find /Users/swot/.leo/vr3/vr3_config.ini so VR3 cannot execute non-Python code
reading settings in /Users/swot/.leo/workbook_20191222.leo
redefining abbreviation date;; 
from '{|{x=time.asctime()}|}' to '{|{x=time.strftime("%Y/%m/%d")}|}'
redefining abbreviation html;; 
from '<html>\n<head>\n<title><|title|></title>\n<style>\n</style>\n</head>\n<body>\n<|content|>\n</body>\n</html>' to '@first <!DOCTYPE html>\n@language html\n@tabwidth -2\n\n<html>\n  <head>\n    <title><|title|></title>\n    <style>\n    </style>\n  </head>\n  <body>\n    <|content|>\n  </body>\n</html>'
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
read 9 files in 0.38 seconds
read outline in 0.60 seconds
reading settings in /Users/swot/learn/learn.leo

**Comment by tbpassin** [comment]
I have fixed the failure to render markdown.  I have created a PR for it:

[#1951](https://github.com/leo-editor/leo-editor/pull/1951)

The initial part of your log that reads
~~~
Can't find /Users/swot/.leo/vr3/vr3_config.ini so VR3 
cannot execute non-Python code
~~~
has nothing to do with the Markdown issue, BTW.  It just means that you have not configured any external language processors for other code languages, which is fine because they are completely optional.

If you want to try out the change before the PR gets processed, it's in the tbp-vr3-1 branch of my git clone at

[tbp-vr3-1](https://github.com/tbpassin/leo-editor/tree/tbp-vr3-1)

**Comment by wangzhaohe** [comment]
It runs well now! Thanks!

**Comment by tbpassin** [comment]
: ) Sorry for messing you up.  It was a careless little error on my part.
