### ISSUE TITLE
Unable to copy text from Log pane -- incorrect context menu?

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#2000]
I am unable to copy text from the Log pane with the current devel commit (f8342ca3).  I'm unsure how long this behavior has existed, but I believe that I was previously able to cut and paste from and to the log window with context menus before.

I imagine the incorrect context menu is appearing, and not firing off the proper back-end event.

Ctrl+C/Ctrl+X/Ctrl+V still work as before.

**Comment by tbpassin** [comment]
I can confirm that.  Copying with the Copy menu item in the context window didn't work for me.  The selected text was not copied and the clipboard contents were not changed.  CTRL-C still works.  I would never have noticed because CTRL-C is easier for me than the context menu so I have never tried it.
