### ISSUE TITLE
Use slots in all classes in leoNodes.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2004]
mypy recently discovered a bug arising from a misspelling of an ivar of the VNode class. Using slots will prevent such bugs.  In addition:

- slots help pylint and mypy check code.
- slots reduce the memory footprint of positions and vnodes.
- slots prevent unwanted alterations of Leo's most important classes.

**Comment by tbpassin** [comment]
I've started experimenting with slots.  I've found one thing I hadn't realized.  If you create a class that inherits a Qt widget, then setting slots prevents a ``__dict__`` from being used but does not cause an exception to be raised if you assign a new non-slot attribute at runtime.

I took the following example from this [web example](https://www.python-course.eu/python3_slots.php) except that I inherit the class from _QMainWindow_  instead of from _object_.

```
from leo.core.leoQt import QtWidgets
class S(QtWidgets.QMainWindow):

    __slots__ = ['val']

    def __init__(self, v):
        self.val = v

x = S(42)
print(x.val)

# Expected this to raise "AttributeError: 'S' object has no attribute 'new'"
x.new = "not possible" # No exception raised
```
This does not raise an AttributeError.  If the class is changed to inherit from _object_, the exception gets raised as expected.

**Comment by tbpassin** [comment]
Here is an easy way I often use to create a sequence of strings such as is used in defining slots:
```
__slots__ = '''c p
               browser
               current_text 
               doc 
               editor 
               editor_csspath 
               editor_style 
               handlers 
               host_editor 
               render_button 
               render_kind 
               render_pane_type
               render_widget 
               rst_csspath
               rst_stylesheet 
               stacked_widget
               switching'''.split()
```
This is way easier than type each identifier with its surrounding quote marks.  You don't even have to write them one to a line, just use whitespace separation.  But if you do it one to a line you can just add them in any order and then use the _sort-lines_ command.

**Comment by edreamleo** [comment]
I am going to close this issue. Please file new issues for any further problems.
