### ISSUE TITLE
Leoeditor.com search can't read ctrl characters or punctuation

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#203]
I've been confounded by the website search function for a long time. Thankfully the discussion about documentation and a comment from Reinhard at https://groups.google.com/forum/?fromgroups#!topic/leo-editor/iYqxrPvr1qs prompted another try :)

examples: A search for 'mod_http.py' or '@clean' reports 'Your search did not match any documents.' 
However a search for 'http' or 'clean' is successful.
Including any ctrl character breaks the search.

Also it seems including *any* punctuation breaks the search.
A search for:
'http' is successful.
'http.py' is not.
'Mulder' is successful.
'Mulder/Ream' is not.

Regards
Lewis

**Comment by edreamleo** [comment]
​> ​
Also it seems including *any* punctuation breaks the search.

​Thanks for this.  This may be a sphinx bug: I didn't write the javascript
for the search box.  I don't see anything obvious at http://sphinx-doc.org/
Not sure what the relationship is between sphinx and http://sphinxsearch.com
.

EKR

**Comment by tbnorth** [comment]
@edreamleo - I think the alternate homepage in eda764f fixes this, if you want to try uploading it to the site.  There was something similar in the repo. prior to eda764f, but it never made it to the site - we discussed it some time ago and agree it was better to drop the Sphinx search altogether rather than offer two search options (eda764f drops Sphinx), downside is some delay in new content making it into the search results, but I'm guessing not much of a delay, and not being able to find directives is a major issue.

**Comment by edreamleo** [comment]
At last I have uploaded the new index.html to Leo's web site.
