### ISSUE TITLE
can't using @ignore in @clean nodes

### ISSUE THREAD

**Issue by wesley628** [leo-editor/leo-editor#204]
when i using @ignore in @clean nodes, it always said "Orphan node", can't save the code file.

without @ignore, @clean just a tree-view code editor, pls fix this.

**Comment by edreamleo** [comment]
> when i using @ignore in @clean nodes, it always said "Orphan node", can't save the code file.

This is a typical restriction for @file, @auto, @shadow and @clean trees.  It can't be changed for @file or @auto trees because *all* data must reside in the external file.

It might be possible to allow @ignore subtrees in @shadow trees because the @ignore'd data could, in theory, be written to the private shadow file.  However, that would complicate the @shadow update algorithm.

Similar remarks apply to @clean.  The outline could contain the @ignore tree.  Modifying the update algorithm to handle the @ignore trees might be relatively straightforward.  I'll have to think about this.

> without @ignore, @clean just a tree-view code editor, pls fix this.

Whatever Leo's merits or failings, they are not significantly impacted by the lack of support for @ignore in various kinds of @<file> nodes. There are easy and obvious alternatives to using @ignore in @file, @auto, @shadow and @clean trees.

**Comment by wesley628** [comment]
i try @shadow it's same to @clean, can't use @ignore.
the alternatives for @ignore, i found @doc only. it's not so handy.

i think the best part of leo is : u can write your code and doc in 1 place, and use them to generate code file. to do this u have to choose which part IN file, and which OUT of file, the @ignore is the key. it's very important.

i still suggest to making @ignore usable in @clean, mark which part will not show in the generated file.

**Comment by edreamleo** [comment]
I am rejecting this request for reasons given above.
