### ISSUE TITLE
Qt6: Review values for Modifier vs KeyboardModifier enums

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2068]
See PR #2078. You guessed it. They have changed.

- [x] Simplify dropEvent. Test with qt6/5.
- [x] find-all for Modifiers and KeyboardModifiers.

#2069 now prevents crashes in event handlers from causing Leo to exit.

**Comment by tbpassin** [comment]
To make it more confusing, in qt6 at least there are two nearly similar names:

```
enum Qt::KeyboardModifier
flags Qt::KeyboardModifiers
```

In some cases I have just lookup up the enum values and made them into declared constants, rather than try to figure out how to get them for the various QT versions.  It seems that the actual values don't change.  Examples from QT6 docs:


<html>
<body>


Constant | Value | Description
-- | -- | --
Qt::NoModifier | 0x00000000 | No modifier key is pressed.
Qt::ShiftModifier | 0x02000000 | A Shift key on the keyboard is pressed.
Qt::ControlModifier | 0x04000000 | A Ctrl key on the keyboard is pressed.


</body>
</html>

**Comment by edreamleo** [comment]
On Fri, Jul 16, 2021 at 4:57 PM tbpassin ***@***.***> wrote:

> To make it more confusing, in qt6 at least there are two nearly similar
> names:
>
Yes. It's a right horror show. Happily, the uses of Modifiers and
KeyboardModifiers are fairly uniform. A few cff's should show that Leo
handles them all the same way.

Imo, the new problems are a sign that it was good to move the logic into
leoQt5.py and leoQt6.py.  We'll see. In extremis I'll declare that Qt6
support will have to wait until Leo 6.5, but I don't think that will be
necessary.

Edward

**Comment by tbpassin** [comment]
I completely agree about using LeoQT to patch up differences.  It may be a bit confusing if someone looks up the Qt API and sees "KeyboardModifier" while LeoQt calls it "KeyboardModifiers".   Aside from aliasing to both forms, though, I don't see what else Leo can do.

**Comment by edreamleo** [comment]
On Fri, Jul 16, 2021 at 6:53 PM tbpassin ***@***.***> wrote:

> I completely agree about using LeoQT to patch up differences. It may be a
> bit confusing if someone looks up the Qt API and sees "KeyboardModifier"
> while LeoQt calls it "KeyboardModifiers". Aside from aliasing to both
> forms, though, I don't see what else Leo can do.
>

The principle I am following is to use the latest spellings (the Qt6
spellings) for all constants.

I discovered a few hard crashers today. These affected only Qt6, so I think
it's fair to say that using Qt6 is a bit more risky than using Qt5.  But
not nearly risky enough to withdraw support for Qt6.

Edward
