### ISSUE TITLE
ALT-X In Find Pane Does Not Put Focus In Minibuffer

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2094]
I thought this had been fixed, but it the fix seems to have gotten lost in 6.4 b1.

**EKR**: The previous issue was #2041. See PR #2100.

Hitting ALT-X leaves the cursor in whatever line edit it was in (Find or Replace), and the ALT-X gets inserted there along with whatever command you type thinking that you were in the minibuffer.

**Comment by edreamleo** [comment]
This is a worthy bug. It involves the horrible innards of Leo's key binding code.

It took considerable searching to discover that dw.create_find_findbox and dw.create_find_replacebox create the QLineEdit widgets that contains the find/replace text. There are no wrappers for these widgets (don't ask me why).

At first I thought the problem was a missing call to qt_gui.setFilter in the two methods above. But adding a call to setFilter in  dw.create_find_findbox/replacebox killed *all* the key handling in the two QLineEdit widgets.

**Comment by tbpassin** [comment]
Thanks, @edward!  Quite a journey.

**Comment by edreamleo** [comment]
@tbpassin You're welcome.

**Comment by tbpassin** [comment]
The change works on my machine:

```
Leo 6.4-devel2, 6.4 branch, build 79a07fbb38
2021-07-27 06:12:53 -0500
Python 3.9.5, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) 

```
