### ISSUE TITLE
Make `websockets` address family work for IPv4-only

### ISSUE THREAD

**Issue by ar-jan** [leo-editor/leo-editor#2119]
I'm checking out leointeg (looking good @boltex!), and noticed: if IPv6 is disabled (a common setup when using a VPN), starting leoserver results in `OSError: [Errno 99] error while attempting to bind on address ('::1', 32125, 0, 0): cannot assign requested address`. I guess leoserver can safely default to specifying `socket.AF_INET` instead of using the default `AF_UNSPEC`?

> family can be set to either socket.AF_INET or AF_INET6 to force the socket to use IPv4 or IPv6. If not set, the family will be determined from host name (defaults to AF_UNSPEC).
> https://docs.python.org/3/library/asyncio-eventloop.html#creating-network-servers

**Comment by boltex** [comment]
All right, found out that the .serve method of the websockets python library has a way to specify the family (or any other parameters that the underlying "create_server" method would accept) because of this nice feature of the websocket's "serve" method's parameter handling: 
**"Any other keyword arguments are passed the event loop’s create_server() method."**

Which is what is needed to specify using the IPv4 family. 

so it's an easy addition - I'll make a pull request for felix-server4 branch later today :)

**Comment by edreamleo** [comment]
On Mon, Sep 27, 2021 at 1:23 PM Felix ***@***.***> wrote:

> All right, found out that the .serve method of the websockets python
> library has a way to specify the family (or any other parameters that the
> underlying "create_server" method would accept) because of this nice
> feature of the websocket's "serve" method's parameter handling:
> *"Any other keyword arguments are passed the event loop’s create_server()
> method."*
>
> Which is what is needed to specify using the IPv4 family.
>
> so it's an easy addition - I'll make a pull request for felix-server4
> branch later today :)
>
Thankyou!!

Edward

**Comment by boltex** [comment]
@ar-jan Can you test the felix-server4 branch? I've no easy ways to test this - if it works I'll make the pull request! Thanks!

I just added a try/exept block for the server creation: 
```
    try:
        server = websockets.serve(ws_handler, wsHost, wsPort)
    except OSError as e:
        print(e)
        print("Trying with IPv4 Family", flush=True)
        server = websockets.serve(ws_handler, wsHost, wsPort, family=socket.AF_INET)
```

The error may be triggered later when the server is actually used with : 
`realtime_server = loop.run_until_complete(server)`
So I'm not sure if this simple fix is just too premature or simple... Thanks!

Félix

**Comment by ar-jan** [comment]
Hi @boltex, that doesn't do the tricket yet:

> $ python leo/core/leoserver.py
> Starting LeoBridge... (Launch with -h for help)
> LeoServer: init leoBridge in 0.62 sec.
> Traceback (most recent call last):
>   File "/home/arjan/Programs/leo-editor/leo/core/leoserver.py", line 3866, in main
>     realtime_server = loop.run_until_complete(server)
>   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.9/asyncio/tasks.py", line 691, in _wrap_awaitable
>     return (yield from awaitable.__await__())
>   File "/home/arjan/.virtualenvs/vscode/lib/python3.9/site-packages/websockets/legacy/server.py", line 1042, in __await_impl__
>     server = await self._create_server()
>   File "/usr/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
>     raise OSError(err.errno, 'error while attempting '
> OSError: [Errno 99] error while attempting to bind on address ('::1', 32125, 0, 0): cannot assign requested address
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/arjan/Programs/leo-editor/leo/core/leoserver.py", line 3895, in <module>
>     main()
>   File "/home/arjan/Programs/leo-editor/leo/core/leoserver.py", line 3883, in main
>     realtime_server.close()
> UnboundLocalError: local variable 'realtime_server' referenced before assignment

**Comment by boltex** [comment]
@ar-jan  oh, thanks to the more verbose details you provided, I now see that the error is triggered by the line :

`realtime_server = loop.run_until_complete(server)`

I have no idea how to test for the availability of IPv6, so I'll get the server setup **and startup** in an embedded try/except block which does the same ' family=socket.AF_INET' fix in case of error. (instead of just the server setup line be in the try/except block)

Can you try the felix-server4 branch again? Thanks man!!

Félix

**Comment by ar-jan** [comment]
Great, that works!

> LeoServer: init leoBridge in 0.63 sec.
> [Errno 99] error while attempting to bind on address ('::1', 32125, 0, 0): cannot assign requested address
> Trying with IPv4 Family
> LeoBridge started at localhost on port: 32125.
> Ctrl+c to break
