### ISSUE TITLE
vim plugin does not work as described

### ISSUE THREAD

**Issue by jurov** [leo-editor/leo-editor#217]
Using Leo 5.1-final, build 20151028094354 under Linux, gvim 7.4.769

Documentation http://leoeditor.com/plugins.html?highlight=vim#vim-py says:

> By default, the plugin opens nodes on icondclick2 events. (double click in the icon box)

Not working, I tried to add the setting to myLeoSetting to no avail. I have to issue vim-open-file comand to minibuffer. Can't find any vim related command in Commands menu, either.

> Leo will update the node in the outline when you save the file in VIM.

File is not updated, nor when Vim is closed. Must be refreshed in Leo. 

No errors were logged throughout.

**Comment by edreamleo** [comment]
On Fri, Nov 13, 2015 at 5:52 PM, Juraj Variny <notifications@github.com>
wrote:

> Using Leo 5.1-final, build 20151028094354 under Linux, gvim 7.4.769
>
> Documentation http://leoeditor.com/plugins.html?highlight=vim#vim-py says:
>
> By default, the plugin opens nodes on icondclick2 events. (double click in
> the icon box)
>
>
​Thanks for this report.  I'll return to fixing bugs in the next day or so
and I'll have a look at this.

EKR

**Comment by edreamleo** [comment]
>> By default, the plugin opens nodes on icondclick2 events. (double click in the icon box)

> Not working...I have to issue vim-open-file command to minibuffer.

Leo does not support icondclick events directly, as per note 15 [here](http://leoeditor.com/writingPlugins.html#summary-of-event-handlers).  A recent rev updates plugins.html so it no longer refers to the icondclick handlers in the vim plugin. This was a *minor* documentation issue because the documentation clearly indicate that icondclick events can only be created by the double-click-icon-box command.

> Can't find any vim related command in Commands menu, either.

None were ever promised, afaik.

>> Leo will update the node in the outline when you save the file in VIM.

> File is not updated, nor when Vim is closed. Must be refreshed in Leo. 

A serious issue.  I'm working on it.

**Comment by edreamleo** [comment]
Rev 9ef2b262 fixes all known problems, and simplifies both the code and user interaction.
It works as expected on Ubuntu and Windows 10.
I'm going to close this now. The code is certainly good enough for Leo 5.2.
Please reopen only if serious problems are found.
