### ISSUE TITLE
Cursor Position on Paste

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#219]
I have a question.

It would be useful to me to have the position of the cursor retained when copy/pasting text.

For example: If I begin selecting a word/snippet of text from the left to the right and I paste it, the cursor remains at the end of the string. If I select from right to left and then copy/paste, the cursor still goes to the end of the string. It would be more consistent for me if it were to remain at the beginning of the string, if that was where it was during the copy/paste operation.

None of the other applications I tested on my Linux box display this behaviour either, so I imagine that there is a good reason why no one does this but I can't think of what it might be.

So, is there a good reason why no one does this and how hard would it be to add this to Leo with a setting to allow the user to choose the desired behaviour?

**Comment by edreamleo** [comment]
I'm not sure the exact answer for this, but Qt's cursor positioning methods probably do not allow what you want. For example, see comments in qtew.setSelectionRange.

**Comment by JohnLunzer** [comment]
I have experience with this issue and have solved it in my own (unreleased) refactoring plugin which needed to make sure that the cursor stayed in the same place after replacing an arbitrary number of strings of arbitrary length. 

It *should* be a simple matter of injecting this code before the paste to save the cursor location:

```python
widget = c.frame.body.widget
scrollPosition = widget.getYScrollPosition()
textCursor = widget.textCursor()
tCurPosition = textCursor.position()
```

and running this code after the alteration of the text to restore the cursor location:
```python
widget.setYScrollPosition(scrollPosition)
textCursor.setPosition(tCurPosition + offset)
widget.setTextCursor(textCursor)
```

```offset``` would be set to 0 if you wanted the cursor to stay at the beginning of the word or set to len(pastedString) if you wanted to put the cursor after the pasted text.

It shouldn't be a problem integrating it into the current paste code.

**Comment by JohnLunzer** [comment]
There would also have to be a check to see if the cursor lined up with the beginning or the end of the selection, which should also be possible. If the cursor is set at the end of the selection then the difference of the length of the string under the selection and the pasted string would become ```offset```.

**Comment by JohnLunzer** [comment]
Edward I have worked this out via the present interface for qtew (rather than the raw Qt interface I referenced in earlier posts). I removed the YScroll stuff (as extraneous) and it's a modest change to def pasteText.

In fact the final behavior is subtle enough that I'm not sure anyone who wasn't bothered by the original behavior would even notice if I submitted the changes. The new behavior feels more logical, the cursor goes where you would expect instead of always to the end of the paste. If you gave me the okay I could just submit the changes without the switch. 

That said, I embarrassingly have **no idea** how to create a settings switch to turn it on or off!

**Comment by edreamleo** [comment]
On Thu, Nov 19, 2015 at 2:19 PM, John Lunzer <notifications@github.com>
wrote:

> That said, I embarrassingly have *no idea* how to create a settings
> switch to turn it on or off!
>
​    mySwitch = c.config.getBool('my-switch',default=True/False)

gets​

​the contents of @bool my-switch.

EKR

**Comment by JohnLunzer** [comment]
Done for qtew, not going to worry about headlines and minibuffer.

I would like the new behavior to be default. Like I said, most people are likely not going to notice it if they haven't taken note of the current behavior. The new behavior makes more sense in the fact that the cursor stays where it was before instead of jumping somewhere new.

**Comment by edreamleo** [comment]
@JohnLunzer If the change is subtle, go ahead and make the new behavior the default for now.  We can always reconsider if people report problems.

**Comment by JohnLunzer** [comment]
Checked in.
