### ISSUE TITLE
Support @auto x.json

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#225]
I don't know how important this is.  I use JSON frequently.  JSON is very widely used.

**Comment by SegundoBob** [comment]
The lack of support for JSON is probably due to JSON's lack of support for comments.

The lack of Leo-Editor support for JSON led me to use @nosent to create JSON files.  For @nosent files the lack of JSON support for comments is not a problem because Leo-Editor does not put the node headlines or the GNX's in the external file.  Leo-Editor support would color the JSON syntax appropriately.  That is what I desire.

I believe the lack of JSON support for comments is not a problem for @clean files either.

I don't have a non-ugly idea of how to allow @file to be used to create a JSON file.  My ugly idea is to use @file to make a .jsonp (JSON plus comments) file, and then provide an "export" commend in Leo-Editor to export the @file xxx.jsonp subtree to a .json file by stripping the comments.

**Comment by JohnLunzer** [comment]
I hadn't seen this here... my solution to this has always been to use @language yaml. YAML is a superset of JSON and so in theory the YAML highlighting rules should highlight JSON completely. That said Leo still doesn't automatically recognize JSON files.

**Comment by edreamleo** [comment]
On Fri, Dec 4, 2015 at 12:01 PM, SegundoBob <notifications@github.com>
wrote:

> The lack of Leo-Editor support for JSON led me to use @nosent
> <https://github.com/nosent> to create JSON files.
>
​Sure, that would be one way.

This is a timely discussion because of the recent work supporting Jupyter's
.ipynb files, which have JSON format.  Just this morning I was considering
the way forward:

1. Importing x.ipynb should create ​@auto x.ipynb.
2. The @auto read/write code should special case .ipynb files.

There is hardly any real choice involved.  Yes, Importing could create any
other kind of @<file> node, but that wouldn't be truth in advertising,
because handling .ipynb files really must be done differently.

The .ipynb importer/exporter code hides the details of both the JSON syntax
*and* the Jupyter JSON schema, found at
site-packages\nbformat\v4\nbformat.v4.schema.json:

1. The .ipynb importer code strips the JSON cruft and, more importantly,
massages the Jupyter cells so that they are properly arranged and labelled.

2. The .ipynb exporter code will turn *any* Leo outline into a .ipynb file
that satisfies this schema, something that is tricky for code to do, and
basically impossible to do by hand.


> My ugly idea is to use @file <https://github.com/file> to make a .jsonp
> (JSON plus comments) file, and then provide an "export" commend in
> Leo-Editor to export the @file <https://github.com/file> xxx.jsonp
> subtree to a .json file by stripping the comments.

​
In general, I avoid paired files if at all possible.

I recommend following the path that I took for .ipynb files, customized for
your unique situation. The importer could check for, say, .xxx or .xxx.json
files. See @file ../commands/convertCommands.py, the trees:

    ccc.import-jupyter-notebook
    ccc.export-jupyter-notebook

I'll give some thought to registering custom .json importers/exporters. The
idea will have the @auto import/export code special case particular file
extensions.

Edward

**Comment by edreamleo** [comment]
I think the proper way is to support @auto importer & exporter for .json files.

In general there are no standard json keys, but that doesn't matter for @auto x.json. The @auto exporter will define keys used by the importer.

Somehow I have possession of example .json code. I'm using that now to create the importer/exporter.

**Comment by edreamleo** [comment]
I've changed the name for this item to better reflect my plans.

**Comment by edreamleo** [comment]
Rev 2e8d9df appears to complete this item.  From the checkin log:

> OMG: this was so easy, and so effective.
> In particular, all uA's are saved and restored.
> @auto x.json is at least as easy to use as @file.

Please reopen if there are problems.

**Comment by gatesphere** [comment]
https://github.com/leo-editor/leo-editor/commit/2e8d9df4bb39f4017d308e5bcaa9c5f0ff07e054#diff-333f869556a69fddfd15aac3a71f2e53R3

Might want to update that docstring :)

**Comment by edreamleo** [comment]
@gatesphere I see nothing wrong with the docstring. Everything has been surprisingly easy, even if there was a small glitch with clones.

**Comment by gatesphere** [comment]
@edreamleo It's super minor, but the docstring for '@file writers/json.py' reads:

'''The @auto write code for vimoutline (.otl) files.'''

Presumably you meant:

'''The @auto write code for JSON files.'''

**Comment by edreamleo** [comment]
Done.
