### ISSUE TITLE
Column Select In Body?

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2279]
Some text editors have an ability to select a rectangular area, which can then be copied or cut.  This can be handy sometimes.  Most of the times I have used it, I have pasted in a source with extra columns from somewhere else, and I want to remove the extra ones.

In thinking about how it should work, the trickiest bit is probably what should happen if a block is pasted into existing text.  I don't know if different editors handle this differently or not.

**Comment by wangzhaohe** [comment]
The following is from LeoDocs.leo. Selecting some text with mouse or keyboard arrow key, then between the first cursor and the end cursor is the columns that being selected.

***

.. _`Emacs rectangle commands`: http://www.gnu.org/software/emacs/manual/html_node/emacs/Rectangles.html

The following commands emulate the `Emacs rectangle commands`_::

    rectangle-clear
    rectangle-delete

    rectangle-open
    rectangle-close

    rectangle-kill
    rectangle-yank

    rectangle-string

Given::

    I'm really glad the docs are being updated. I know that's a
    monumental task. I only use a fraction of Leo's commands, mostly
    because I don't even know what they're supposed to accomplish. A few
    examples:

Placing the cursor immediately before the first "I", holding shift and moving it to immediately before the word``examples`` selects a zero width rectangle from the beginning to the end of the selection (zero width because the selection starts and ends in the same column.  Then running ``rectangle-string [largo]<space><enter>`` yields::

  [largo] I'm really glad the docs are being updated. I know that's a
  [largo] monumental task. I only use a fraction of Leo's commands, mostly
  [largo] because I don't even know what they're supposed to accomplish. A few
  [largo] examples:

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen if you have more questions.

**Comment by tbpassin** [comment]
@wangzhaohe, I did _ALT-x rectangle-open_  and did a selection but only got an ordinary selection, not a rectangular one.  If that's not the way to do it, then the whole thing is so obscure that it's as if it isn't a real feature.  Also, I don't know what the emacs-like _yank_ does with regard to getting something into the ordinary clipboard., which is what I expect.

Yes, I knew about those commands and so far haven't gotten them to work for me.

**Comment by edreamleo** [comment]
@tbpassin rectangle-open uses the beginning and ending columns of the selection as the column markers.  For example, let the body text be:

```
line 1
line 2
line 3
```
Now select everything except the first and last characters (not including the trailing whitespace.  rectangle-open should give you
```
l    ine 1
l    ine 2
l    ine 3
```
HTH.

**Comment by tbpassin** [comment]
IMHO, if you are selecting in rectangle mode then the selection highlight should be exactly that rectangle. For example, Notepad++ visibly selects a column if you hold the ALT key down while selecting with the mouse or arrow keys.  That's the capability I was hoping for.

**Comment by edreamleo** [comment]
@tbpassin Fair enough. I doubt if many people use the rectangle commands, so feel free to create a PR that works as you would like :-)

**Comment by tbpassin** [comment]
Pretty challenging if there is wordwrap going on! I think the editors I know about disallow rectangle mode if they are wordwrapping.
