### ISSUE TITLE
Fix problem with Windows key on Linux

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2344]
See PR #2344.

From [this post](https://groups.google.com/g/leo-editor/c/GSRn1E67BeE/m/ZM8EpXDPBAAJ) from gar:

Leo enters symbols like ៀ? into it's editor when user presses Win key? This does not happen when using the Leo released in May. I am under ubuntu 20.04 and cant say if the same can be reproduced under Windows.

**From gar**

I see the same behavior with leo v6.5 and v6.4, but not with v6.3.

Playing with python and Leo versions, I got the following result when enabling --trace=keys, and pressing the win-key
```
Python 3.9.9 (fyi, same result for python 3.7.12) + leo 6.5
        masterKeyHandler None 'ៀ\udc53' <KeyStroke: 'ៀ\udc53'>
        selfInsertCommand ch 'ៀ\udc53'

Python 3.9.9 + leo 6.3
        traceKeys    shortcut-override:         ''
        traceKeys    shortcut-override:         ''
        traceKeys            key-press:         ''
        traceKeys            key-press:         ''
        traceKeys          key-release:    Meta ''
        traceKeys          key-release:    Meta ''

fyi: I'm running Arch Linux and the spectrwm window manager.
```

**Comment by edreamleo** [comment]
@tbpassin Many thanks for your efforts. Because of [this discussion](https://groups.google.com/g/leo-editor/c/GSRn1E67BeE) I am going to reopen this issue.  I have assigned it to you because you can now reproduce the problem. 

Later today I'll write an ENB describing what should be done.  The short version:
- LeoQtEventFilter.eventFilter should return False for the Windows key.
- The test for the Windows key should be based on the keynum value obtained in LeoQtEventFilter.toBinding and used in several of toBinding's helpers. Qt likely defines a symbolic name for this keynum.

**Comment by edreamleo** [comment]
@tbpassin From [this page](https://doc.qt.io/qt-5/qt.html#Key-enum): On Windows Keyboards, Qt::MetaModifier and Qt::Key_Meta are mapped to the Windows key. Caution: I'm not sure how to handle this special case properly without messing up more standard ways of using the Meta modifier!

**Comment by tbpassin** [comment]
The problem is only showing up on Linux these days, although I seem to recall it on my windows machine last year, before you did something to fix it.

Linux should be intercepting the Win key, because all these distros use it to open up the app launch menu.  For it to get passed to an app is just wrong.  BTW, it seems to me that the Win key on Kububtu gets passed to Leo *before* the app menu starts to open. That's even stranger.  SHIFT-Win getting to an app might be understandable since the desktop manager isn't using it for anything.  I imagine there's a way in Linux to route th t key stroke to the bit bucket, but I have no idea how.

Anyway, we have to practice defensive programming here - if we were able to tell users how to fix their desktop manager configuration, it might re-occur in the future.  That would not be a good permanent fix, though it might get folks like Gar in business for  while.

**Comment by edreamleo** [comment]
@tbpassin Thanks for these remarks. Imo, any change should apply only on Linux (`sys.platform.startswith('linux')`).

**Comment by tbpassin** [comment]
I've made some progress.  On Windows, the raw key code for the left Windows key is 0x5b.  On XWindows (Linux) - as distinct from the linux non-X console - it is 0xffeb.  If you ignore the FF (which is 1111, which as a mask changes nothing), the binary codes are

```
Windows   0101 1011
XWindows  1110 1011
```

I saw the same with both KUbunbtu and Mint.  However, these are not the codes for the problem symbols, and I haven't really seen a relationship there.

You can get these linux key codes by running the xev utility in the console.  Fpr Windows, I used the Sharpkey utility program (a free download), or you can get them from a MSDN table.

**Comment by edreamleo** [comment]
@tbpassin Good work. No need for an ENB :-)

**Comment by tbpassin** [comment]
Just submitted a PR to fix this by filtering out the 0x1000053 key on linux.  Worked on both Debian and Kubuntu VMs.  This is done in the LeoQtEventFilter, as suggested by @edward.

Let's hope this magic number doesn't change in the future!

**Comment by tbpassin** [comment]
Just to fill out the Qt keyPressedEvent results:

```
Windows: key: 0x1000022, native scan code: 0x15b, Native virtual key: 0x5b
Kubuntu: key: 0x1000053, native scan code: 0x85, Native virtual key: 0xffeb
Debian:  key: 0x1000053, native scan code: 0x85, Native virtual key: 0xffeb
Mint:    key: 0x1000053, native scan code: 0x85, Native virtual key: 0xffeb
```
`0xffeb` is the value returned at a linux console using the _xev_  utility.

I wonder if that 0x1000053 value is getting sent to a character table, but some of the installations are using a font that doesn't have any glyphs for those codes while some are using a font that does - and that's why we're seeing a difference.
