### ISSUE TITLE
help-for-command Should Expand << docstring>> Sections

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2369]
I have written some commands whose docstrings are detailed enough for me to have put them into their own << docstring >> sections.  However, in this case, F11/help-for-command only returns _<< docstring >>_.

It would be useful of docstring section references like this were expanded by _help-for-command_.

**Comment by edreamleo** [comment]
What command are you talking about?

**Comment by tbpassin** [comment]
The one invoked by F11.  A command (e.g., mine) has a longish docstring with a <<section>> or two.

**Comment by edreamleo** [comment]
@tbpassin I was asking which of your commands has a docstring contained in a section reference.

Anyway, I am inclined not to do this item. The relevant code is g.getDocStringForFunction. This function does not have easy access to the position that contains the function/method/class whose docstring we want. I do not want to further complicate g.getDocStringForFunction.

Instead, there should be a straightforward workaround.  Instead of defining """<< docstring >>""", as I assume you are doing, you can define a << docstring >> section whose contents are the desired docstring. That way, python's inspect module should deliver the proper docstring.

I may be wrong about what I have just said, which is why I am asking for a particular command so that I can see exactly what is happening.

**Comment by tbpassin** [comment]
Yes, the command that elicited my issue does start with \<\<docstring\>\>:

```
def plot_2d():
    << docstring >>
   # imports, etc follow
```

The Leo display for the F11 command is:

`no docstring available`

Previously I have also tried `"""<< docstring >>"""`, as I thought you had advised a while ago (but won't work now since the section has to be alone on its own line), and then F11 simply reported `<< docstring >>`.

The other variation that doesn't work either is

```
"""
<< docstring >>
"""
```

This particular docstring is fairly long and detailed, so I would rather tuck it away in a named section.

**Comment by edreamleo** [comment]
@tbpassin Thanks for the new info.  I'll take a look and see whether some solution is possible.

**Comment by edreamleo** [comment]
Rev 9085b40 in devel converts the docstring for the vr3-plot-2d command:

- Moved the docstring from the plot_2d function to the vr3_plot_2d function.
- Flattened the docstring.

With these changes, help-for-command works for vr3-plot-2d.

This rev also suppresses a traceback:

`AttributeError("'QWebEngineSettings' object has no attribute 'DefaultFontSize'")`

I hope you don't mind.  Imo, this kinds of changes are better than trying to do AI on docstrings.

**Comment by tbpassin** [comment]
I was just about to tackle the AttributeError, which I noticed a few days ago.  That's one of those qt5 vs qt6 things, I think.  Setting that default font size isn't of much practical effect, I  think - I think my standard stylesheets all set it anyway, IIRC.  I'll take a look at this new changeset in a bit.

**Comment by tbpassin** [comment]
Looking at this changeset, I'm happy that the docstring displays.  I'm less happy about the need to flatten it, though I can live with that.  And I'm quite unhappy about there now being no docstring in the command that does all the actual work.

Let me chew on that last for a while, see if I can come up with something to fill the gap.

**Comment by edreamleo** [comment]
@tbpassin I'll close this issue, but I'll be happy to look at a PR.

**Comment by tbpassin** [comment]
I have other commands that are defined in an @command node in the @commands tree, and their `<< docstrings >>` are not getting picked up.
