### ISSUE TITLE
Chapters enhancements

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#238]
Chapters have a few limitations that when combined with clones could help create views:
- Chapters have the same limitation as hoists when switching between nodes. If I switch between clones and one clone is inside a chapter and the other isn't I will lose my chapter view by switching to the clone outside the chapter and then attempting to switch back to the clone inside the chapter.
- Allow any node to be a chapter without the @chapter directive. Remove the need for a top level @chapters node.
- A Chapter-clone-marked-to would be a nice.
- By default when I come back to the main view from a chapter view it appears to randomly collapse chapter nodes. From a user expectation perspective the expand/collapse state of the outline should not change by default (for clones/hoists/chapters/etc), if collapse behavior is desired it can be enabled through settings. There is currently no option in the global chapter settings to change collapse behavior.  

These suggestions are based on this [thread](https://groups.google.com/forum/#!topic/leo-editor/vtSEq3jekcg).

**Comment by edreamleo** [comment]
I had forgotten this request when I wrote [this](https://groups.google.com/d/msg/leo-editor/-mv2x_6TAdM/Bgntt7b9AgAJ). As explained there, and a reply to your email, I think less is more, especially since it's possible to move @chapters nodes anywhere.

For this reason, I am going to close this item.  Feel free to continue the discussion.
