### ISSUE TITLE
Add copy-node-as-json command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2481]
See PR #2482.

Félix suggests that JSON is preferable to XML for some purposes.  Leo already supports .leojs files. See #442, which defines the JSON format used in .leojs files.

**Update**: I agree with Thomas that the only change that should be made is a new copy-node-as-json command.

**Comment by tbpassin** [comment]
I don't see why json would be preferable.  The format has always been xml.  My new save node as outline command wouldn't work.  The code for pasting the copied node would have to change.  Instead of making a major change to the way an existing command has always worked, just create a new command.

Anyway, liking json better may be a personal thing for Fekix, but liking xml better is a personal thing for me.

I suggest that Leo should have json to xml and xml to json converters.  Then anyone can end up with whatever they want without much trouble.

**Comment by edreamleo** [comment]
@tbpassin I find your arguments persuasive.
