### ISSUE TITLE
Leo and Stickynote plugin do not request to save

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#249]
When I edit a node using a Stickynote popout window and close the popout window, the node body text updates as expected. But when I close the leo tab there is no request to save the file.
Also when I directly close the visually updated leo file tab, there is no recognition that the file is edited and no confirmation request to save the file.

Leo Log Window
Leo 5.3-devel, build 20160327164927, Sun Mar 27 16:49:27 CDT 2016
Git repo info: branch = master, commit = 86449baa801a
Python 2.7.11, PyQt version 4.8.7
Windows 7 AMD64 (build 6.1.7601) SP1

**Comment by edreamleo** [comment]
A call to p.setDirty() should do the trick.

**Comment by edreamleo** [comment]
Fixed at 067fc23fdfe. From the checkin log:

    This plugin has major problems, which I'll leave it to the original author to fix:

    1. The insertion point is not visible in the popup window.
    2. The window has no menu, so one must use alt-space c to close it from the keyboard.
    3. Closing the window changes text, but this is not undoable.
    4. Encryption does not work for Python 3.

I can not recommend this plugin in its current state. Don't ask me to work on this further.

**Comment by tbnorth** [comment]
> 1. The insertion point is not visible in the popup window.

Fixed in 52cf694 - it's amazing how long I've been tolerating this nit :-) I'm guessing long ago it worked and Qt changed the requirement to call base class focusIn/OutEvent.

> 2. The window has no menu, so one must use alt-space c to close it from the keyboard.

People who choose to avoid using the mouse should know their window manager's window close shortcut. Window managers should have a single key (with modifier) window close shortcut. I use the i3 tiling window manager, and I know the window close shortcut ;-)

> 3. Closing the window changes text, but this is not undoable.

More generally changing the text changes the text, and is not undoable.  Will try and get to that.

> 4. Encryption does not work for Python 3.

Have started work on this.

**Comment by edreamleo** [comment]
Thanks, Terry, for your work on this.
