### ISSUE TITLE
Improve app.setIdFromDialog

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2519]
See PR #2520 and PR #2523.

app.setIdFromDialog should call sys.exit if the user refuses to supply a valid leoID.

**Comment by vitalije** [comment]
> app.setIdFromDialog should call sys.exit if the user refuses to supply a valid leoID.

I don't think that is a very good idea. I would suggest that in this case Leo should generate random string. Most users, especially new ones, don't have any idea what the leoID is all about, and I believe that there is really any benefit in the ability to choose leoID. It would work perfectly well with any string.

If two or more people work together on some outline, then perhaps it is beneficial to have different leoIDs but even if they use same leoID,  probability to have a gnx clash is very small and possibility that two of them would create the same random string during the setup is almost zero.

If you think that this might happen, then perhaps leoID should look like three-four random letters followed by the number of milliseconds since the unix epoch.

I remember some new users have had problem that they couldn't install Leo because there were some issues with the showing the dialog. For example, users that want to use console GUI don't need to have installed neither Qt nor Tkinter, but they couldn't use Leo because it crashed every time trying to show the dialog. I would argue that for the most users it would be much easier if Leo hadn't asked them for leoID on the first launch.

We could say that setting the leoID is advanced feature for those who care about what their gnx will look like. Most users don't care at all, about that, and yet it is the very first (potentially confusing) experience they will have with Leo.

**Comment by edreamleo** [comment]
@vitalije I considered, and rejected, these kinds of behaviors.​  The leoID is something that should be descriptive, as the dialog that prompts for them explains.

**Comment by edreamleo** [comment]
@vitalije This issue exists because of a request from Félix. This is not the time or the place to re-imagine the role of leoID.

**Comment by tbpassin** [comment]
As long as a user never has to later supply an ID that he may not remember, I suppose it's OK.  We never want to have a user locked out of their outlines because of forgetting the user ID.

**Comment by edreamleo** [comment]
@tbpassin The worst that could happen is that Leo would again prompt for an id after the user mistakenly deletes leoID.txt (don't ask me how or why). There is never any need to remember anything: any id will do.

**Comment by boltex** [comment]
@tbpassin @vitalije  

Just to reassure that this is a small change, and not a behavior breaking change: At very worst, this only changes behavior if used via leobridge: it would make Leo use an id string of  'None' for the current running session, without saving it to .leoId.txt file, if not found and not provided. So it's pretty safe and benign.

In other case, out of leobridge utilization, 'standard' Leo just exists cleanly with an error message instead of crashing if id not provided anywhere at all, and if no dialog UI available for some reason. 

Thanks for your concerns,

It's a great honor to collaborate with such famous leonistas as you two! :)

...and don't hesitate to correct me if i'm wrong !
--
Félix

**Comment by tbpassin** [comment]
"It's a great honor to collaborate with such famous leonistas as you two!"  \*cough\*, \*choke\*, \*sputter\* (speaking only for myself, of course!).

It seems that it will be all right.  My concern has been that either someone forgets their id and then can't even open Leo to access their own outlines, or that because of some system or user error that id file gets clobbered, with the same result.

It sounds like in this last case, you could go into the .leo directory and recreate an id file with some arbitrary id in it.  So it might be a good thing that the error message in the case of a missing or empty id file explained this.

I actually had a failure-to-start today, and I got the default non-GUI message box.  It was quite a shock.  I had been removing packages from the system Python install directory and reinstalling them into my Python user directory.  Apparently I borked pyqt somehow.  

So I know what a jolt it would be for someone to get hit with this condition.

I re-installed PyQt6 to the user location and all was well.

**Comment by edreamleo** [comment]
Fixed by #2523.

**Comment by vitalije** [comment]
@tbpassin the value of `leoID` isn't very important for starting Leo. As Edward have said any value will work.
The only reason it exists is to reduce the possibility of having two different nodes with the exactly same `gnx`. Theoretically speaking this can happen if two different users with exactly the same `leoID` create a node at exactly the same time each. Of course those two users have to work on two different machines or two different Leo instances. If the created node is part of some external file that these two users share, then it can happen that one of them loose some data because of the `gnx` clash.

In reality however, the chances that this would happen are extremely small.

As a side effect of manually selecting the `leoID` value, one can look at the external files content and see who has created which part of the file. This may be interesting only in the case where multiple users collaborate on the same outline. For users who work alone, this isn't important at all, because every created node is created by the same user.

Bearing in mind that in the situation where multiple users do work together on the same outline, they most likely have some kind of version control like git, fossil, or something similar. Every version control tool has its own command to show which part of the code was created by which person. So, having recognizable `leoID` doesn't seem to be very important after all.

I don't want to argue about this any further. I was just thinking loud.

**Comment by edreamleo** [comment]
@vitalije Thanks for your comments. I agree with them all.
