### ISSUE TITLE
Allow mypy command to run without blocking Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2594]
See PR #2599.

**Comment by tbpassin** [comment]
Assuming that my changes to bpm work as well as I think they do, this proposal seems like it would add complexity for no real value to a user.

**Comment by edreamleo** [comment]
@tbpassin You may be correct. I do, however, review the existing code in light of existing developments.

**Comment by edreamleo** [comment]
@tbpassin I have changed the title of this issue and clarified the idea in the first comment of this issue.

**Comment by tbpassin** [comment]
Yes, I took a look at the mypy setup, and it is a bit of a mess in terms of refactoring to the new bpm system.  I would suggest refactoring so that there is a mypy.run() or a run_mypy() method so that the mypy processing looks as similar to the pylint processing as possible.  All the pylint processing code for retrieving the output, computing the links, and outputting to the log pane is now handled by bpm.on_idle and bpm.put_log().  That should become the case for mypy as well.

The more parallel the mypy code is to the pylint, the easier it will be in the future to understand them both, and the less likely it will be that someone might introduce a change that doesn't work right.

It seems to me that the only real differences between running mypy and pylint (and some other checker in the future) are

1. The command line details, and
2. The regex for the output.

Everything else should be essentially the same, and if done well could serve as a template for adding a new checker in the future.  In particular, one thing that would be the same would be the method of finding the files to check and verifying them.  No use in having a new solution each time for the same job.

Sounds like a reusable utility method would be a good idea.  I'm not quite sure where its home should be...

**Comment by edreamleo** [comment]
@tbpassin Thanks for these remarks. They are similar to my own thinking. I'll be working on this issue soon.

I'll certainly try to avoid code duplication, but I'm not sure a helper is advisable. Sometimes duplicating code turns out to be the simplest, best, way.
