### ISSUE TITLE
[Question] New to Leo, how can I get a GUI on MacOS 12.4?

### ISSUE THREAD

**Issue by davidleejy** [leo-editor/leo-editor#2683]
Installation instructions on Leo's website are for Lion a v10.x OS.

Managed to install Leo in a python environment (Anaconda), what is additionally needed/ what would one have to do to get the GUI running?

Much thanks,

**Comment by tbpassin** [comment]
Do you mean what command to use to run Leo, now that it has been installed?

**Comment by tbpassin** [comment]
The command that I use to run Leo from a terminal is

```python3 -m leo.core.runLeo```

There are other ways, but this one does not require that any paths or icons be set up correctly.  If your Python 3.x installation runs with a different name, use that instead of "python3".  I don't have any specific knowledge of any Mac-specific quirks, but it should work as long as all Leo's dependencies have been installed, which they presumably were as part of the Leo install.

**Comment by davidleejy** [comment]
Thanks. This works.
