### ISSUE TITLE
Duplicate chapter name (name too long?)

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#269]
With all of the recent work on @chapters, maybe this slipped through the cracks. I opened a file that contains two @chapters:

@chapter FSS - Level 1
@chapter FSS - Level 2

When the file opens, I get this error in the log pane:

Error: duplicate chapter name: FSS-Level-

Also, looking in the Chapter drop-down box, I see that the chapter names were converted to the same name: FSS-Level- (spaces removed)

Is there a baked in limit to the size of @chapter names? It looks like there is and it appears to be 12 characters.

**Comment by largo84** [comment]
Maybe the problem is with the '-' (dash). I shortened the @chapter names to FSS - 1 and FSS - 2 and now I see them in the drop-down box as FSS- and still get the duplicate chapter error.

**Comment by edreamleo** [comment]
On Fri, Apr 22, 2016 at 11:47 AM, Rob Keeney <notifications@github.com>
wrote:

> With all of the recent work on @chapters <https://github.com/chapters>,
> maybe this slipped through the cracks. I opened a file that contains two
> @chapters <https://github.com/chapters>:
>
> @chapter <https://github.com/chapter> FSS - Level 1
> @chapter <https://github.com/chapter> FSS - Level 2
>
> When the file opens, I get this error in the log pane:
>
> Error: duplicate chapter name: FSS-Level-
>
​That's the expected behavior.​

> Also, looking in the Chapter drop-down box, I see that the chapter names
> were converted to the same name: FSS-Level- (spaces removed)
>
> Is there a baked in limit to the size of @chapter
> <https://github.com/chapter> names? It looks like there is and it appears
> to be 12 characters.
>
​There's no limit, but numbers were not allowed.  Rev d2c99c1 fixes this.

There is a problem with renaming chapters.  I've put this on the list.

Edward



> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/leo-editor/leo-editor/issues/269>
>



-- 
------------------------------------------------------------------------------------------
Edward K. Ream: edreamleo@gmail.com Leo: http://leoeditor.com/
------------------------------------------------------------------------------------------

**Comment by edreamleo** [comment]
Everything fixed at 076edc4.  Happily, the new code is simpler and more general than ever.

setAllChapterNames is called before doing anything requiring a list of chapter names, so chapters can now be renamed dynamically.  However, when renaming a chapter from x to y, the old chapter-select-x command remains.  That's a nit, because the callback will either get the correct chapter anyway, or issue a warning.
