### ISSUE TITLE
Can't click all urls in the release notes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2705]
In particular, this url does not work at present:
`https://github.com/leo-editor/leo-editor/issues?q=is%3Aissue+milestone%3A6.6.3+`

The trailing '+' is neither colored nor recognized as part of the url.

g.url_regex is supposed to match any url. The colorizer contains similar code in the node:
`jedit.match_url_any/f/h`.

~~See [this page](https://gist.github.com/gruber/8891611) for a supposedly proper url.~~

**Update**: For clarity and safety, Leo now colorizes and handles gnxs only if they start with "gnx:".

**Comment by tbpassin** [comment]
From what I've read, it's almost impossible to write a fully general regex for an arbitrary URL because nearly anything can be a URL. On top of that, some URLs aren't formed correctly but our code should work with them anyway.  For example, "+" is a reserved delimiter.  If it is used in a non-delimiter fashion, it should be %-escaped (see [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-1.1.3)).

So the example URL appears to be non-conforming but we want to have it work anyway.

From [URL Validation](https://cran.r-project.org/web/packages/rex/vignettes/url_parsing.html):

"Creating a correct regular expression is hard! (only 1 out of 13 regexs were valid for all cases)."
