### ISSUE TITLE
Enhancement: optionally delay syntax coloring

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#272]
Per [this discussion](https://groups.google.com/d/msg/leo-editor/y8EJQ3py8sc/vPL17cTKCQAJ), it would be good to delay syntax coloring of large nodes, possibly under control of another user option.

The original suggestion was to delay syntax coloring when arrow keys are down. Another would be to delay coloring of large nodes until idle time.

**Comment by tbnorth** [comment]
On Mon, 25 Apr 2016 06:32:28 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> Per [this
> discussion](https://groups.google.com/d/msg/leo-editor/y8EJQ3py8sc/vPL17cTKCQAJ),
> it would be good to delay syntax coloring of large nodes, possibly
> under control of another user option.
> 
> The original suggestion was to delay syntax coloring when arrow keys
> are down. Another would be to delay coloring of large nodes until
> idle time.

Maybe a useful test would be to prefix all the nodes in an outline
displaying the problem (which I agree exists) with @nocolor, and
checking performance then.  If things are still more laggy than
desired, it might be better to avoid populating the body pane at all
until the up / down keys are released, assuming that can be detected,
I'm sure it's possible.

**Comment by JohnLunzer** [comment]
Terry's comment is fully applicable. I did not state this clearly enough in the discussion. @nocolor is not enough. It is a very large part of the slowdown but the larger a node gets the more just its length becomes a big problem. As per my original post in the forum, part of the fix was to empty the body pane **and** not do syntax highlight. So if not populating the body pane means that syntax coloring doesn't take place that is the most complete solution.

**Comment by edreamleo** [comment]
@JohnLunzer @killcolor is what you want.  There is a big performance difference.

However, the larger issue is whether you should ever be using huge body text.  The problem with "big text" is essentially a Qt bug that hasn't been fixed, which means Leo is stuck with it.

**Comment by edreamleo** [comment]
I have just assigned this for Leo 5.4.  It's too late in the release cycle to mess with this now.

**Comment by JohnLunzer** [comment]
Agreed, it was not in the 5.3 release plan so should not be include.

**Comment by JohnLunzer** [comment]
After some further usage I have noted that I still see slowdown when I press the up/down key rapidly (rather than holding it down). So checking if the up/down key is being held down is likely not a complete solution. 

I am wondering if a simple time delay would do the trick. Starting with 200ms might work without artificially introducing a perceptible delay.

**Comment by edreamleo** [comment]
Fixed at  0dcce11. The new code is straightforward.

However, as mentioned in #273, syntax coloring is **not** the cause of the unwanted pause when selecting nodes with large text.  Instead, the delay is due to an apparently unavoidable call to `w.setPlainText`.
