### ISSUE TITLE
how to change shortcut keys

### ISSUE THREAD

**Issue by andrewchenshx** [leo-editor/leo-editor#2745]
how can I change/customize the shortcut keys? for example, I would like Tab for "move right", Shift+Tab for "move left", and Enter for "insert node".

thanks

**Comment by tbpassin** [comment]
You assign shortcuts in myLeoSettings.leo.  You create a node with the headline "@shortcuts" (without the quotes), and put your shortcuts into the body of this node.  Then you have to reload settings (or better, restart Leo).  

Each shortcut command has to be a Leo command that you could run from the minibuffer.  You use the name of the command in the shortcut definition.

Here is part of my own @shortcut body:

```
# Marks
goto-next-marked = F4
mark = F9  # This is a toggle command
unmark-all = F10

# Brackets and comments
match-brackets = Ctrl+]
add-comments = Ctrl+'
delete-comments = Ctrl+;
```

It looks to me like you expect to be able to define shortcuts that would only apply when the tree view has focus.  Otherwise, if you made \<ENTER\> mean something else while the body were focused, for example, how would you ever actually be able to insert a *newline* character?  I don't know how or if shortcuts can be made to apply only when the tree is focused.  Someone else will have to chime in here.

**Comment by andrewchenshx** [comment]
thanks for clarifying me.
yes, I want to define shortcuts that would only apply when the tree view has focus.
and as u mentioned, I don't think Enter is a leo command.

**Comment by tbpassin** [comment]
The general approach is to write your own commands, and bind them to the shortcut keys.  So in principle, you could write a script that checks to see if the tree or the body has focus.  If the tree has focus, then your script would execute the *insert-node* command, if the body has focus, it inserts a <newline>.  The particular case of the <ENTER> key is tricky, though, because

1. The key is no doubt already being handled by Leo's key-handling machinery, and you would have to intercept it and 

2.  There are many other circumstances in which the <ENTER> key does something and you would need to handle them all.

So rebinding the <ENTER> key doesn't sound like a good idea to me.  Either it won't work, or it would take a lot of digging to figure out how.  But some of the others should possible.

Maybe Leo already has a way to intercept a keystroke and optionally pass it on to some other handler.  Maybe you can modify the standard handler.  You might be able to write a replacement handler, and write a script that replaces the standard handler while Leo is running, but only for a particular outline.  Then you could have the special rules in effect when you want them, but no one else would be affected. That would be my preferred approach.
