### ISSUE TITLE
limit on the number of nodes

### ISSUE THREAD

**Issue by andrewchenshx** [leo-editor/leo-editor#2746]
hi all,
are there any limit on the number of nodes per leo file?
is it a good practice to put as more things as possible in ONE leo file, or split them among as more files as possible?
personally, I prefer less leo files. Once  split into two files, I usually have a feeling that they're LESS/NOT connected.

**Comment by wangzhaohe** [comment]
I think this is an entangled thing with my mind.

1. I have a leo file with 20k nodes. Then I find that the operational response is slow.
2. Now I control the nodes number is less than 10k.
3. I must make a backup file frequently because with my wrong operation or some leo design (i.e. refresh-from-disk with markdown file or same vnode with section reference).
4. I must operate carefully and slowly with many nodes file before save & close leo.
5. So if a leo file with many nodes which very important, I should run git commit before each leo quit.

Generally I love leo-editor!

**Comment by tbpassin** [comment]
LeoPyRef.leo has more than 13,000 nodes.  I don't have any problem working with it.  But many Leo operations, like find commands, look serially through all the nodes.  So depending on your computer and commands, a file with too many nodes may seem poorly responsive some of the time.  If so, it is probably time to split up the file.

Otherwise, I think it is a good idea to keep related material together in one outline.  Use good titles for major parts, or use chapters.  For example, in an outline that contains a blog that gets generated by Sphinx and aBlog,  I include a subtree that explains how to do so.

It also seems to me that Leo is snappier on my Linux virtual machines than it is on the Windows host system.  For example, large outlines seem to load faster.  However, it takes slightly longer to iterate through all nodes in LeoPyRef.leo on my Linux VM compared with the Windows host (20 - 21 ms vs 19 - 20 ms). [I wrote a little script to time the traversal.  Here it is:

```
import time

def loop_to_time(event = None):
    n = 0
    for p in c.all_positions():
        n += 1
    return n

REPS = 100
t0 = time.time_ns()
for n in range(REPS):
    positions = loop_to_time()
t1 = time.time_ns()

g.es((t1 - t0)/(1e6 * REPS), 'ms per rep', '# positions:', positions )
```
]

With regards to @wangzhaohe's remarks above, I haven't encountered most of his problems so far.  About _@file_, note that leoPyRef contains most of Leo's source code in _@file_ trees and that seems to work well.  Of course, it's always a good idea to save and back up frequently, no matter what system you are working with.

As to his point 6, I find that opening a second editor is very confusing because it is too easy to lose track of which node is showing in which editor window.  Instead, I like to use the Freewin plugin for comparing code between nodes.  The plugin doesn't have the full set of editor functions that the Leo body editor does, but it's good for displaying a node for comparison or reminder while you look at another node (that was its main design goal). A Freewin window stays locked to the node it was opened on, no matter how you navigate around the tree. You can do basic edits in a Freewin window and they will be reflected into the underlying node, and vice-versa.  You can even save the changed outline with \<CTRL-s\> while the focus is in a Freewin window.

His point 4 is a little hard for me to understand, but the key thing to know is that a *clone* paste operation keeps the node identifiers of the pasted nodes, while a non-clone paste changes them to new ones.  This is normally what you want.  But if you have some code that depends on these exact identifiers, you need to do a *clone* paste.  I have some code like that for certain special outlines.
