### ISSUE TITLE
@chapter somestring does not create binding until after I restart leo

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2748]
I found the discuss here https://groups.google.com/g/leo-editor/c/_iWLGh7ShEo/m/x-wrUNoGCAAJ

It seems that "You don't have to restart Leo for the new @chapters nodes to take effect."

And now it is still existing on my macos. My operational step is:

1. Create a new node with @chapter somestring
2. No command for chapter-select-somestring
3. restart leo: python launchLeo.py
4. run command chapter-select-somestring ok

Must I restart leo after a @chapter node created? 

***
Leo Log Window
Leo 6.6.4-devel, devel branch, build 143ad8878e
2022-08-17 21:52:05 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
That is not what I see on my system.  After I create a new @chapter node, its *chapter-select-xxx* command is immediately present and functional from the minibuffer.  I did notice that the _chapter-select-_ command is case sensitive (``chapter-select-One`` selects _@chapter One_ but does not select _@chapter one_).  Perhaps naively, I expected it to be case-insensitive.

@wangzhaohe, you use Vim mode, don't you?  Maybe that makes a difference.

**Comment by wangzhaohe** [comment]
> That is not what I see on my system. After I create a new @chapter node, its _chapter-select-xxx_ command is immediately present and functional from the minibuffer. I did notice that the _chapter-select-_ command is case sensitive (`chapter-select-One` selects _@chapter One_ but does not select _@chapter one_). Perhaps naively, I expected it to be case-insensitive.
> 
> @wangzhaohe, you use Vim mode, don't you? Maybe that makes a difference.

I have closed vim mode and all letters were lowercase. 

So could teach me how to debug this phenomenon？

**Comment by boltex** [comment]
@tbpassin I tried it too. latest dev version on ubuntu... 

after creating a new chapter, lets say @chapter banana,  alt+x does not show the "chapter-select-banana" command,,,

But, if i just do the simpler "chapter-select" and press enter, Then all choices are there, including the banana chapter.

And even more surprising: after that "chapter-select" command was issued, regardless of if i've actually chosen a chapter or just hit escape to cancel that chapter change, then, if I re-try alt+x and type "chapter-" and hit tab for auto complete, then the choice of a command called "chapter-select-banana" is there. oh oh!

So, it seems that triggering "chapter-select" creates all valid chapter-select-xxx commands, and not just inserting a new node that starts with @chapter. (it would be cool if it did ! )

**Comment by tbpassin** [comment]
@wangzhaohe, that would be hard! I've just been trying to repeat what Felix repored above.  

1. Create a new, unsaved outline.
2. Rename the unnamed node to _Head_.
3. Create a new node _@chapter banana_. Move it to be at the same level as the _Head_ node, if it is not already there.
4. Check the _Chapters_ dropdown to see if "banana" is there.  On my system, it is.
5. Delete the outline, create a new one, and do steps 1 - 3.  Do **not** check the _Chapters_ dropdown, but instead look for the command in the minibuffer.  Type "chapter-select", using \<TAB\> for convenience.  See if "chapter-select-banana" appears.  On my system, it did not.
6. Issue the "chapter-select" command.  See if you get the same behavior as @Felix did.  On my system, I did.
7.  Repeat steps 5, and then in the minibuffer type "chapter-select-banana" and press \<ENTER\>.  See if it works even though the command was not offered as an option by \<TAB\> completion.  On my system, it did work, and after that \<TAB\> completion did offer "chapter-select-banana" as one of the options.

These results seem to show that, at least sometimes, the new _chapter-select-xxx_ command may be present but not installed in the _Chapters_ dropdown or in the command list known to the \<TAB\> completion  code.

Maybe this information will be enough for someone who knows the _Chapters_ code to figure it out.

I do not see this behavior as very bad, since as soon as you create a new chapter and populate it with a few nodes, the dropdown and the correct command are going to work and after that everything seems to work as expected.  Only \<TAB\> completion seems to be a little questionable when the new command is first created.

**Comment by wangzhaohe** [comment]
1. Create a new, unsaved outline.
2. Rename the unnamed node to *Head*.
3. Create a new node *[[@chapter](https://github.com/chapter)](https://github.com/chapter) banana*. Move it to be at the same level as the *Head* node, if it is not already there.
4. Check the *Chapters* dropdown to see if "banana" is there. On my system, it is.
   * **Banana not in Chaptesr dropdown list.**
5. Delete the outline, create a new one, and do steps 1 - 3. Do **not** check the *Chapters* dropdown, but instead look for the command in the minibuffer. Type "chapter-select", using <TAB> for convenience. See if "chapter-select-banana" appears. On my system, it did not.
   * **"chapter-select-banana" is not there.** Only *chapter-select && chapter-select-main* are there.
6. Issue the "chapter-select" command. See if you get the same behavior as [[@felix](https://github.com/felix)](https://github.com/felix) did. On my system, I did.
   * Yes, it did. A "Select chapter" hint is waiting for an input after issued a "chapter-select" command. Then banana is there. So it was a special design for this case.
7. Repeat steps 5, and then in the minibuffer type "chapter-select-banana" and press <ENTER>. See if it works even though the command was not offered as an option by <TAB> completion. On my system, it did work, and after that <TAB> completion did offer "chapter-select-banana" as one of the options.
   * "chapter-select-banana" has been there. But a new "@chapter apple" has the same phenomenon with the first launchLeo as a new "@chapter banana".

Thanks for [[@boltex](https://github.com/boltex)](https://github.com/boltex) and [[@tbpassin](https://github.com/tbpassin)](https://github.com/tbpassin) ! You give me a way to use "chapter-select"(Enter).

***

Leo Log Window
Leo 6.6.4-devel, devel branch, build 6edaa86241
2022-08-20 07:01:06 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
@wangzhaohe, do you feel this issue can be closed now, or is there more you would like to pursue about it?

**Comment by edreamleo** [comment]
@wangzhaohe Thanks for your thorough report. Imo, this issue should remain open.

**Comment by wangzhaohe** [comment]
@tbpassin @edreamleo, Running "chapter-select+Enter" is enough for me. Thanks!

**Comment by edreamleo** [comment]
@wangzhaohe Alright. Closing the issue now :-)
