### ISSUE TITLE
Show global line number in lower left status bar

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#283]
It would be useful to show the global line number in the lower left status bar, there appears to be plenty of room.

Reference the forum [post](https://groups.google.com/forum/#!topic/leo-editor/-tFrCflsY24).

**Comment by edreamleo** [comment]
This could easily slow Leo significantly.  To prevent that, Leo would have to compute the line number of the first line of p.b whenever p is selected.  That would be non-trivial.

**Comment by edreamleo** [comment]
> Create a command that would calculate the offsets of all items in an @<file> tree.

This command is especially ugly because changes to any node invalidates the computed file offsets in all following nodes.  Ditto for any tree insertions, deletions, rearrangements.

Hmm.  The more I think about this, the less I like it. The goto-global-line (Alt-G) command handles the most important use case: determining which line in an outline corresponds to a line given in an error message.

I'll leave this open for awhile longer, and I won't add the Won'tDo tag just yet, but it seems like the costs far outweigh the benefits.  I'm surprised by this conclusion, but for now it seems valid.

**Comment by edreamleo** [comment]
Rev d7a8c39 completes work on this project for now.

I expect that there will be no way forward, so I am going to add the Won'tDo label and close this item.

Please reopen if you know of a way around the problems I have described.

**Comment by JohnLunzer** [comment]
Thank you for looking into it, too bad about the performance, we'll survive without I suppose ;)
