### ISSUE TITLE
More flexible imports for .json files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#284]
[Original discussion](https://groups.google.com/d/msg/leo-editor/k0TS8JGxNiA/GleSjF2lAgAJ)

A helper class, JSON_Import_Helper (jih) would contain all the general code. You could say that this helper class is conceptually similar to the RecursiveImportController class.

Client scripts would tell the jih class what elements are to create outline structure, which elements should be ignored, and which elements are to create headline text, body text, or even may uA's.

See also: #442.

**Comment by edreamleo** [comment]
This item will have low priority until someone tells me that it would actually be useful, so at present it will not be targeted to 5.4.

**Comment by tbnorth** [comment]
On Fri, 06 May 2016 08:55:49 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> This item will have low priority until someone tells me that it would
> actually be useful, so at present it will not be targeted to 5.4.

I think I understand how it would be useful, but I also think you're
right in thinking it would need a helper class to actually handle each
specific case.

There's a parallel in the xml_edit plugin, which import and exports XML
in Leo, with namespace and attribute support, and making maximum use of
Leo's tree to display the XML.

By itself, it imports according to the rules in the doc string,
basically element names are in headers and text content is in the body.

But there's a simple database description schema I use, and use
xml_edit to edit, DTD is here:
https://github.com/tbnorth/trans/blob/master/dml.dtd but basically
think of it as

<table>
  <name>List of foos</name>
  <field>
    <name>id</name>
  </field>
  <field>
    <name>foo_text</name>
  </field>
</table>

The vanilla xml_edit imports this with only 'table', 'name', and
'field' as headers, but a domain specific helper script, the helper class
I think the JSON case would need to, appends the name element body content 
to the parent's header, so you can actually see the structure in the tree.
This works because xml_edit only looks at the the first whitespace free 
part of the header when exporting.

Bottom line I don't think there's a non-code way of describing how to
import things in a domain specific way - you could use some kind of
XPath-ish notation to explain how to do the import, but anyway who could
parse that could probably handle the code based approach.  And the code
based approach will always be most flexible, e.g. it could insert info.
about child counts etc. into the headers.

Cheers -Terry

**Comment by edreamleo** [comment]
#1098 probably suffices.
