### ISSUE TITLE
show-(commands|bindings|settings|plugins-info) show up in rightmost tab

### ISSUE THREAD

**Issue by karstenw** [leo-editor/leo-editor#2931]
On macos 10.13.6; leo 6.7.0; miniconda Python 3.9

All the show settings commands print their results repeatedly in the rightmost tab, not in the tab the command originated.

Is this a bug or a feature?

**Comment by tbpassin** [comment]
I think it's a feature.  Tabs can be used for all kinds of purposes, not just a log-style  listing.  For example, what if you had a calendar in a tab?  Or you had run some code in the Python Console tab so you could see the results.  You wouldn't want it to be trashed just because you wanted to run a command or check the settings.

**Comment by edreamleo** [comment]
@karstenw Yes, this feature is intended. I don't think there is a command to delete a particular tab, but (for example)

`c.frame.log.deleteTab(Settings)`

will delete the Settings tab.
