### ISSUE TITLE
vr3 ruby syntax NOT coloring 

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2967]
It seems that ruby code in vr3 NOT be coloring.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/2628013/202911295-f6d1ad9c-9b38-416b-9c02-a374e401688f.png">

***
Leo Log Window
Leo 6.7.2-devel, devel branch, build 7b89be3fa6
2022-11-16 13:47:11 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
VR3 only tries to use pygments for syntax coloring.  Even if you installed Rouge, VR3 will not know to use it.

However, after I installed asciidoctor and pygments.rb, when I run asciidoctor stand-alone in a terminal, I don't get syntax highlighting so far.  I'm not sure, but the Ruby gem for pygments somehow uses Python, and it may be trying to use the a different Python executable than I'm using to run Leo.  I don't know yet how to find out.

I do get highlighting when I use the _highlight.js_ highlighter stand-alone.  I could modify VR3 to use it instead.  This highlighter operates in the browser. rather than having asciidoctor insert the highlighting.  If that works, would that be satisfactory for you?

**Comment by tbpassin** [comment]
I tried it, but the highlight.js highlighter doesn't work in the VR3 pane, although it does work when the rendered result is exported to an external browser.

**Comment by tbpassin** [comment]
I have found a solution (at least, it works for asciidoctor).  Where you would write
`[source, ruby]`, use `[source%, ruby]` instead.  This assumes you have the pygments gem installed.

I'm guessing this is a bug in asciidoctor.  I tried it because I noticed this in an example: `[source%linenums, ruby], and this did display line numbers.

I find that asciidoctor does not like blank lines in these code blocks.  The lines after a blank line do not get colored.  I don't see how this can be a VR3 problem;  it must be a quirk of asciidoctor - perhaps something about Linux vs Windows line endings.

This solution only works for asciidoctor;  some other solution is needed for asciidoc and asciidoc3.

**Comment by wangzhaohe** [comment]
@tbpassin Thanks for your quick reply in time!

With this solution, we can use only one leo file to achieve:

1. @file save to disk and run the code.
2. presentation with VR3 in leo-editor.
3. export .adoc file with command `adoc`.

I think it is wonderful!

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/2628013/202930982-ed8cc8ec-156f-4dd4-ab2c-45896f07b46c.png">

**Comment by tbpassin** [comment]
@wangzhaohe, 

"With this solution, we can use only one leo file to achieve:

https://github.com/file save to disk and run the code.
presentation with VR3 in leo-editor.
export .adoc file with command adoc.
I think it is wonderful!"

Thank you!  This is one of the things I tried to achieve with VR3.  Don't forget that you can export the rendered HTML to a browser (and save it from there), and you can also get the entire marked-up tree into your text editor with the Leo command `vr3-open-markup-in-editor`.

(However, VR3 does not understand `@others` nor `<< named sections >>` (maybe some day)).

**Comment by tbpassin** [comment]
Can we close this issue now?

**Comment by wangzhaohe** [comment]
> 

Yes, I always use export button to create a html file named leo_rst_html.html, then use chrome browser saved as a pdf file.

**Comment by wangzhaohe** [comment]
> (However, VR3 does not understand @others nor << named sections >> (maybe some day)).

I hope some day that VR3 will support  `Execute` the whole outline with @others and sections. 

But now we can use `execute-script` and `ipython-exec` to achieve the goal.

And another excited function will be to save the running result somewhere like jupyter-notebook.

**Comment by tbpassin** [comment]
I have a few lengthy subtrees - RsT, not asciidoc - that can be executed to produce graphs that are embedded in the outline.  Since the executed outline can be exported to the browser, it is shareable - not interactively, to be sure.  For Leo users, they can be shared, of course.  For everyone else, they can be shared in static form.

The design does not support saving running results.  All the code fragments are collected together, and when executed all the code is treated as if it were all in a single python file.  Any printed output is captured and appended to the end of the subtree so it can be seen, but this will be lost the next time the tree is rendered.

This design is fairly straightforward to implement, but limited in what it can do.
