### ISSUE TITLE
add-editor suddenly changed different node body content to same text

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2992]
This phenomenon has occurred several times already. Is there some steps to debug this? Did anyone encountered this phenomenon?

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/2628013/205796938-3977c3b9-c966-46b4-bb4a-42c93b0d82e4.png">

shell print bellow message:

```shell
updateAfterTyping p.b != w.getAllText() p: script
w:  <QTextEditWrapper: 5599936464 body>
end_insert_mode,done,save_body,afterChangeBody
```

ref: https://github.com/leo-editor/leo-editor/issues/2366

***
Leo Log Window
Leo 6.7.2-devel, devel branch, build 1a4277d65e
2022-12-06 10:20:24 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by wangzhaohe** [comment]
Reproduce it when mouse click back from chrome browser.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/2628013/205804535-23786be2-0210-4c84-b43d-3fab98561a78.png">

shell print:

```
updateAfterTyping p.b != w.getAllText() p: node1
w:  <QTextEditWrapper: 5543947184 body>
on_activate,quit,save_body,afterChangeBody
```

**Comment by tbpassin** [comment]
I do not fully understand what you are describing.  But having several editors open at the same time can lead to confusion (I have been bit by this too many times, so I don't use multiple editors any more).  It's easy to overlook what node is in each editor, and which editor is focused.   

Since it is hard to notice which editor is focused, it's even easier to start working with the wrong one.

Usually I want a second editor open so that I can refer to one node while editing another, not because I want to do extensive editing in both nodes.  Nowadays I use the Freewin plugin for that.  The plugin lets you open a basic editing view of a node.  It's not a full Leo editing window, but it does do bi-directional editing communication with its underlying node.  Each Freewin window is tied to one and only one node.  That node never changes even when you select a different node while a Freewin window is open.  This minimizes the chance of confusion.

In addition, it can switch to a  rendering mode that renders a node in RestructuredText, somewhat like VR3.  (So far it does not render asciidoc, but I might be willing to undertake that if there is enough interest).

The minibuffer command to open a freewin window on the selected node is `z-open-freewin`.  I used to put it in a button, but now I add it to a custom menu that is available to all open outlines.  You can have as many Freewin windows open as you want.

**Comment by wangzhaohe** [comment]
@tbpassin Thanks! I am using freewin now. This is what I am looking for.

Add a @shortcuts in myLeoSetting.leo

```
z-open-freewin = Ctrl-Shift-Z
```

**Comment by tbpassin** [comment]
Good to hear!  I hope you will find it very useful.

**Comment by tbpassin** [comment]
Can this issue be close now?

**Comment by wangzhaohe** [comment]
@tbpassin freewin plugin is another solution. Will `add-editor` mode be fixed later?

**Comment by edreamleo** [comment]
@wangzhaohe I'm not going to change this part of Leo's code.

**Comment by edward** [comment]
Very cool! I’m curious what that experience has been like.

**Comment by edreamleo** [comment]
@edward I continue to use the desktop version of Leo. Félix uses vs-code/leoInteg exclusively, I think. Besides leoInteg, Félix is working on [leoJS](https://github.com/boltex/leojs) (Typescript-only leoInteg). His work on leoJS continues to suggest refinements to leoInteg.

But don't take my word for it. Ask Félix directly :-)

**Comment by edward** [comment]
Great! Please do jump into the public chat if you have any questions or ideas: https://discord.com/invite/FTJr9gP – I’m sure there’s lots to share between the tools.

**Comment by wangzhaohe** [comment]
@tbpassin I will close this issue since edward is not going to change this part of Leo's code. And we have another solution by freewin.
