### ISSUE TITLE
Log window doesn't get line separators

### ISSUE THREAD

**Issue by lonetech** [leo-editor/leo-editor#301]
Running leo from git on Windows using Anaconda 3 Python installation, the log window doesn't separate lines for most messages, only the initial version printing. This makes it quite impractical to see what issues occur. Example below. 

> Leo Log Window
> Leo 5.4-devel, build 20160722143100, Fri, Jul 22, 2016  2:31:00 PM
> Git repo info: branch = master, commit = aca8d416ec35
> Python 3.5.2, PyQt version 4.8.7
> Windows 8.1 AMD64 (build 6.3.9600) SP0
> saved: fit2google.leoError: inconsistent leading whitespace. tabs converted to blanksinserting @ignoreimported D:\Source\VivoSmart steps\fit2google.pyimported D:\Source\VivoSmart steps\googleapi.pyError: intermixed blanks and tabsError: inconsistent leading whitespace. tabs converted to blanksinserting @ignoreimported D:\Source\VivoSmart steps\readfit.py

**Comment by edreamleo** [comment]
This doesn't happen for me, and we can be pretty sure that it doesn't happen for other people either because the log window would be unusable for anyone with your problem.

Clearly, something very strange is happening with your build.

Rev 50b1043f changes LeoQtLog.put slightly.  See if that helps.

If not, set trace = True in LeoQtLog.put (search for it in the headline) and report your results.

**Comment by edreamleo** [comment]
I am going to close this for now.  I do not believe this is an actual bug.  Something weird, like an installation problem, is going on.
