### ISSUE TITLE
vr3 adoc issue: command adoc output path not in project directory

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#3032]
@tbpassin With https://github.com/leo-editor/leo-editor/pull/3027, I put an example, Please have a check about it. Thanks!

Test steps:

1. Download vr3adocIssue.zip

3. open vr3adocIssue.leo by leo-editor

4. run command adoc in leo-editor on the @adoc google.adoc node.

5. The google.adoc may be created in the following directory.

    adoc: wrote /Users/swot/app/leo-editor/leo/core/google.adoc

    adoc: wrote /Users/swot/app/leo-editor/google.adoc

    adoc: wrote /Users/swot/google.adoc

    adoc: wrote /Users/swot/learn/example_adc/google.adoc (in my project directory, wanted)

6. A relative img path is used in the project directory example_adoc

    image::img/googlelogo_color_272x92dp.png[]

7. So the asciidoctor command will not find the googlelogo_color_272x92dp.png if the created google.adoc not in example_adoc directory. So the google.adoc should be copied to the example_adoc directory manually.

    asciidoctor google.adoc

8. I found to change the bellow code that would let google.adoc created in the project directory example_adoc by leo/core/leoMarkup.py.

    #i_path = g.os_path_finalize(i_path)
    n_path = c.getNodePath(c.p)  # node path
    i_path = g.os_path_finalize_join(n_path, i_path)

Please have a check about this phenomenon.

[vr3adocIssue.zip](https://github.com/leo-editor/leo-editor/files/10348650/vr3adocIssue.zip)

**Comment by tbpassin** [comment]
Your example is a little confusing to me because the instructions above do not agree with the instructions in your Leo outline.  However, when I ran Leo's adoc command on the @adoc node, the result included a file named _google.html_.  That file displayed the Google logo, so the relative path must have been correct.

Your code change (above) is included in the version I am running, so your change did work for me in this example.  Thank you for explaining it to me.  

I will close this issue now, since the PR has been merged and it seems to do what you want.

**Comment by wangzhaohe** [comment]
@tbpassin Perhaps you mean  /Users/swot/app/. This is my computer's path.

**Comment by tbpassin** [comment]
Not the path, the file names are different.

**Comment by wangzhaohe** [comment]
Oh, sorry!

`example_adc/google.adoc` should be `vr3adocIssue/example_adoc/google.adoc`
