### ISSUE TITLE
Fix bugs in find-all and related unl code

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3101]
See PR #3103 for details.

- [x] Fix bugs in unl logic.
- [x] Fix bugs in find-all logic.

**Comment by tbpassin** [comment]
I'll look at it.  I just have to make up a test document and a shortcut to point to it.  I want to get this working right since I use shortcuts to collect  many of my outlines in one place.

I would have thought that the standard file open dialog would have taken care of symbolic links, so I'll see if I can understand that angle, too.  Maybe the best place to handle the issue is when the outline is opened.

**Comment by tbpassin** [comment]
On Windows 10, when I open an outline from a shortcut, `c.fileName()` has the full path to the real outline, not the path to the link.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your investigations. I'll attempt to create a reproducible scenario.

**Comment by edreamleo** [comment]
@tbpassin This may be a bug in the new find-all command. I can recreate the problem. It may have nothing much to do with unls, but we shall see...

**Comment by edreamleo** [comment]
Closed via PR #3103.
