### ISSUE TITLE
XDG Base Directory on Linux

### ISSUE THREAD

**Issue by paolomi** [leo-editor/leo-editor#3213]
On Linux, in order to reduce the clutter in the user's home directory, leo should use the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for its configuration directory.

For backwards compatibility, the configuration would be read initially from the current location (~/.leo). If not found, it would be read from $XDG_CONFIG_HOME/leo, with $XDG_CONFIG_HOME defaulting to $HOME/.config if not set.

Thanks a lot.

**Comment by tbpassin** [comment]
I knew there had to be something like that specification, but didn't know what to look for.

On a practical note, I checked two of my Linux VMs, and in neither of them are those XDG variables set.  I don't think that any particular application should set them itself.  I did read in the spec that certain default directories should be used if it XDG variable is missing, so I suppose that would be more or less reasonable.

One question that I've wondered about may be something that you (@paolomi) can answer.  As the specification says, if you put binaries into _~/.local/bin_, then if you move ~ to another machine (or dual boot to another version of Linux), those binaries may be incorrect for the new system.  I didn't see that the spec had a recommendation as to what to do in this case.  Is there a standard practice?

**Comment by tbpassin** [comment]
Not everything in ~/.leo is a configuration file.  There are runtime temporary files (e.g., _scriptFile.py_), possibly data files (though it can be hard to know if something is a configuration or data file), _workbook.leo_, _myLeoSettings.leo_ (which might or might not be considered "configuration", and probably many other files or directories used by various scripts and plugins.

It would be easy enough to remap _g.app.homeLeoDir_ to _$XDG_CONFIG_HOME_ as @paolomi is suggesting.  We could just ignore any further splitting up of _.leo_'s contents to other XDG_ directories.  This is what I would favor.

If we made this change, we would also have to comb through Leo's code base to change anyplace that is hardcoded to _~/.leo_.  We would have to do the same for all the docs.  And (a lessor point), it would be harder to refer to the "~/.leo" directory since it might no longer be at that actual location.  Referring to "g.app.homeLeoDir" instead would be a little awkward for non-programmer users, who might not know what that refers to or how to find the actual directory.

**Comment by paolomi** [comment]
> One question that I've wondered about may be something that you (@paolomi) can answer. As the specification says, if you put binaries into _~/.local/bin_, then if you move ~ to another machine (or dual boot to another version of Linux), those binaries may be incorrect for the new system. I didn't see that the spec had a recommendation as to what to do in this case. Is there a standard practice?

About your question: I don't know the official answer, sorry. However if I had to install compiled binaries for different architectures in $HOME/.local/bin I'd rename those binaries by adding a trailing suffix(*) and I'd run it with a simple bash script:

arch=$(uname -m)
exec binary.$arch "$@"

----

(*)  For example:
binary.i386
binary.x86_64
binary.ppc64
binary.aarch64

**Comment by tbpassin** [comment]
Thanks.  I found a similar suggestion on line, but it wasn't explained as clearly as yours so I didn't quite grasp the idea.

**Comment by tbpassin** [comment]
I'm still not convinced that _~/.config_ is the right place for the current _~/.leo_.  That's because the directory contains, or often contains, files and directories that are not configuration data.  Theoretically we could split out various bits to _~/.local/share_, _~/.config_, and maybe others to some other $XDG_ locations, but that would seem to be to be annoying or confusing for little gain.

Perhaps _~/.local/share/leo_ would be a better location for the entire directory.  

Please comment and make suggestions.

**Comment by paolomi** [comment]
I am not a developer, but I am a practical guy: if splitting out various bits is a waste of time, then ~/.local/share/leo is better than ~/.config/leo.  My purpose is to reduce the clutter in the user's home directory, so your proposal satisfies me.

**Comment by tbpassin** [comment]
It would be all right with me.  I'd like to float the idea on the Google Group to see if anyone else has objections or another idea.

**Comment by tbpassin** [comment]
Based on the discussion in the Group, I don't think this suggestion would accomplish much for many people.  No one really had any enthusiasm for it.  I'm going to mark this as :Won't Do' and close it for now.

**Comment by edreamleo** [comment]
@tbpassin I agree. This issue can be marked `Won'tDo`.
