### ISSUE TITLE
The "undefined_section_name_color" changed to "white"

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#3234]
PR #3239 changes `white` to `solarized-red`.

Rev 3d5fe63 incorrectly changed `undefined_section_name_color` to `white`. 

<details>

I did not figure out the reason after some search.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/2628013/229328258-56b7124d-61d0-4145-b773-f512f7f0b818.png">

</details>

**Comment by tbpassin** [comment]
It would be red, I think, because an undefined section is an error and red is a common warning color.  White would not stand out for a dark theme., but at the same time your image shows that the name - which you might want to use as the headline of a new node, can be unreadable on a light theme.  I's say that red is a more suitable general color, but good that it's configurable.

**Comment by wangzhaohe** [comment]
@tbpassin I think so too.

At git commit: cc012cb698f89bf822ddafdd7fb986e19f1ca772

<img width="471" alt="image" src="https://user-images.githubusercontent.com/2628013/229383462-9608ef7a-29c6-4502-be55-88de82de8046.png">

**Comment by edreamleo** [comment]
@wangzhaohe Please let me know how PR #3234 works for you.

**Comment by wangzhaohe** [comment]
@edreamleo It works well now.

**Comment by edreamleo** [comment]
Closed via PR #3239.
