### ISSUE TITLE
Support for editorconfig

### ISSUE THREAD

**Issue by doctorlard** [leo-editor/leo-editor#3237]
Being able to use/encourage/enforce code style project-wide or per-directory with a [.editorconfig](https://editorconfig.org) file would be useful. Even a minimum of a few basic things like file encoding, line endings, trailing whitespace, and the whole spaces/tabs thing would be a great start. New to Leo but happy to have a go at a PR when I get a chance.

**Comment by tbpassin** [comment]
Character encoding will have to be the same throughout the outline, since it's saved as a single XML file.  I can't see it changing from utf-8.

**Comment by edreamleo** [comment]
@doctorlard Hi Jonathan. Welcome to Leo.

Please don't bother with a PR for .editorconfig files. They aren't needed and would complicate Leo's already-too-complicated startup process. Iirc we Leonistas considered and rejected such a proposal a few years ago.

**Comment by doctorlard** [comment]
I'm not sure what you mean by "they aren't needed", they're needed by me. This means our devs can't realistically use Leo for any projects that run code style checks in CI, that use different styles in different projects, or that we contribute to that aren't under our control. That is the entire point of a .editorconfig file.

**Comment by tbpassin** [comment]
Let's see what can be done with what Leo already has.  For things like tabs/spaces,  there are settings and per-external-file directives.  For removing trailing whitespace, and similar, Leo has commands.  There are probably commands for some other similar things you might want to do.

So the question is, how can you make it practical to make them apply for a project?  For properties that can be set by settings, you can use an `@settings` tree in the project outline.  You could even write a Leo command that inserts a custom `@settings` tree into an outline.

For settings that you want to apply to all outlines, and for all devs,  you could create a tiny outline that contains all these settings, and have the devs copy them bodily into their own _myLeoSettings_ outline.

For Leo commands, I'd suggest that a script could be written that would do all the clean-up and formatting issues, and to create a button for that command.  The script and button node would be in the outline's `@settings` tree so that every time the outline gets loaded, the button would be available.

Another approach is to define a custom menu, also by means of the local `@settings` tree, that can do each or all of these things you want.    You could even write a command to insert your own settings tree into an outline.  If you want to have an .editorconfig in each directory, you can write your own command to read that file and apply its settings.  

Of course, it might be that you want to do something that Leo just doesn't provide at all, and that it would be too hard to write a script for.  Then it might be reasonable to ask for an enhancement or propose a PR.  But I bet you can get many of the capabilities you are thinking of without one.  Your devs would have to learn to press one of the buttons or use your local menu to set things up at the start of a project, and maybe use one of your formatting/cleanup menu items from time to time during working on a project.

As an example of what can be done (that one might not expect), I have a script that changes the body font to a non-monospaced font unless the node or external file is in a programming language, in which case the font will be monospaced.

As another example, when I was developing the feature to highlight the current line, I worked entirely in my Workbook outline, without actually touching any Leo internals.  I was able to monkey-patch the capability into the core by running a script.  You'd be amazed what you can do without too much effort with Leo once you start thinking that way. (Of course, there's a learning curve here!).

If you are not sure how to set up, say, a local custom menu, or any of the other suggestions I have made, just ask.  I think these kinds of topics would be good to raise on the Leo-Editor Google Group, a better place for them than here, since more people will notice them.

I hope no one will think that I am blowing off their legitimate needs.  Instead, I am trying to raise awareness of how capable and adaptable Leo truly is, once you start absorbing the different approach to working with it.  As a kind of analog, an EMACS lover will tell you that you can get EMACS to do do everything you have asked for - as long as you learn it LISP dialect and get deep into its internals.  I won't claim that Leo can be adapted as much as EMACS (but, who knows, maybe it can), but I think it's capabilities are not realized by many users.  It's much like the Leo way of handling settings.  No handy dialogs and wizards, but much more power and flexibility once you learn the Leo way.

**Comment by edreamleo** [comment]
On Tue, Jun 20, 2023 at 9:10 PM Thomas Passin ***@***.***>
wrote:

> Let's see what can be done with what Leo already has.
>
Yes. That's the proper attitude. Leo:
- has many configuration-related features
- is a general scripting environment with full access (via c, g and p) to
all of Leo's data and code.

Edward
