### ISSUE TITLE
Request for clickable_link output to other Tab.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3314]
If I add a tabName to a es_clickable link Leo gives a TypeError.

_File "C:/Users/lewisneal/.leo/scriptFile.py", line 49, in <module>
    g.es_clickable_link(c, p, 1, (node_name), tabName=('GNX_TAB'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: es_clickable_link() got an unexpected keyword argument 'tabName'_

Can es_clickable_link function allow output to other Tab?

**Comment by tbpassin** [comment]
The signature is:
`def es_clickable_link(c: Cmdr, p: Position, line_number: int, message: str) -> None`

so no, it does not let you specify a tab.  But you could write a new method to do so, since the existing one is pretty simple:

```
def es_clickable_link(c: Cmdr, p: Position, line_number: int, message: str) -> None:
    """
    Write a clickable message to the given line number of p.b.

    Negative line numbers indicate global lines.
    """
    unl = p.get_UNL()
    c.frame.log.put(message.strip() + '\n', nodeLink=f"{unl}::{line_number}")
```

`log.put` has an optional _tabName_ argument:

```
def put(self,
    s: str,
    color: str=None,
    tabName: str='Log',
    from_redirect: bool=False,
    nodeLink: str=None,
) -> None:
```
 
So you could define, say, `es_clickable_link_tab()` and have it call `put()` with a tab name.

**Comment by tbpassin** [comment]
Can this issue be closed?

**Comment by edreamleo** [comment]
@tbpassin Yes. I'm closing this issue now.
