### ISSUE TITLE
Following a link sometimes generates two node history entries

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3463]
In other words, it takes two `goto-prev-history-node` commands to undo ctrl-clicking a link.

This bug is annoying: it interferes with using gnx-based links instead of clones.

The `nav_qt plugin` is not the culprit. The fault lies in the ctrl-click logic.

**Comment by tbpassin** [comment]
I never thought of this as being something to be handled by undo.  To me, the navigation history is something separate. True, if clicking on a UNL navigated to a different outline, the forward-backword arrows probably wouldn't work, since they use the navigation history within an outline, but that wouldn't be a problem because the starting outline would still have the starting node selected.

I suggest leaving this to 6.7.5 if indeed it is decided to change something.

**Comment by edreamleo** [comment]
@tbpassin The schedule for 6.7.4 is open. I'm an investigating this issue. I would like to fix it if possible now.

**Comment by edreamleo** [comment]
Closed via PR #3465. The fix was straightforward.
