### ISSUE TITLE
Todo plugin doc inaccessible

### ISSUE THREAD

**Issue by palego** [leo-editor/leo-editor#3580]
The link to http://leo.zwiki.org/tododoc found at https://leo-editor.github.io/leo-editor/plugins.html#todo-py fails with security issues.

Output of `curl -L http://leo.zwiki.org/tododoc`:
`curl: (35) OpenSSL/3.1.2: error:0A000438:SSL routines::tlsv1 alert internal error`

**Comment by tbpassin** [comment]
That would be because of some kind of error in the SSL connection, which happens even when https is tried.  Maybe it's not configured for https at all. 

This would be something for the author of the plugin to fix, since presumably that is the owner of the web site.  I don't know who that is, though.
