### ISSUE TITLE
Enhance UNLs with relative paths and optional node specifiers

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3816]
See PR #3817.

**The proposal**

- Allow **relative paths** in UNLs.
- Allow **file-only** UNLs by making the node specifier optional.

Both features would be important additions to Leo:

- Relative paths will allow people to share `.leo` files more effectively.
- File-only UNLs are nifty way to refer to other outlines!

**Notes**

- **UNLs** with relative paths are *completely different* from `file://` **URLs**.
- Users will have to create UNLs with relative paths by hand.
  Leo's status area can never create such UNLs.

**Comment by tbpassin** [comment]
I think that most or all of the work can take place in `g.findAnyUnl()`. There will be two slightly tricky points:
1. Checking a relative UNL whose outline is not open without visibly opening it.  We don't want the user to suddenly see a lot of opened outlines he didn't expect;
2. If there is no node specifier, opening the outline and selecting its root node.  This should be easier than (1).

There is code that could be used as a model for 1) already, since Leo opens an outline without making it visible when first looking for its setup nodes, if I'm remembering that correctly.

Code for 2) should be found in the method that creates a new outline.

I also suggest that when a Unl with a node specifier turns out to point to a non-existent node, that it be treated as if there were no node specifier.  IOW, it would open the right outline anyway.  Currently no outline is opened and an error message is printed to the terminal.

**Comment by edreamleo** [comment]
Completed via PR #3817.
