### ISSUE TITLE
Leo doesn't honor new headlines when switching branches

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#385]
The decision to honor headlines in .leo files was a conscious a long time ago, but it doesn't play well with `git checkout external-file`. This is almost unbearably annoying.

**Comment by tbnorth** [comment]
Hi - I don't understand this issue and it sounds important, can you elaborate a little?  Is it about refresh from disk / external file changes while Leo's running?

**Comment by edreamleo** [comment]
On Sun, Jan 29, 2017 at 10:26 AM, Terry Brown <notifications@github.com>
wrote:

> Hi - I don't understand this issue and it sounds important, can you
> elaborate a little? Is it about refresh from disk / external file changes
> while Leo's running?
>
The problem is minor. When Leo reads an external file, headlines in the
outline override (changed) headlines in the external file.  This was fine
when there was only one branch.

One workaround would be to use a different copy of leoPy.leo in each
branch.  But this isn't necessary. It's easier to correct "incorrect"
headlines in the leoPy.leo than with git.

You would think that headlines in external files clearly should rule, but
now I remember the issue.  What about cross-file cloned headlines?  They
typically happen in "catch-all" files, like Leo's attic in
leo/doc/leoNotes.txt.

So we would like headlines in external files to rule, except when the
external file contains @all.  Alas, that won't work because the decision
has to be made before actually reading  the external file.

I'm not sure that Leo can do better than its present way.  I'll leave this
issue open, but I think dealing with headlines can (should?) be done in Leo
itself.

**Comment by tbnorth** [comment]
Ok, kind of what I thought.  The severity would be different for Python, where headlines aren't written to source, vs. markdown, where they are - if it applies to markdown too.  I'm not sure Leo's handling of external file changes is quite where it needs to be (no surprises, no loss of content without explicit direction).  I tend to open another Leo file, close the Leo file containing external files that have changed on disk, then open it again - this reflects my level of trust / comfort with the way Leo handles external changes.

It's a bit of a challenge for Leo, whereas some editors may have a dozen or so files "open" (I suspect Notepad++ etc. may lazy load tabs from previous sessions), Leo may have dozens of files loaded in ram at once.

I'll try and pay attention to the rough edges and post bug reports rather than just "close whole outline / open whole outline".

**Comment by edreamleo** [comment]
This appears to be a caching problem. When I reload leoPy.leo with --no-cache everything works fine.
I am going to close this issue for now.

**Comment by edreamleo** [comment]
**Update**: the problem isn't just about caching.  refresh-from-disk doesn't refresh headlines.

**Comment by tbnorth** [comment]
Maybe related: #470

**Comment by edreamleo** [comment]
Rev b32259 appears to fix this, without the need for the workarounds discussed [here](https://groups.google.com/d/msg/leo-editor/tKZje4gR_uQ/EwfHsUa3AAAJ).
