### ISSUE TITLE
Add color to text/strings while creating outline programmatically

### ISSUE THREAD

**Issue by rsm123** [leo-editor/leo-editor#3969]
Thank you for this wonderful project! 
I'm trying to parse a txt file and write to LEO using leobridge. Is there a way to add color to text or strings while writing text to body pane (p.b) in python?

**Comment by tbpassin** [comment]
Could you say more about what you want to accomplish? Generally speaking you won't be able to do anything using the bridge than you could by typing directly into a body from within Leo; you will only get coloring that the colorizer puts in there, which will depend on the language in effect.

Depending on exactly what you want to do, you might be able to do the parsing using a script inside Leo and skip using the bridge altogether.  That won't change the colorizing situation, though.

**Comment by tbpassin** [comment]
You are only going to get what Leo's colorizer gives you for a given file type.  As the body text is rendered by the body's editor, the colorizing will be applied.  I haven't done this using the bridge, but I don't see why it wouldn't work the same way.

There may be an easier way here.  Leo has an "Import Any File" menu item. It creates a subtree for the file, and the structure while it might not be perfect usually doesn't require much tuning by hand.  The importer for a given language may be less evolved than one for another language depending on how much use the one has gotten.  It's worth trying.

A file imported in this way is created as an "external" file, generally meaning that any edits you do in Leo will get saved in the external file.

Do I understand that you are working with CSS files?  Why don't you attach the simplest example of a file and how you would like it to be structured once it's in Leo.  Also, in what way is the bridge involved here?  Please show an example.

**Comment by tbpassin** [comment]
BTW, if you meant c# files, Leo's name for that language is "csharp", not "css".

**Comment by rsm123** [comment]
Following code creates 2 child nodes using bridge. I just want to color the text written to the body pane from the Python script, and not at a later point within the editor. That way I can choose what text and color to be applied while creating the .leo file:


from leo.core import leoBridge
bridge = leoBridge.controller(gui='nullGui',
            silent=True,
            verbose=False,
            loadPlugins=False, readSettings=True)
path = "/Users/rsm/Documents/testfolder/coloredtext.leo"
if bridge.isOpen():
 g = bridge.globals()
 assert g.app.inBridge,g.app
 g.app.db['LEO_EDITOR'] = "gvim"
 c = bridge.openLeoFile(path)

 for n in range(1, 2):
    parent = c.lastTopLevel()
    parent.h = 'Parent'
    child1 = parent.insertAsNthChild(0)
    child2 = parent.insertAsNthChild(1)
    child1.h = "child1"
    child2.h = "child2"
    child1.b = "Text to be colored BLUE"
    child2.b = "Text to be colored RED"
 c.redraw()
 c.save()

**Comment by tbpassin** [comment]
As far as I know, the standard Leo body editor doesn't have an API to color anything.  Only the syntax colorizer does any colorizing.

If you want to get into Qt programming, you can probably make the editor do all sorts of things.  You could look into the code in Leo's core that highlights the current line, and write a script that does something like that, perhaps.  But there would be no standard way to persist the colorizing of any text.  You could probably manage it with User Attributes, but then you would have to write code to apply the text colors using the User Attribute data you saved.  This all could probably be done but it would not be easy. You probably would want to do it using a plugin

You could also look into the code that writes to the log file, because that can write in different colors (though not to the body).

The question really is, why do you want to do this?  Few if any text editors will do this.  It's more of a word processor kind of thing.  I suppose you really are thinking of something more general than just coloring a block of text blue or red. What is it, and why do you want to do it? 

Perhaps you want what is sometimes called a "rich text" editor.  Qt has such a capability but you would have to write all the supporting code and figure out how to use that editor instead of Leo's standard editor on specific nodes or trees. The data would be saved in a specialized HTML format (that's how Qt does it).  Someone wrote a rich text plugin for Leo.  I'm not sure how it worked and it no longer is fully functional but you could undertake to get it working again.

Again, it would be helpful if you would explain the bigger picture of what you want to accomplish.  There might be another way.

**Comment by tbpassin** [comment]
Can this issue be closed?  The OP hasn't followed up with enough information to think about it.

**Comment by edreamleo** [comment]
@tbpassin @rsm123 I am closing this issue.
