### ISSUE TITLE
VR3 Traceback - object has no attribute 'QWebEngineView'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3983]
Leo 6.8.0-b1, devel branch, build d8ffe6a719
2024-06-24 04:46:46 -0500
Python 3.12.4, PyQt version 6.7.2
Windows 10 AMD64 (build 10.0.19045) SP0 

gives traceback at startup:
_Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 544, in loadOnePluginHelper
__import__(moduleName)
  File "N:\git\leo-editor\leo\plugins\viewrendered3.py", line 981, in <module>
qwv = QtWebEngineWidgets.QWebEngineView
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'QWebEngineView'
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 544, in loadOnePluginHelper
__import__(moduleName)
  File "N:\git\leo-editor\leo\plugins\freewin.py", line 269, in <module>
QWebEngineView = QtWebEngineWidgets.QWebEngineView
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'QWebEngineView'_

**Comment by tbpassin** [comment]
I'm mystified here.  Using the same rev, on Windows, I don't get that error.  The only way, it would seem, is if this import in leoQt were to fail:

`from PyQt6 import QtWebEngineWidgets`

If that had happened then I think you would have seen a message about it when Leo starts up.

The requirements.txt file clearly imports the WebEngine, in this line near the bottom:

`PyQt6-WebEngine`

Could you check to make sure it's been installed?

`py -m pip list |find /i "webengine"`

You should see (the version may not be exactly 6.6.0):

```
PyQt6-WebEngine               6.6.0
PyQt6-WebEngine-Qt6
```
The only anomaly I know of with Freewin is that every few characters you type, if you are editing in its window, the cursor gets moved back up to the top.  This is something new;  it must be a change with more recent versions of Qt6, since it didn't used to happen; I just noticed it very recently.  I will try to track this down.

**Comment by LewisNeal** [comment]
The import of QtWebEngineWidgets failed:
from PyQt6 import QtWebEngineWidgets

_exception executing script
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 1213, in executeScript
c.executeScriptHelper(args, define_g, define_name, namespace, script)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 1258, in executeScriptHelper
exec(compile(script, scriptFile, 'exec'), d)
  File "C:/Users/lewisneal/.leo/scriptFile.py", line 9, in <module>
from PyQt6 import QtWebEngineWidgets
ImportError: DLL load failed while importing QtWebEngineWidgets: The specified module could not be found._

Checked installation:
>py -m pip list |find /i "webengine"
PyQt6-WebEngine             6.7.0
PyQt6-WebEngine-Qt6         6.7.2
PyQt6-WebEngineSubwheel-Qt6 6.7.2

I will uninstall and reinstall the WebEngine packages.

**Comment by LewisNeal** [comment]
Uninstall and reinstall of the WebEngine packages fixed the problem.
I tested Freewin typing into the window and did not see the cursor jump you described.

**Comment by tbpassin** [comment]
Good, maybe I should try updating the WebEngine.

**Comment by tbpassin** [comment]
I just updated PyQt6 and PyQt6-WebEngine and got the same import error you did.
