### ISSUE TITLE
 Using command line option --version  starts a full Leo session

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#4200]
Running Leo with command line command line option _--version_  should print version number and exit. However it starts a full Leo session.

Leo 6.8.3-devel, devel branch, build 804a840d59
Python 3.12.7, PyQt version 6.7.3
Windows 10

**Comment by tbpassin** [comment]
This isn't happening for me. Control returns to the command line after the version output:

```
C:\Tom\git\leo-editor>py -m leo.core.runLeo --version
Leo 6.8.3-devel, devel branch, build 804a840d59
2024-11-19 03:40:11 -0600
Python 3.12.3
Windows 10 AMD64 (build 10.0.19045) SP0
```

How are you launching Leo?

**Comment by edreamleo** [comment]
This issue must be erroneous. The following work as expected:
```console
python leo\core\runLeo.py --version
python -m leo.core.runLeo --version
```

**Comment by LewisNeal** [comment]
I start Leo with just _launchleo.py_ on Windows and I haven't broken that habit.
Sometimes I refer to Running Leo at [https://leo-editor.github.io/leo-editor/running.html#leo-s-command-line-options](url)
which doesn't mention the need to use  _python launchLeo.py [options]_

Time to develop a new habit and use  _python launchLeo.py_

**Comment by edreamleo** [comment]
@LewisNeal Thanks for your investigation. I'm glad all is well now.

**Comment by tbpassin** [comment]
Windows paths and file associations can get out of whack after different versions get installed. The "py" launcher will run the latest version of python by default, whereas "python" might not. On my computer, for instance:

```
C:\Users\tom>python -V
Python 3.9.9

C:\Users\tom>py -V
Python 3.12.3

C:\Users\tom>py -3.11 -V
Python 3.11.5
```

On my computer the Windows file type association for ".py" files is"

```
C:\Users\tom>assoc .py
.py=Python.File

C:\Users\tom>ftype Python.file
Python.file="C:\Windows\py.exe" "%L" %*
```

And finally, again on my computer:

```
C:\Users\tom>where launchleo.py
INFO: Could not find files for the given pattern(s).
```

I could fix the paths and associations by hand, and at the next version of Python I could let the installer set those paths, etc. There used to be a reason I didn't let the installer do so.  I'm not sure that reason is valid any more but I'm so used to typing `py -m leo.core.runLeo`  (and `py -m pip`) that I just keep running Leo that way.  I always know what version will run and pip-install.
