### ISSUE TITLE
Leo file still shown as "dirty" even when all changes have been undone

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#460]
If I save a Leo file and start making changes, the file is automatically shown as "dirty" (changes pending to be saved) with an `*` appearing before the file name at the Tab bar. That's ok. 

But if I then undo **all the changes** (with `Ctrl-z`) going back to when I made the last save, the `*` should disapear showing that the file is no "dirty" any more, so there's no need to save it any more.

This is the behaviour at the most common editors like Notepad++ and others.

**Comment by edreamleo** [comment]
Leo sometimes works as intended, and sometimes not.  For example, if the only change is inserting a node, undoing that changes clears the changed bit.  But undoing typing doesn't.

**Comment by vitalije** [comment]
I have written a plugin for Leo named vnodes-history, but it requires sqlite-leo to work. Basically it makes snapshot of current outline data at opening outline. In any given moment it can report changes made since last snapshot. After saving outline, it writes all changes to db table. There is also function to rewind changes for any given node (to see what it looked like at given time.) For now, I have enabled this plugin so it records every change I make to LeoPyVitalije.db When I accumulate enough history data, I will probably try to make some use of it (still don't know what). But this two functions can reliably answer the question: is this outline same as it were when last time saved or opened. Just call `bool(get_changes())`

Vitalije

**Comment by vitalije** [comment]
My vnhistory table contains 11931 records since about 46 hours ago. Exported as sql text file this table is around 1.3M, when gzip-ed it is about 96k, and current size of LeoPyVitalije.db is 9.7M.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 7:15 AM, Виталије Милошевић <
notifications@github.com> wrote:

> I have written a plugin for Leo named vnodes-history, but it requires
> sqlite-leo to work.
>
​I'll look forward to testing this when you are ready.

Edward

**Comment by edreamleo** [comment]
On Sat, Jul 15, 2017 at 5:06 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

> I have written a plugin for Leo named vnodes-history, but it requires
>> sqlite-leo to work.
>>
> ​I'll look forward to testing this when you are ready.
>

​Oh, I see you were referring to the sqlite-leo branch, rather than a
plugin.​

​

I don't any plugin named vnode*.py in the sqlite-leo or v-lines branches.

Edward

**Comment by vitalije** [comment]
I haven't added it to git yet. It is still alpha. But I shall add it soon.

**Comment by edreamleo** [comment]
Rev e4d720b in devel apparently fixes this issue.
