### ISSUE TITLE
Allow paste-retaining-clones across files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#478]
I'm not sure why this restriction exists.  It doesn't seem necessary.

**Comment by vitalije** [comment]
Perhaps it can be problem if two nodes in different commanders have the same gnx, but differ in content. It is unlikely to ever happen first time nodes are pasted, but later if user edit those nodes separately they may get out of sync and if then user tries to paste them back problems can arise. Though it can be checked before pasting if there are any known gnx and warn user or let user choose what to do.

**Comment by edreamleo** [comment]
> maybe that was the reason for such a restriction in the first place.

Iirc, the original idea was that only one outline should ever be "responsible" for any particular piece of code.  Similarly, it would typically be bad management practice to have two separate programming groups be responsible for the same piece of code. I'm not entirely sure this is a convincing argument...

**Comment by vitalije** [comment]
I think I have remember why it can be sometimes useful. If we have two Leo documents as for example: LeoPy.leo and LeoPyVitalije.leo. One is considered to be reference file and is part of source version control,  and the other one is considered as private. In Leo source code we use at-files for external files, but I have used at-clean files and I had a problem with unwanted changes in repository because of changed gnx. Before committing I would execute script in leoBridge that would copy all at-clean files from private to public outline. It would be nice if gnx remain as they are so that no false changes are detected by source version control tool. I believe it would be fair use of this feature.

**Comment by edreamleo** [comment]
@vitalije: " It would be nice if gnx remain as they are so that no false changes are detected by source version control tool. I believe it would be fair use of this feature."

I think I agree :-)

**Comment by vitalije** [comment]
Done at a51fc3f

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 2:58 AM, Виталије Милошевић <notifications@github.com
> wrote:

> Done at a51fc3f
> <https://github.com/leo-editor/leo-editor/commit/a51fc3f76ff08759d91b24b94178d8763ac33e5f>
>

​And I have just added preliminary documentation in leoProjects.txt. This
is useful so I don't have to go digging through git logs or lists of
completed issues.

Edward
