### ISSUE TITLE
leoConfig.ParserBaseClass methods should be revised

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#517]
I have noticed some methods that are not mentioned in documentation nor used in leoSettings.leo.
We should either remove them or document them properly. 

Here is a suspect list:
1. `doAbbrev` and `parseAbbrevLine`
2. I am not 100% sure about this, but shouldn't `doOutlineData` return 'skip'?
3. `doPage`  empty method, can't figure why?

I am working on standalone script for analyzing settings outlines and I want to be clear on what kind of settings are to be supported and which can be skipped in new code.

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 1:47 AM, Виталије Милошевић <notifications@github.com
> wrote:

> I have noticed some methods that are not mentioned in documentation nor
> used in leoSettings.leo.
>
​Thanks for this.​


> We should either remove them or document them properly.
>
​I think removing them is reasonable.​


> Here is a suspect list:
>
>    1. doAbbrev and parseAbbrevLine
>
> ​These can be removed. I'm not sure whether these were ever used.  Now,
however, Leo uses @data nodes for abbreviations. Using @data is a huge
improvement, because @data nodes may contain children, grandchildren, etc.

>
>    1. I am not 100% sure about this, but shouldn't
>    ​​
>    doOutlineData return 'skip'?
>
> ​An interesting edge case.  ​

​Yes, I think you are right.​

>
>    1. doPage empty method, can't figure why?
>
> ​This can be removed.​ @page may be an ancient remnant.

At one time I thought a gui representation of settings would be good for
Leo, and I have a half memory that @page was used to organize the gui
"pages".​


​I actually did all the work of creating a settings pane, and then
abandoned it after it became clear that Leo outlines were a much more
flexible way or representing settings.

There may be a lesson here.  In the present scheme, it is dead easy to make
a new setting.  Just create an @bool, @int, etc. node, and reference it in
the code using c.config.getBool, getInt, etc.​  Creating a new gui setting
was much harder.

>
>
> I am working on standalone script for analyzing settings outlines and I
> want to be clear on what kind of settings are to be supported and which can
> be skipped in new code.
>
​I think all your proposed changes are reasonable. I doubt that removing
​@page or @abbrev will cause any problems. Users will let us know if they
do ;-) Making sure that @outline-data does not reparse the tree for more
settings seems like it could avoid rare problems.

Edward

**Comment by vitalije** [comment]
Thanks for the clarification.

**Comment by edreamleo** [comment]
@vitalije Feel free to make the proposed changes in the trunk. We may as well start testing immediately.

Make sure you announce them in leo-editor so people will be on the lookout for trouble.

**Comment by vitalije** [comment]
Ok.

**Comment by vitalije** [comment]
Done at 3f88d31
