### ISSUE TITLE
Allow nested @clean trees

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#525]
The following is an edited version of the [original discussion](https://groups.google.com/forum/#!topic/leo-editor/CjF_FYxBMyg) on leo-editor.  This would represent a major change to Leo's read/write code.  EKR does not yet understand all the implications.

**Status**: work is complete in the `at-others` branch.  This branch will be merged into devel after testing.

At present, an `@clean` node as a child of a node with `@others` will simply be treated like all other sub-nodes&mdash;its content will get placed after the `@others` directive. Instead, the OP would like `@clean` nodes to ignore descendant `@clean` nodes. For example:

```tex
% at_file main.tex:

\section{Section level}
blah blah
blah
\input{sub}
blah
blah blah
...

% at_file sub.tex:
\subsection{Subsection level}
more blah
more blah
...
```
Currently the main.tex node cannot be a parent of the sub.tex node, although logically it is. The OP would like the tree to represent the document structure.

**Comment by dalcolmo** [comment]
The above solution has the advantage of being rather generic.
In the special case of editing latex files it may be useful to implement something similar to @auto-rst,
which interprets section titles as node headings.
In this case, having a main @auto-latex node and the nodes underneath reflecting the document structure would be great. Then again, any \input statements should be associated with nested @auto-latex nodes. These would then not represent the document structure as in "headings" but would still show up in all the right places.
Such nested @file nodes might not play well with the active_path plug-in, though. Perhaps it is less disruptive to use links to the files after all. In that case the @auto-latex node would only need to reflect the document heading structure, and perhaps the \input statements can be automatically linked to the appropriate files. - still thinking.

**Comment by dalcolmo** [comment]
Automatic creation of descendant @file nodes (or links) in latex files may not always be a good idea. I often use \input to pull in **derived** files. In that case the child @file node or link should point to the source, not the derived .tex file, but it can be very difficult to figure out the source file automatically without using a naming convention or analysing the Makefile(s).
I still think having the possibility to have nested @clean nodes might be a good thing, but the same would not work in @auto nodes, since there is no universal way to know which file to load.

**Comment by dalcolmo** [comment]
Hi Edward,
I just keep nagging about this, because this is still the main issue bothering me when working with leo and latex while sharing tex code with others (When I am writing alone I just use a single @clean tree for the whole document). So, I would greatly appreciate if this (@clean under @others) would be implemented.

**Comment by edreamleo** [comment]
@dalcolmo Thanks for the nudge.  I'll see what I can do in the next day or so.

**Comment by edreamleo** [comment]
Rev 8cf842646 in the at-clean branch in the at-clean branch supports nested `@clean` nodes.

It's may be possible to make nested `@file` nodes work, but they do not work at present.

**Comment by edreamleo** [comment]
The code in the at-others branch has been fully merged into devel.

**Comment by edreamleo** [comment]
> I can't escape an uneasy feeling that this will somehow lead to
unexpected results

Please test the code in devel.  As I remember, only one real line of code
changed, so there will be no difficulty in backing out of the existing code.

> or actually be dangerous.

Any real danger would likely arise from deeply nested clones, not the
feature itself.

Edward

**Comment by largo84** [comment]
Yes, testing in devel (that's the only version I use anyway). I think what makes me uncomfortable is the creation of external files with duplicate data (one of my basic rules is to never duplicate data). The master file contains the data contents of the nested @clean file and of course, the @clean file contains the same data.

I envision a scenario where they could get of sync externally (not within Leo) if they were each edited separately and independently, perhaps by multiple people working on the files outside of Leo. That's not presently an issue for me as I typically don't have collaborators. However, in the case suggested by the OP, that might happen (or might not).

**Comment by edreamleo** [comment]
On Wed, Jan 16, 2019 at 1:32 PM Rob Keeney <notifications@github.com> wrote:

> makes me uncomfortable is the creation of external files with duplicate
> data (one of my basic rules is to never duplicate data). The master file
> contains the data contents of the nested @clean <https://github.com/clean>
> file and of course, the @clean <https://github.com/clean> file contains
> the same data.
>

No, the master file does not contain the contents of the nested @clean
files.  See this posting
<https://groups.google.com/d/msg/leo-editor/WGQIzBzQ058/QTJRUvl9CwAJ> in
leo-editor.  Please verify the workings of nested @others for yourself.

Edward

**Comment by dalcolmo** [comment]
I had so far only time for some limited testing, e.g. no complicated hierarchies and only with @clean nodes.
I tried first to put an @clean node under another @clean node, and forgot to add any @others (since the parent @clean node did not have any need for @others beforehand. The result was an @ignore and a write error -- not what I had expected, though logical when considering how you named the branch.

Second, when changing files outside Leo one gets normally a notification by Leo, but not for the @clean nodes underneath another @clean node.

I am using this together with the active_path plugin, where my default import mode is @clean. I thought I saw a strange behaviour of some file being created in the wrong directory, but haven't had the time yet to figure out the circumstances - it may be an active_path "feature", when an intermediate dir has the right headline, but no corresponding @path statement in the body.

Otherwise, I am using this version happily in a production environment and haven't seen a problem yet. I will try to do some tests with some more complicated trees soon.

**Comment by edreamleo** [comment]
On Wed, Jan 30, 2019 at 6:52 AM dalcolmo <notifications@github.com> wrote:

> I had so far only time for some limited testing, e.g. no complicated
> hierarchies and only with @clean <https://github.com/clean> nodes.
> I tried first to put an @clean <https://github.com/clean> node under
> another @clean <https://github.com/clean> node, and forgot to add any
> @Others <https://github.com/Others> (since the parent @clean
> <https://github.com/clean> node did not have any need for @Others
> <https://github.com/Others> beforehand. The result was an @ignore
> <https://github.com/ignore> and a write error -- not what I had expected,
> though logical when considering how you named the branch.
>

Please redo your tests on "devel". All the recent branches have been merged
into devel. In particular, the merged code in the "detect" branch no longer
inserts @ignore when detecting write errors.

> Second, when changing files outside Leo one gets normally a notification
> by Leo, but not for the @clean <https://github.com/clean> nodes
> underneath another @clean <https://github.com/clean> node.
>
This is likely a bug.  I have just created #1072
<https://github.com/leo-editor/leo-editor/issues/1072> for it.

Edward

**Comment by edreamleo** [comment]
**Josef**:  I am unable to save if a child @clean node has (ordinary) children nodes:

Create a new file with an @clean foo.txt node, write @others into the body, then create a child @clean goo.txt node and write something into it.
So far everything works as expected.

Now add a normal child node to the @clean goo.txt node and try to save. It won't let you.

**Comment by edreamleo** [comment]
I am going to defer further work indefinitely.  I have updated the docs for `@clean` to indicate the present situation.

**Comment by edreamleo** [comment]
I am not going to do this. Live is too short.
