### ISSUE TITLE
createOutlineFromCacheList needs unit tests and proof of correctnes

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#542]
Recent discussion (#514) and bug fix in this part of Leo suggest that this method was broken for a while and yet it was not discovered until now. It affected recreating outlines of external files from cache, and only in some special cases where clone was present in xml and in external file the same clone has new child.

Fix in 2c497cd6 did solve this particular combination. However, I am not convinced that this method will do right thing if clone in xml has more children.

My plan is as follows:

1. make a test that will fail with code before 2c497cd6.
2. make a test that exhibits the other combination (xml clone has more children than the cache one)
3. try to improve createOutlineFromCacheList in terms of clarity

Right now, else statement at the end of createOutlineFromCacheList, doesn't seem too intuitive. Without careful reading of other methods I was certain that this `else` statement was an error. The other method `checkForChangedNodes` doesn't do just check but also it completes otherwise uncompleted clones, which is not obvious from its name.

**Comment by vitalije** [comment]
Here is workbook for testing leoCache module [cache-testing.leo](https://raw.githubusercontent.com/leo-editor/snippets/88c9f5876afc77034a5a6d98db0b0daf24b0dce3/experiments/cache-testing.leo)

It contains 4 test cases:
1. clone in cache has children with the same gnxes as clone in outline
2. clone in cache has at least one child that clone in outline hasn't
3. clone in outline has at least one child than clone in cache hasn't
4. clone in cache has at least one child that clone in outline hasn't and clone in outline has at least one child that clone in cache hasn't

At the moment, with the latest version of leoCache.py cases 3 and 4 fail. With version before 2c497cd case 2 is also failing.

**Comment by vitalije** [comment]
Fixed at b96439c.  All unitTests pass and also all four test cases from [cache-testing.leo](https://raw.githubusercontent.com/leo-editor/snippets/88c9f5876afc77034a5a6d98db0b0daf24b0dce3/experiments/cache-testing.leo) pass.

I feel that there is still space for improvements in this method and its helpers, but for now let them be as they are. They are connected with some methods in leoAtFile module, so any change here must take into consideration related methods there.

**Comment by edreamleo** [comment]
@vitalije I greatly appreciate your thoroughness in handling this issue.  Like you, I am not satisfied with cacher.createOutlineFromCacheList and its helpers. I have a bad feeling about this code in checkForChangedNodes:

```python
for_removal = [(i, v)
    for i, v in enumerate(child_v.children) 
        if v.gnx not in gnxes_in_cache]
for i, v in reversed(for_removal):
    v._cutLink(i, child_v)
```
It *might* work in all cases, but I wouldn't be my life on if.  This is not a criticism of your work!  Rather, I am unhappy with the cache list itself.

My first thought was that the cache list should contain, for each vnode an *explicit* representation of the vnode's children and parents arrays. This would complicated the (easy) write code in order to simplify the (always harder) read code.

Alas, this approach is not feasible. Indeed, the cacher code must read the external file *in the context of the .leo file*. The property of being a clone not a local (intrinsic) property of the external file. So the v.parents array *will* depend on the .leo file. In turn, this means that calls to low-level methods such as v._linkAsNthChild and v._cutLink are unavoidable.

There is another way to see that a more explicit cache list is not possible. There is no way to cache the children array of the hidden root vnode.  Actually, my proposed new caching scheme just doesn't make sense.  Regardless of the format of the cache list, there is no alternative to linking the external file into the outline.

So we are stuck with the general approach to caching that we have.  If problems arise later, we'll just have to fix them. In other words, I agree with your decision to close this item for now.

**Comment by edreamleo** [comment]
On Mon, Aug 14, 2017 at 2:22 AM, Виталије Милошевић <
notifications@github.com> wrote:

> Closed #542 <https://github.com/leo-editor/leo-editor/issues/542>.
>
​I don't see any new changes to Leo's unit tests. I was expecting to see
some new tests for this item.

Edward

**Comment by vitalije** [comment]
Tests are in [cache-testing.leo](https://raw.githubusercontent.com/leo-editor/snippets/88c9f5876afc77034a5a6d98db0b0daf24b0dce3/experiments/cache-testing.leo). They need to be transformed to be proper unitTests, but I haven't done it yet.

In sqlite-leo (and now it is also part of master), all nodes are kept in a table. Parents and children are just strings of gnxes joined with separator. It is possible to recreate tree (or subtree) from this table. Perhaps cache list can be represented as tuple of rows, where each row is tuple defining just one node. That way it is easier to look for something (like changes) in it and check even without creating any node.

Also I think that checking for changed clones can be done separately from creating nodes. One possible way I used in writing tests for this issue is to create cache tuple (like cache list) of clone and see if it differs from the one stored in cache. 

But when I saw that there is also similar code in atFile read code, I gave up of making any changes here.

Perhaps we can try to combine code for reading external files that I have earlier written in [line-numbering.leo](https://raw.githubusercontent.com/leo-editor/snippets/88c9f5876afc77034a5a6d98db0b0daf24b0dce3/experiments/line-numbering.leo) with new cache read/write redesigned to use table of nodes like sqlite-leo does. Both of this functions are standalone and deal with ordinary python dictionaries. After getting those dictionaries, a separate step can be performed for checking if there will be changed clones and later create all nodes that need to be created or applying changes to existing clones. 

Recreating outline from sqlite table does not involve any low level method on vnodes. It simply populate gnxDict with all nodes created with empty parents/children lists and then add children to parents and parents to children from those lists of gnxes. There is no need for fastAddLastChild and _linkAsNthChild or other low level methods.

**Comment by vitalije** [comment]
> Alas, this approach is not feasible. Indeed, the cacher code must read the external file in the context of the .leo file. The property of being a clone not a local (intrinsic) property of the external file. So the v.parents array will depend on the .leo file. In turn, this means that calls to low-level vnode methods such as v._linkAsNthChild and v._cutLink are unavoidable.

At present all nodes in external files are unique, there are no clones among them (at least inside one external file), so their parents attribute will contain only one gnx. However, when accessing clone node by its gnx from gnxDict we will get node which already has at least one parent in its parents list. Recreating such node from external file or from cache will require adding only one more parent. For all other non-cloned nodes we will get from gnxDict a node with empty parents and adding one will just connect it to the tree.

**Comment by vitalije** [comment]
Perhaps this pseudo code will explain better:
```python
for gnx, h, b, children, parent in cache:
       v = gnxDict.get(gnx,  leoNodes.VNode(context=c, gnx=gnx))
       v.h = h
       v.b = b
for gnx, h, b, children, parent in cache:
     v = gnxDict[gnx]
     v.parents.append(gnxDict[parent])
     v.children = [gnxDict[x] for x in children]
```
Of course making list of changed clones is done before this step.

**Comment by edreamleo** [comment]
On Mon, Aug 14, 2017 at 6:03 AM, Виталије Милошевић <
notifications@github.com> wrote:

At present all nodes in external files are unique, there are no clones
> among them (at least inside one external file), so their parents attribute
> will contain only one gnx.
>
​I don't think this statement is valid, for two reasons.  First, external
files may indeed contain clones within the file.  Second, and more
importantly, because of *other* clones, a node (cloned or not) may have
multiple parents.  This what makes it possible to use positions to record
the state of the traversal. I'm not entirely sure about these statements,
but I would be surprised if they were false.

I'd like to switch gears, and start using .db files :-)  How do I convert a
.leo file to a .db, and vice versa?

Edward

**Comment by vitalije** [comment]
@edreamleo just open .leo and  save-to .leo.db. You'll have to enter extension explicitly.
