### ISSUE TITLE
#561 Sub-Project: Allow live objects in Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#569]
This would allow better code completion, etc.

**Comment by tbnorth** [comment]
On Mon, 30 Oct 2017 10:48:59 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> This would allow better code completion, etc.

This kind of works already.

Ville's arcane ;-) valuespace plugin executes its stuff in the
namespace c.vs.  Because it was already doing that I added the much
simpler vs-eval command family in the same plugin executing in the same
namespace.  I think vs-eval and friends would be more visible
elsewhere, although maybe it's simplest to just re-arrange the
valuespace docs.

Anyway, I did something to make Leo look for objects in c.vs when
attempting completion.

import datetime
a = datetime.datetime.now()
a.<Ctrl-Space>
<no completions>

now put the cursor at the start of the import line and execute vs-eval
three times.  Note that the value of a is shown in the log.  First time
is just to set up the selection.

Now a.<Ctrl-Space> should show a's members.

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Oct 30, 2017 at 2:11 PM, Terry Brown <notifications@github.com>
wrote:

Ville's arcane ;-) valuespace plugin executes its stuff in the
> namespace c.vs.


Thanks for the reminder.  This lowers the priority of this item, which is
fine with me.

**Comment by edreamleo** [comment]
I am going to close this issue.  We now have prototype code for interacting with the jupyter kernel, and that should suffice for now.
