### ISSUE TITLE
Tip: pylint command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#622]
Leo's pylint command runs [pylint](https://www.pylint.org/) on all `@<file>` nodes in the selected trees.

Pylint runs in the background, so you can continue to use Leo while pylint runs.

Tags: Command, Testing.

**Comment by tscv11** [comment]
I noticed today that once I had provided pylint with a configuration file and executed 'pylint Leo4SQLite'
from the minibuffer pylint ran successfully, but every line was output twice. Then I remembered that the 'redirect to log' plugin was enabled and so disabled it - problem resolved. I thought it was interesting
because I use a large number of plugins but none of them have given me that problem before.

tscv11

**Comment by edreamleo** [comment]
Closed: transferred to leoTips.leo.
