### ISSUE TITLE
Leo fails to start with: leo --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#637]
Running leo from my pip installed leo at ...\Python\Python36\lib\site-packages\leo
Rather than the usual
>launchleo.py --gui=console
I tried
>leoc --gui=console
This successfully starts Leo with Console gui.

However I tried
>leo --gui=console
This results in a spinning wheel for 5 seconds, then the wheel disappears. Leo console GUI does not start.

I consider this a minor issue and have only reported so I have a record for the 'Starting Leo with the console gui' documentation at http://leoeditor.com/console-gui.html

**Comment by edreamleo** [comment]
On Thu, Dec 14, 2017 at 6:44 AM, LewisNeal <notifications@github.com> wrote:

> Running leo from my pip installed leo at ...\Python\Python36\lib\site-
> packages\leo
> Rather than the usual
>
> launchleo.py --gui=console
> I tried
> leoc --gui=console
> This successfully starts Leo with Console gui.
>
>
​I'm not sure what this means, but you definitely must run Leo from the
console when using --gui=console.  It works for me, as I have just verified.

I use a script/.bat file for testing.  Here is its contents on Windows:

python3 c:\leo.repo\leo-editor\launchLeo.py --gui=console --no-cache
leo\test\unitTest.leo %*

Is there any reason for me not to close this issue?

Edward

**Comment by LewisNeal** [comment]
I'm referring to the use of _leo_ and _leoc_ scripts, the executable wrappers around launchLeo.py created by Matt Wilkie. 
I am running Leo from the console. I'm just pointing out that using:
_leo --gui=console_
doesn't work. You get a spinning wheel for 5 seconds, then the wheel disappears.

And in contrast using:
_leoc --gui=console_
does work, and starts Leo with it's console gui.

**Comment by maphew** [comment]
We could add a 3rd wrapper for console gui, `leocc` for sake of argument. It would just be an alias for `python3 path\to\launchLeo.py --gui=console`, just like:

* `leo` script is functionally identical to `pythonW.exe path\to\leo-editor\launchLeo.py`
* `leoc` script is functionally identical to `python.exe path\to\leo-editor\launchLeo.py`

About the names: It's always felt a bit funny to me that `leoc` isn't gui=console, but I started using the name leoc before console gui existed. It's purpose is to echo the Leo log window reports to the command shell instead of swallowing them (to find errors like the one opening this issue). I haven't thought of a better name. 

For the putative 3rd one: `leo-shell` maybe?

**Comment by maphew** [comment]
`leo-console` or `leo-con` to be consistent with command line parameter

**Comment by LewisNeal** [comment]
leo-console
+1

**Comment by edreamleo** [comment]
On Thu, Dec 14, 2017 at 3:39 PM, LewisNeal <notifications@github.com> wrote:

> I'm referring to the use of *leo* and *leoc* scripts, the executable
> wrappers around launchLeo.py created by Matt Wilkie.
>
​Thanks for the clarification.  I'll delegate this to you and Matt.

Edward

**Comment by maphew** [comment]
Pull request #650 changes the scripts like so:

* `leo` - start Leo in normal graphical mode (qt)
* `leo-c`, `leo-console` - start Leo in console (curses) mode
* `leo-m`, `leo-messages` - start Leo in normal (qt) mode, and echo log messages to the starting shell

**leo-m** is new name for an old thing. **leo-c** is a new thing, re-using an old name. There might be some confusion over this, but I don't think it will be serious or long lasting because `leo-c` hasn't been talked about or promoted very much. In short, I think it's worth the pain, if any, in order have names that more closely match the results.

**Comment by maphew** [comment]
Closing this as the core issue of "how to start leo in console mode" has been solved with introduction of `leo-console` launch script.

There still remains a background issue that `--gui=...` parameter passed to any of the Leo wrapper scripts in `PYTHONHOME\Scripts` has no effect. I tried to figure out why that parameter disappears while others work but failed. I don't think it's a fruitful line to follow up right now so am leaving it to sleep.
