### ISSUE TITLE
synchronize ~/.leo/leo.session with tab order

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#704]
the file `~/.leo/leo.session` defines the UNLs for tabs open in a session. The tabs can be dragged to reorder, but the tab order reverts next session.

Minor enhancement: reordering tabs triggers reordering the UNLs in leo.session

**Comment by tscv11** [comment]
I thought this was what I needed for the task: unl: /leo-editor/leo/core/LeoPyRef.leo#Code-->Core classes-->@file leoSessions.py, I don't, however, see the code that writes the session file, only the code that loads it. Where could it be? Hints welcome.

**Comment by edreamleo** [comment]
On Fri, Mar 23, 2018 at 3:55 PM, tscv11 <notifications@github.com> wrote:

> I thought this was what I needed for the task: unl:
> /leo-editor/leo/core/LeoPyRef.leo#Code-->Core classes-->@file
> <http:///file> leoSessions.py, I don't, however, see the code that writes
> the session file, only the code that loads it.
>
​Looking at the session commands, the primary suspect is
SessionManager.save_snapshot. But we don't want to guess.

The usual convention is that instances of any class have the class name,
with lowercase first letter. A cff (ignoring case) of sessionManager,
yields 12 nodes, including closeEvent (leoTabbedTopLevel). This method
starts with:

    if g.app.save_session and g.app.sessionManager:
        g.app.sessionManager.save_snapshot()

I had forgotten that there is only one instance, g.app.sessionManager,
instead of a per-outline instance, c.sessionManager, but of course that
makes sense.  These are the kind of reminders one gets when becoming
reacquainted with the code.

HTH

Edward

**Comment by tscv11** [comment]
Thank you. A quick test reveals that CloseEvent (and I believe other related code) is called only when the command line switches for loading and saving sessions are in effect. I conclude that I have not yet found the code I'll need to work on.

**Comment by edreamleo** [comment]
On Sat, Mar 24, 2018 at 9:49 AM, tscv11 <notifications@github.com> wrote:

> Thank you. A quick test reveals that CloseEvent (and I believe other
> related code) is called only when the command line switches for loading and
> saving sessions are in effect. I conclude that I have not yet found the
> code I'll need to work on.
>
​Thanks for this report.  You are doing all the right things.

Edward

**Comment by tscv11** [comment]
I've searched for session, leo.session, sessionManager, tab, tabs, tab_order, snapshot, save_session, and more. Having run out of ideas I browsed more through Leopy.py but found nothing else. Since Leo's internals are being taught at LeoU, I'll ask this: where else should I look for this "tab order code?"

**Comment by edreamleo** [comment]
On Sun, Mar 25, 2018 at 2:51 PM, tscv11 <notifications@github.com> wrote:

> I've searched for session, leo.session, sessionManager, tab, tabs,
> tab_order, snapshot, save_session, and more. Having run out of ideas I
> browsed more through Leopy.py but found nothing else. Since Leo's internals
> are being taught at LeoU, I'll ask this: where else should I look for this
> "tab order code?"
>
​Not sure.  I'll look myself.

Edward

**Comment by technatica** [comment]
Tab order on --save-session is determined by the order the tabs were opened in. No amount of moving, making dirty and saving files etc. will change that. This behaviour is also persistent between sessions.

I hope this is a clue on where to look.

**Comment by edreamleo** [comment]
On Sun, Mar 25, 2018 at 2:51 PM, tscv11 <notifications@github.com> wrote:

> I've searched for session, leo.session, sessionManager, tab, tabs,
> tab_order, snapshot, save_session, and more.
>
​How about searching for the global vars set by the --session* command-line
arguments.

See ​LM.scanOptions & helpers.

Edward

**Comment by tscv11** [comment]
In LM.doPostPluginsInit & helpers I see lines that look promising (starting at line 14). Unfortunately, I cannot claim to understand them well enough to know for sure. I do note, however, that there is a command used there called 'setTabForCommander', and that seems like a decent search term to try next.

Regarding the information being saved between sessions, in general I had thought it was kept in a file called "leo.session" but a search returns nothing. Perhaps I was mistaken or it has been phased out. The only other thing that comes to mind is storing the tabs using uA's for that outline, but I still don't know where this might be happening in the code.

**Comment by edreamleo** [comment]
On Mon, Mar 26, 2018 at 4:20 PM, tscv11 <notifications@github.com> wrote:

> I had thought it was kept in a file called "leo.session" but a search
> returns nothing. Perhaps I was mistaken or it has been phased out. The only
> other thing that comes to mind is storing the tabs using uA's for that
> outline, but I still don't know where this might be happening in the code.
>
​Session data might also be stored in c.db.

Edward

**Comment by tscv11** [comment]
It seems I'm out of my depth. I might try working on a "good first issue" or "lvl:minor". Thanks for the hints.

**Comment by edreamleo** [comment]
On Tue, Mar 27, 2018 at 4:12 PM, tscv11 <notifications@github.com> wrote:

> It seems I'm out of my depth. I might try working on a "good first issue"
> or "lvl:minor". Thanks for the hints.
>
​I'll look into this further.  I haven't been any help to you so far.

Edward

**Comment by tbnorth** [comment]
On Tue, 27 Mar 2018 17:58:12 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Tue, Mar 27, 2018 at 4:12 PM, tscv11 <notifications@github.com>
> wrote:
> 
> > It seems I'm out of my depth. I might try working on a "good first
> > issue" or "lvl:minor". Thanks for the hints.

"lvl:minor" may not imply straight forward, just not very important.
I'm not sure if that tags used very widely.

> ​I'll look into this further.  I haven't been any help to you so far.
> 
> Edward

I think I spotted that leo/core/LeoPy.leo#Code-->Core classes-->@file
leoSessions.py-->class SessionManager-->get_session
uses g.app.windowList which doesn't reflect tab order, which
instead comes from g.app.gui.frameFactory.masterFrame which is a
LeoTabbedTopLevel instance.  So get_session() just needs to sort its
answer by the order given by g.app.gui.frameFactory.masterFrame or some
derivative of it.

Cheers -Terry

**Comment by edreamleo** [comment]
On Tue, Mar 27, 2018 at 10:26 PM, Terry Brown <notifications@github.com>
wrote:
​\
​

"lvl:minor" may not imply straight forward, just not very important.
>

​Correct.
​


I think I spotted that leo/core/LeoPy.leo#Code-->Core classes-->@file
> leoSessions.py-->class SessionManager-->get_session
> uses g.app.windowList which doesn't reflect tab order,


​Interesting.
​


> instead
> ​[the present tab order] ​
> comes from g.app.gui.frameFactory.masterFrame which is a
> LeoTabbedTopLevel instance. So get_session() just needs to sort its
> answer by the order given by g.app.gui.frameFactory.masterFrame or some
> derivative of it.
>

​Thanks for this.  ​It's likely to be the solution.

@tscv11: Care to have a go?

Edward

**Comment by tscv11** [comment]
If I do this I'll likely need an awful lot of questions answered - I thought it might be better to leave it for someone with more experience. For example, I looked through (what I think is) the frameFactory code but I don't understand how it's saving tab order. I think the size of Leo and its OOP intricacies  are a big challenge for me in general. 

However,  as long as someone wants to answer my questions I'm "game."  So my first question would be: how should I look at the frameFactory code so I can see what it's doing? And is this location right: /leo-editor/leo/core/LeoPyRef.leo#Code-->Gui base classes-->@file leoFrame.py-->class LeoFrame.

**Comment by edreamleo** [comment]
On Wed, Mar 28, 2018 at 3:14 PM, tscv11 <notifications@github.com> wrote:

> If I do this I'll likely need an awful lot of questions answered - I
> thought it might be better to leave it for someone with more experience.
>
​Well, that's how you get experience!  I'm happy to answer any questions
you might have.

Edward

**Comment by tscv11** [comment]
Thank-you! There is a question in my previous post. Hopefully it's not too broad.

**Comment by tscv11** [comment]
In: /leo/core/LeoPyRef.leo#Code-->Qt gui-->@file ../plugins/qt_frame.py-->class TabbedFrameFactory-->createFrame   I had Leo output the file names and index numbers being created. They were in the same order as in g.app.windowList.

**Comment by edreamleo** [comment]
On Thu, Mar 29, 2018 at 12:38 AM, tscv11 <notifications@github.com> wrote:

> In: /leo/core/LeoPyRef.leo#Code-->Qt gui-->@file <https://github.com/file>
> ../plugins/qt_frame.py-->class TabbedFrameFactory-->createFrame I had Leo
> output the file names and index numbers being created. They were in the
> same order as in g.app.windowList.
>
​Right, but users can rearrange tabs later.

Edward

**Comment by tscv11** [comment]
The closest I've been able to find is here: /leo/core/LeoPyRef.leo#Code-->Qt gui-->@file ../plugins/qt_frame.py-->class LeoBaseTabWidget(QtWidgets.QTabWidget)-->setChanged, but it changes when a tab is selected, not when a tab is selected and then dragged to a new position.

**Comment by tbnorth** [comment]
On Fri, 30 Mar 2018 12:30:30 -0700
tscv11 <notifications@github.com> wrote:

> The closest I've been able to find is
> here: /leo/core/LeoPyRef.leo#Code-->Qt
> gui-->@file ../plugins/qt_frame.py-->class
> LeoBaseTabWidget(QtWidgets.QTabWidget)-->setChanged, but it changes
> when a tab is selected, not when a tab is selected and then dragged
> to a new position.

I think the trick is to find the current order when the session list is
written during shutdown.  So I think

leo/core/LeoPy.leo#Code-->Core classes-->@file leoSessions.py-->class SessionManager-->get_session

needs to get at least the order of the tabs from the instance of
the LeoTabbedTopLevel g.app.gui.frameFactory.masterFrame.

How easy that is depends on whether the children of masterFrame have
links back to the outlines to get the full path from.  Otherwise you'd
have to get the full paths from g.app.windowList and then re-order them
by the order in masterFrame, which might mean matching tab names to
paths.  Or perhaps adding the missing link, seeing that seems less
fragile.

Cheers -Terry

**Comment by tscv11** [comment]
How should I get the tab order from the instance of LeoTabbedTopLevel g.app.gui.frameFactory.masterFrame? How can I check whether there are links from the children of masterFrame back to the outlines where full paths can be found? My understanding of OOP is so limited that I don't know how to go about implementing your suggestions. I am looking for a good online course covering the object oriented parts of python, but I could use more hints for this situation as I try to get "up to speed". Thanks.

tscv11

**Comment by tbnorth** [comment]
On Sun, 01 Apr 2018 02:46:11 +0000 (UTC)
tscv11 <notifications@github.com> wrote:

> How should I get the tab order from the instance of LeoTabbedTopLevel
> g.app.gui.frameFactory.masterFrame? How can I check whether there are

Here's what I do - I use what is now the 'eval' command to eval this
expression:

g.app.gui.frameFactory.masterFrame.children()

which gives

[<PyQt5.QtWidgets.QStackedWidget object at 0x7f645f9b2438>, <leo.plugins.qt_frame.QtTabBarWrapper object at 0x7f647782b3a8>]

so

tabs = g.app.gui.frameFactory.masterFrame.children()[1]

tabs.children()

... this gives the buttons for the tab bar.  Then you just flail about
for ten minutes trying to work out how they relate to the tab contents,
and realize you missed a turn right back at the beginning:

g.app.gui.frameFactory.masterFrame is a http://doc.qt.io/qt-5/qtabwidget.html
so ignore the tab bar, we want

tabs = g.app.gui.frameFactory.masterFrame

tabs.count()  - number of tabs
tabs.widget(0)  - first tab, turns out to be
<leo.plugins.qt_frame.DynamicWindow object at 0x7f64742ae0d8>

I'm sure that has a link to the corresponding c, so I look at
leo-editor/leo/core/LeoPy.leo#Code-->Qt gui-->@file ../plugins/qt_frame.py-->class  DynamicWindow (QtWidgets.QMainWindow)--> ctor (DynamicWindow)

and find that it's leo_c

So 

session_order = [
    g.app.gui.frameFactory.masterFrame.widget(i).leo_c.p.get_UNL(
        with_file=True, with_proto=False, with_index=True)
    for i in range(g.app.gui.frameFactory.masterFrame.count())
]

and that's what leo/core/LeoPy.leo#Code-->Core classes-->@file
leoSessions.py-->class SessionManager-->get_session

should be returning, not the order taken from g.app.windowList

*except* that Leo has or had a mode where the outlines aren't tabbed
together, so the code should probably check that
g.app.gui.frameFactory.masterFrame exists and is a QTabWidget and fall
back to g.app.windowList if not.

Cheers -Terry

**Comment by tscv11** [comment]
I have successfully tested these things live using the python console. However, the session_order code produces no result if added to the "get_session" node and I'm not sure how to make the information available there. I'm also looking for the part of Leo that saves tab order when closing, starting here: /leo-editor/leo/core/LeoPyRef.leo#Code-->Core classes-->@file leoApp.py-->class LeoApp-->app.Closing. I don't know how to interpret much of what I see, but try anyway, hoping to find a clue.

**Comment by tscv11** [comment]
I'm still very lost and running out of questions to ask. Maybe a 'good first Issue' would be better, although I'm getting the feeling it might _all_ be beyond me - Leo is vast and complex - leo4sqlite is the biggest thing I've ever done and I struggled with _that_. I just know that I don't seem to be making any progress.

**Comment by tbnorth** [comment]
On Mon, 02 Apr 2018 21:10:23 +0000 (UTC)
tscv11 <notifications@github.com> wrote:

> I'm still very lost and running out of questions to ask. Maybe a
> 'good first Issue' would be better, although I'm getting the feeling
> it might _all_ be beyond me - Leo is vast and complex - leo4sqlite is
> the biggest thing I've ever done and I struggled with _that_. I just
> know that I don't seem to be making any progress.

The complexity of things is hard to describe.  The session ordering
thing has, I think, a small answer, but not exactly a straight forward
one. An accurately labeled "good first Issue" might have a less obscure
answer, even if it involved more code.  I haven't look at what's
labeled "good first Issue".

I think for the session ordering, the session is saved on exit whenever
--session-save is in effect, just not in the right order.  So getting
get_session to return things in the right order is "all" that's needed.

I've pushed that in e3ca666.  Code would have been simpler if it was
x.c both times and not x.c in one case and x.leo_c in the other.

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Apr 2, 2018 at 8:47 PM, Terry Brown <notifications@github.com>
wrote:

I think for the session ordering, the session is saved on exit whenever
> --session-save is in effect, just not in the right order. So getting
> get_session to return things in the right order is "all" that's needed.
>

​Many thanks for this. It's certainly not a good first issue.​


I've pushed that in e3ca666. Code would have been simpler if it was
> x.c both times and not x.c in one case and x.leo_c in the other.
>

​The leo_ prefix is used in subclasses of Qt classes to ensure that there
can be no clash with existing Qt ivars.

Edward
