### ISSUE TITLE
How to Switch between Anaconda installations

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#710]
All this info is out of date.

[This post](https://groups.google.com/d/msg/leo-editor/dy132kU7EnA/S8AIaJ-zBgAJ) by David Szent-Györgyi discusses distributions issue for Windows. My present plan is to leave the NSIS installer unchanged.  The Windows pyinstaller distro will be based on 32-bit code.

I installed 32-bit Anaconda2-5.0.1-Windows-x86.exe, but pyinstaller is incompatible with PyQt4. [This page](https://stackoverflow.com/questions/21637922) tells how to install PyQt4 on Python 2.  The following is a bit different, but works:
```
conda uninstall anaconda-navigator
conda uninstall navigator-updater
conda install qt=4
```
And now pyinstaller works!
```
[a32] pyinstaller --clean --win-private-assemblies launchLeo-unified.spec
```
The second comment here gives scripts for switching between 32 and 64 bit installs.

**Comment by maphew** [comment]
If you use `set` instead of `setx` reloading the console isn't needed. Oh, maybe you want to avoid having to alter PATH with every new console?  In any case I would add something like the below so you don't need to remember what last setting was (using either set or setx as needed).

~~~
setx path "%OLD_PATH%;c:\Anaconda3_32bit;c:\Anaconda3_32bit\Scripts"
setx prompt "[a32] $P$_$G"
~~~

**Comment by edreamleo** [comment]
[This page](https://superuser.com/questions/916649/what-is-the-difference-between-setx-and-set-in-environment-variables-in-windows) discusses the differences between set and setx.
