### ISSUE TITLE
Make the valuespace plugin more visible

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#761]
How many times has Terry reminded me and others about the valuespace plugin?

This plugin creates live objects, which can be introspected/auto-completed, as in jupyter notebooks.

Details unclear, but this is an extremely important issue.

**Comment by tbnorth** [comment]
On Fri, 02 Mar 2018 15:21:30 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> Details unclear, but this is an extremely important issue.

I think the challenge is to separate, either in the docs. or the code,
the vs-eval-* commands from the rest, which is Ville's clever but
convoluted way of making and outline into a sort of live document.  I
put the vs-eval-* stuff in there partly because at the time it seemed
there are a new plugin every 24 hours and doubling up seemed a way to
try and control that trend, but more because the plugin already
defined a namespace (c.vs) and the vs-eval-* stuff needed a namespace,
and sharing seemed possibly useful.

**Comment by edreamleo** [comment]
I am going to close this.  #839 (Split valuespace) separates the new eval- commands from the too-complex vs- commands.
