### ISSUE TITLE
CheatSheet.leo should demo Leo's features

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#762]
The demos should include markdown rendering:

Leo's existing markdown rendering is extremely powerful because you can embed html into markdown. The `<img>` element can insert svg graphics and movies in Leo's rendering pane.  In particular, the style attribute allows virtually unlimited flexibility!

I've renamed this issue.  Imo, there is no need to demo features in the quickstart.

**Comment by xgid** [comment]
FYI, I've started to work on this. I see no way to add me as an assignee, am I missing permissions to do it? How should I do it?

Regarding the VR examples in leo/test/test.leo, there are many which are not working:

- Python code: is rendered wrongly at the VR pane (as if all newlines were stripped)
- @graphics-script: shows this at the log pane:
```
:2: undefined name 'gs'
:3: undefined name 'gs'
:3: undefined name 'gv'
:3: undefined name 'gs'
:7: undefined name 'gs'
```
- @html display Leo tree (cool): rendering is quite ugly, at least with the default theme in Windows:
![imagen](https://user-images.githubusercontent.com/12764559/37594231-5be1c670-2b53-11e8-877d-57f13c969797.png)
- @html Leo's home page: talks about Leo v4.7 (I can fix that myself), but most important:
  * Text sizes are too big
  * Logo is not shown (a box is shown instead)
- @image nodes give "file not found" errors because paths are absolutes and pointing to `c:\leo.repo\...`
- @movie Gayane Ballet (Local file): points to a file at `C:\Users\edeamleo`
- @movie Gayane Ballet (Url): takes the URL as if it was a relative path, showing this error: `Not found: C:/dev/leo/leo/test/https:/www.youtube.com/watch?v=EB3IokHelRk`
- @movie Sample video ...: idem than above
- @networkx my network: has an empty body
- @pyplot matplotlib animate_decay: worked perfectly the first two times that I selected the node, but the plotting got frozen just after starting from then on.
- @pyplot basic_example: shows a nice plot, but no animation. Is this correct?
![imagen](https://user-images.githubusercontent.com/12764559/37594748-e01530ca-2b54-11e8-994c-325027462451.png)
- @pyplot barchar_demo: this one works great!
- @svg bubbles sources: this is also working.
- @svg bubbles.svg: this works when I jump from the previous node to this one, but not on his own because it's pointing to a local file. The problem is that it gives no errors!
- @url Leo's home page (md default, ... all of them): Ctrl+left clicking the node does NOT open the URL in the browser for me. Is this correct?
- docstring test: It's working
- markdown test (including url): it's working, altough there's a minor typo that I have corrected
- rst test (including url): it's working ok

How do you want to address all these? Maybe we should open new issues for some of them...?

**Comment by edreamleo** [comment]
On Mon, Mar 19, 2018 at 7:15 AM, XGiD <notifications@github.com> wrote:

> FYI, I've started to work on this. I see no way to add me as an assignee,
> am I missing permissions to do it? How should I do it?
>
​I just invited you to be a core member of leo-editor.​

> Regarding the VR examples in leo/test/test.leo, there are many which are
> not working:
>
For now, just include the items that are working.

>
>    - Python code: is rendered wrongly at the VR pane (as if all newlines
>    were stripped)
>
> ​I'll look into this.

>
>    - @graphics-script: shows this at the log pane:
>
> :2: undefined name 'gs'
> :3: undefined name 'gs'
> :3: undefined name 'gv'
> :3: undefined name 'gs'
> :7: undefined name 'gs'
>
> ​This is a known problem. ​You can suppress these message by suppressing
pyflakes in the files.  Add the following settings:

@bool run-pyflakes-on-write = False

However, it still doesn't do anything for me.  You can delete this from the
demo.

>
>    - @html <https://github.com/html> display Leo tree (cool): rendering
>    is quite ugly, at least with the default theme in Windows:
>
> ​Just set zoom: 75% in the actual body text.

>
>    - @html <https://github.com/html> Leo's home page: talks about Leo
>    v4.7 (I can fix that myself), but most important:
>       - Text sizes are too big
>       - Logo is not shown (a box is shown instead)
>
> ​I would pick another html example, one that doesn't use javascript.​


>
>    -
>       - @image <https://github.com/image> nodes give "file not found"
>    errors because paths are absolutes and pointing to c:\leo.repo\...
>
> ​Forget about this for now.​


>
>    - @movie <https://github.com/movie> Gayane Ballet (Local file): points
>    to a file at C:\Users\edeamleo
>    - @movie <https://github.com/movie> Gayane Ballet (Url): takes the URL
>    as if it was a relative path, showing this error: Not found:
>    C:/dev/leo/leo/test/https:/www.youtube.com/watch?v=EB3IokHelRk
>    - @movie <https://github.com/movie> Sample video ...: idem than above
>
> ​Forget about movies.​


>
>    - @networkx <https://github.com/networkx> my network: has an empty body
>
> ​Forget about this.​


>
>    - @pyplot matplotlib animate_decay: worked perfectly the first two
>    times that I selected the node, but the plotting got frozen just after
>    starting from then on.
>
> ​Yeah, sometimes this happens.  I would leave it in.​


>
>    - @pyplot basic_example: shows a nice plot, but no animation. Is this
>    correct?
>
> ​It may work, depending on platform.

>
>    - @pyplot barchar_demo: this one works great!
>
> ​Include what works.​


>
>    - @svg <https://github.com/svg> bubbles sources: this is also working.
>    - @svg <https://github.com/svg> bubbles.svg: this works when I jump
>    from the previous node to this one, but not on his own because it's
>    pointing to a local file. The problem is that it gives no errors!
>
> ​I would leave them both in.​



>
>    - @url <https://github.com/url> Leo's home page (md default, ... all
>    of them): Ctrl+left clicking the node does NOT open the URL in the browser
>    for me. Is this correct?
>
> ​Ctrl-click in the body pane.  Regular click in the rendering pane.​


>
>    - docstring test: It's working
>    - markdown test (including url): it's working, alt
>    ​h​
>    ough there's a minor typo that I have corrected
>    - rst test (including url): it's working ok
>
> How do you want to address all these?
>
*​Summary*

​Use your judgement.  Include what generally works. Omit what doesn't.

I'll attempt a fix for python source-code issues.

Edward

**Comment by edreamleo** [comment]
Completed at e8c8fb834.
