### ISSUE TITLE
Create a Themes menu

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#766]
Leo now has library of pre-built themes that users can choose without knowing anything about @settings trees and myLeoSettings.leo.  Discussion [here](https://groups.google.com/d/msg/leo-editor/rsZARO7A57s/tfrA-LX7BAAJ).

**Theme files** will be .leo files containing `@settings` trees. Choosing a theme from the Themes menu will load a theme file *as if it were a settings file*, but *without* reloading myLeoSettings.leo.

- [x] Add a Themes menu, allowing users to pick a theme file.
- [x] Improve the Themes menu. It should open a Theme file in another process.
- [x] Migrate files from leo/themes/old_themes.leo to leo/themes.
       Ongoing.  Good enough for now.
- [x] Add `@string theme-name`.
- [x] Add `--theme=<path to theme file>` command-line argument.

**No partial themes**

Using only **complete** themes is the simplest thing that could possibly work. 

**Won't do**: A theme file could change to just syntax coloring settings, or just defining text sizes or colors. Something like this:

    LeoBlackTheme.leo
    LeoSolarizedConsoleText.leo
    LeoSolarizedSyntaxColoring.leo.

Zoom.Quiet suggests this theme: base Sublime Text 3 's Spacegray/base16-eighties.dark.tmTheme -> predawn-DEV.sublime-theme

**Comment by tbnorth** [comment]
On Fri, 02 Mar 2018 07:40:42 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> - [ ] Add a Themes menu, allowing users to pick **pre-built** themes
> and syntax colors.
> 
> - [ ] Support a new, *optional*, simpler, way to specify themes.
> 
> Don't panic.  Existing themes settings will remain in place. Imo, the
> present system, built on a mix of settings, is a failed experiment.
> Something simpler should be used in future, while retaining the
> present baroque scheme.

I think a working Leonine solution has been built, but subsequently
broken by cleanup / packaging.  I can't remember top of head if the
currently damaged system supported switching themes by changing a
single setting - I guess it was more a case of moving a single subtree,
which is not quite a clear for neophytes.  We've had the conversation
many times before, but I don't think managing Leo's theme settings is
any more complicated than any of Leo's other settings, which are
perhaps not complicated for people thinking in the Leo way, but
unfortunately tend to be the first thing newbies run in to.

But I think perhaps your talking more about switching themes than
authoring / editing them, which is somewhat different.  The only caveat
is that people will want to tweak the theme they switch to, so the
authoring system needs to work as well.

Also perhaps we need to give up on
https://bugreports.qt.io/browse/QTBUG-59533
ever getting fixed :-/

I know I've put off some maintenance on the theme system because having
to code around that is a pain.  Partly to do with supporting the border
highlighting implementation, but other elements as well.

Cheers -Terry
