### ISSUE TITLE
Line breaks not preserved in VR for python source code

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#829]
Report: In the viewrendered plugin, formatting as html does not preserve/insert line breaks.  

The report is mistaken:

- The `::` syntax works for `@language rest` or `@language python`, which uses rST.
- The \`\`\` syntax works for `language md`.

I am going to close this item.

**Comment by edreamleo** [comment]
I am going to close this item.  The VR plugin is working as expected.  In particular, VR renders `@language python` as rST text.

**Comment by xgid** [comment]
Just to check that this is the expected behaviour, I'm currently seeing this in the current `leo/test/test.leo` VR examples:

![imagen](https://user-images.githubusercontent.com/12764559/37846157-88be3cd6-2eab-11e8-888a-26091645a41e.png)

Is this the rST rendering you are refering to?

**Comment by edreamleo** [comment]
On Fri, Mar 23, 2018 at 1:07 PM, XGiD <notifications@github.com> wrote:

> Just to check that this is the expected behaviour, I'm currently seeing
> this in the current leo/test/test.leo VR examples:
>
​There is no need for a screenshot. The example is:

@language python

def spam():
    pass

If you want to render this with rST (which may be the default, the screen
shot doesn't tell us), you would use:

@language python

::

    def spam():
        pass

Otoh, if markdown is the default, you would use:

```python
def spam():
    pass
```

My point is that the viewrendered plugin doesn't assume add markup
depending on which language is in effect.

Perhaps this is confusing, but is is the way the VR plugin works. In fact,
it makes sense. We don't need VR to show us source code.  It's purpose is
to render *other* things.  Like html, markdown, rST, etc.

Edward

**Comment by xgid** [comment]
Yes, the way you explain it, makes sense. What confused me in the first place is that it is the first child of a node labeled "Viewrendered examples"! :simple_smile: 

But the main reason this behaviour looks weird to me is because of my common use of the viewrendered pane. That's going through my Leo notes in "reading mode". In this mode, I just go through the nodes reviewing things and clicking links, so I like the cleaner, less cluttered view that the VR pane offers. When I need to edit a node, of course I go to the body pane, but it's not my main view.
So, under this usage, I would expect that a node that has been properly marked with "@language python" would also be properly rendered at the VR pane (even better than in the body pane because here we can render all links, bolds, and so on appropriately).

What you say makes sense to me when the @language in effect for the node is md or rest and you write down just some Python code in there, without any @language indication, because the VR plugin has no way to know that that's a Python code. But when you've set the @language to python before the code, there's no possible confusion.

Do you think it would be too hard to make the VR plugin render the @language python nodes appropriately? Does this use case makes any sense to you?

**Comment by edreamleo** [comment]
On Sat, Mar 24, 2018 at 8:09 AM, XGiD <notifications@github.com> wrote:

> Do you think it would be too hard to make the VR plugin render the
> @language <https://github.com/language> python nodes appropriately?
>
​Anything is possible.​


> Does this use case makes any sense to you?
>
​I've tried to explain why this use case is dubious.  Let me think about
this more.

I'm not ruling it out, but I don't want to cause problems for the more
usual cases.

Edward​
