### ISSUE TITLE
*.config.getData(foo) strips comments inconsistently

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#840]
`*.config.getData(foo)` seems to strip lines starting with `#` in descendant nodes but not the top node of the setting.  Intentional?

**Comment by edreamleo** [comment]
On Tue, Mar 27, 2018 at 9:08 AM, Terry Brown <notifications@github.com>
wrote:

> *.config.getData(foo) seems to strip lines starting with # in descendant
> nodes but not the top node of the setting. Intentional?
>

​As I read the code, c.config.getData and ​

​gcm.getData clearly strip '#' from​ all lines.

However, the code to do this looks fragile, because the '#' must start the
line.

if data and strip_comments:
    data = [z for z in data if not z.startswith('#')]


Does the following help?

if data and strip_comments:
    data = [z for z in data if not z.strip().startswith('#')]

Edward

**Comment by edreamleo** [comment]
**Terry Brown**:  *.config.getData(foo) seems to strip lines starting with # in descendant nodes but not the top node of the setting.

**EKR**: As I read the code, c.config.getData and ​​gcm.getData strip '#' from​ all lines, but the code is fragile, because the '#' must start the line:
```python
if data and strip_comments:
    data = [z for z in data if not z.startswith('#')]
```
Does the following help?
```python
if data and strip_comments:
    data = [z for z in data if not z.strip().startswith('#')]
```

**Comment by tbnorth** [comment]
The problem was that the code had a hard assumption that the first line of data it would get would start with 'RULE ', I made it more robust to not break if that wasn't true.  But the `#` not at the start of the line was what was causing the unexpected data, so fixing that would be more consistent.

**Comment by edreamleo** [comment]
On Tue, Mar 27, 2018 at 12:21 PM, Terry Brown <notifications@github.com>
wrote:

> The problem was that the code had a hard assumption that the first line of
> data it would get would start with 'RULE ', I made it more robust to not
> break if that wasn't true.
>

​Good to know.​


> But the # not at the start of the line was what was causing the
> unexpected data, so fixing that would be more consistent.
>
​Rev fd8a6cf strips comments, including comments with leading whitespace.
