### ISSUE TITLE
Repeatedly enter comma ( , )  it toggles on/off.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#849]
Apologies if this is a coding type convention :)
If I type a comma ( , ) into headline or body text the comma appears. However if I type another comma ( , ) the first one disappears.
As I repeatedly enter the ,  it toggles on/off. 
This doesn't occur with any other character, and I haven't seen it happen in other editors.

**Comment by edreamleo** [comment]
On Wed, Apr 4, 2018 at 11:25 PM, LewisNeal <notifications@github.com> wrote:

> Apologies if this is a coding type convention :)
> If I type a comma ( , ) into headline or body text the comma appears.
> However if I type another comma ( , ) the first one disappears.
>
​You could call this a coding convention.  It is part of the abbreviation
machinery.

The work around is to type the first comma, backspace over it, then type
the second comma.

Edward​

**Comment by tbnorth** [comment]
On Wed, 04 Apr 2018 21:25:12 -0700
LewisNeal <notifications@github.com> wrote:

> Apologies if this is a coding type convention :)
> If I type a comma ( , ) into headline or body text the comma appears.
> However if I type another comma ( , ) the first one disappears. As I
> repeatedly enter the ,  it toggles on/off. This doesn't occur with
> any other character, and I haven't seen it happen in other editors.

,, seaches for the next occurrence of <|target|>, and selects it.  It's
the abbreviation template expansion template fill in helper.  You can
probably change / disable it looking at @settings related to
abbreviations.

You can get two commas by typing them with a space between them and
deleting the space, or copy/paste.

If there's a consensus for not having it enabled by default because
it's odd if you're not using it, we could have it not enabled by
default.

Cheers -Terry
