### ISSUE TITLE
syntax error in `extensions/asciidoc.py`

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#856]
While troubleshooting #847 noted this error in passing

~~~
    byte-compiling c:\apps\miniconda3\envs\leo-pip-github\Lib\site-packages\leo\extensions\asciidoc.py to asciidoc.cpython-36.pyc
      File "c:\apps\miniconda3\envs\leo-pip-github\Lib\site-packages\leo\extensions\asciidoc.py", line 101
        except KeyError, k: raise AttributeError, k
                       ^
    SyntaxError: invalid syntax
~~~

**Comment by edreamleo** [comment]
On Tue, Apr 10, 2018 at 7:08 AM, matt wilkie <notifications@github.com>
wrote:

> While troubleshooting #847
> <https://github.com/leo-editor/leo-editor/issues/847> noted this error in
> passing
>
>     byte-compiling c:\apps\miniconda3\envs\leo-pip-github\Lib\site-packages\leo\extensions\asciidoc.py to asciidoc.cpython-36.pyc
>       File "c:\apps\miniconda3\envs\leo-pip-github\Lib\site-packages\leo\extensions\asciidoc.py", line 101
>         except KeyError, k: raise AttributeError, k
>                        ^
>     SyntaxError: invalid syntax
>
> ​Guido seems regard those who complain about the Python 2/3 split ​as
people akin to trolls.  Well, count me among them.  Python 3 was a huge
mistake, a mistake that keeps on costing devs who have better things to
do...

There is supposed to be a unit test that tests the syntax of all files.
Not sure why this wasn't caught.

Edward

**Comment by edreamleo** [comment]
On Tue, Apr 10, 2018 at 8:12 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

There is supposed to be a unit test that tests the syntax of all files.
> Not sure why this wasn't caught.
>

​The test explicitly disables the test against asciidoc.py​

​when using python 3.

Presumably this is because asciidoc not only fails to compile with python
3, but also would need to be rewritten for python 3. This I am not willing
to do now.

Imo, asciidoc.py probably should be not appear in "bundled" distros.  Do
with this opinion as you like ;-)

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  asciidoc.py will only work with python 2.  I have no plans to update it.
