### ISSUE TITLE
outline pane styles not applied

### ISSUE THREAD

**Issue by adlaius** [leo-editor/leo-editor#894]
Body pane and log window pick up fonts/colors as expected, but the outline pane is wholly unstyled, both out of the box and after attempts to modify via myLeoSettings. This is on:

Git repo info: branch = master, commit = 6d05a6ee0578
Python 3.6.5, PyQt version 5.10.1
Windows 10 AMD64 (build 10.0.14393) SP0

**Comment by technatica** [comment]
Please try changing the theme setting string in myLeoSettings to @string
theme-name = BreezeDarkTheme and restart Leo.

Let me know what happens.

Chris

**Comment by adlaius** [comment]
Well, I was searching around last night and noticed a number of related threads in various places that indicate (py)Qt >= 5.8 has problems, so I reverted via pip to 5.7.1, and styling now works as expected. Looking particularly at [this bug](https://bugreports.qt.io/browse/QTBUG-59533), perhaps there needs to be a version requirement for Leo?

Also, being new to the program, I don't really know where the string-name @string needs to be; just any node under myLeoSettings->@settings? Perhaps more to the point, does "theming" use an entirely different mechanism from specifying fonts/colors under the "Qt Gui settings" node? As in, would it be worthwhile to test the behavior of themes on newer PyQt versions?

**Comment by technatica** [comment]
HI Brian,

Add the following as a headline as a child of @settings in myLeoSettings:
@string theme-name = BreezeDarkTheme as it will override the default theme.

When I designed this particular theme I incorporated the workaround for the
Qt bug. It should work for you with PyQt >= 5.8 (I run 5.10.1).

The fix is to move the styles for the status line to the very bottom of the
theme because if you are running PyQt >= 5.8 it fails and halts the parsing
of the rest of the stylesheet. So some of the stylesheet works fine, the
rest simply is never loaded.

HTH,

Chris

**Comment by wangzhaohe** [comment]
`cp BreezeDarkTheme.leo another.leo` name
otherwise git pull will complain.
Then `@string theme-name = another` in myLeoSettings.leo

**Comment by adlaius** [comment]
Thanks Chris, the theme seemed to work just fine on an Ubuntu VM last night; looks nice.

**Comment by technatica** [comment]
Hi Brian,

Thanks for the confirmation.

I'll take a peek at the default theme.

Chris
