### ISSUE TITLE
pip install on linux with python 3.5 fails

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#944]
On ubuntu 16.04 with python 3.5, these steps are required to get working leo installed via pip:

```
$ python3 -m venv leo-editor-venv
$ cd leo-editor-venv
$ bin/pip install leo
$ bin/pip install PyQt5==5.10.0
$ bin/leo
```
See https://groups.google.com/forum/#!topic/leo-editor/ghiIN7irzY0 for the full details, but here is the important part:

https://github.com/mu-editor/mu/issues/502#issuecomment-399682079
https://github.com/mu-editor/mu/issues/538#issuecomment-404096351

> "Chipping in rather late: the error message in the OP refers to a Python API that was only added in 3.6.1. Since the venv is using Python 3.5 it appears that Qt have offered a wheel for 3.5 which uses code only available in 3.6"

So maybe (as @maphew mentioned in the email thread) some version pinning is needed for the dependencies? That seems like a trade-off since maybe users on python 3.6+ would be better off with the newer PyQt versions.

**Comment by btheado** [comment]
If you get a segfault using this approach, try disabling python_terminal. See the linked google groups thread above for details.

**Comment by edreamleo** [comment]
I would like to resolve this for the next release.

**Comment by edreamleo** [comment]
I have just added the "Waiting" label.  The ball is in Matt's court.

**Comment by maphew** [comment]
For me on linux mint 18.2, based on ubuntu 16.4, `pip install leo` works in new mini-conda environments for both python 3.5 and python 3.7. In these pip installs pyqt 5.10 and 5.11 respectively.  

When I use _venv_ instead of _conda_ pip install leo halts due to fatal failure with a long stack trace when attempting to build a cryptography module. 

```
Leo 5.7.3, build 20180525162844, Fri May 25 16:28:44 CDT 2018
Not running from a git repo
Python 3.5.5, PyQt version 5.10.1
```
```
Leo 5.7.3, build 20180525162844, Fri May 25 16:28:44 CDT 2018
Not running from a git repo
Python 3.7.0, PyQt version 5.11.1
```

Install recipe used:

```
conda deactivate
conda create -n leo-xxx
conda activate leo-xxx
conda install pip
pip install leo
leo-messages
```
Package listing for each environment:

* [leo-conda-py35-env.txt](https://github.com/leo-editor/leo-editor/files/2321262/leo-conda-py35-env.txt)
* [leo-conda-py37-env.txt](https://github.com/leo-editor/leo-editor/files/2321261/leo-conda-py37-env.txt)

This is a laptop I've used for some time, so I don't know how well this experience compares to a virgin OS install. In particular there was a time when I scrambled my python setup due to confusion over whether I should be using user-space or system python and pyqt (`pip install xxxx` or `sudo pip install xxxx`), which led to a mess that eventually led me to rely only on Anaconda (via miniconda) for managing python. 

All of which is a long way to say: sorry, I can't test for your circumstance, it works for me. :-/

**Comment by btheado** [comment]
> When I use venv instead of conda pip install leo halts due to fatal failure with a long stack trace when attempting to build a cryptography module.

When I've seen this issue (I don't remember the circumstances), it worked to upgrade pip:

`pip3 install --upgrade pip`

With newer versions of pip, the per-compiled .whl version of packages are installed and you can avoid all the compiler nightmares.

**Comment by maphew** [comment]
Closing as it looks like upgrading pip is the solution. Re-open if needed.
