### ISSUE TITLE
Create a way to isolate documentation in a subnode

### ISSUE THREAD

**Issue by maparent** [leo-editor/leo-editor#946]
I was hoping to have my documentation in a subnode, so I could share it (as a clone) between the code and a separate documentation file (md or rst).
But trying to set
```
@
<< description >>
@c
some code
```

did not work, as the << description >> was not parsed as a node reference in documentation;
I thought of putting the `@` in the description node itself, without code:
```
<< description >>
some code
```
containing `<< description >>`:
```
@
some comment
```

 but I ran into another bug where the multiline comment markers got repeated through the roundtrip (using `@clean` files.)
This one is more of a bug, but solving it does not solve my original request of having a block of text live in code comments and documentation. (because I suspect the documentation would not like the `@`)
Best regards,
Marc-Antoine

**Comment by wangzhaohe** [comment]
I also want a method to arrange document in codes.

**Comment by tbpassin** [comment]
I would also like to mix in pure documentation parts into a tree of code.  But there doesn't seem to be much interest in that kind of "literate programming" any more, so it may not happen.

One way I have worked around this is to have two trees - one for the code and one for the documentation.  In the documentation tree, you can write a section of text, then right after it insert a clone of a node from the code tree.  Then you can publish the documentation tree and it will include any clone nodes from the code tree.

**Comment by edreamleo** [comment]
On Sat, Aug 4, 2018 at 8:18 AM, tbpassin <notifications@github.com> wrote:

> I would also like to mix in pure documentation parts into a tree of code.
> But there doesn't seem to be much interest in that kind of "literate
> programming" any more, so it may not happen.
>
This is a frequently requested feature, but it's not clear how to proceed.

Cloning nodes isn't sufficient.  We would like code-supported markup to do
"just what we want", whatever that is.  I'll think about this once again.

Edward

**Comment by tbpassin** [comment]
I think there are basically two ways to do this, from a user point of view.

1.  Allow a tree of code to contain nodes that contain text, possibly markdown or rst.  These nodes would not get written to the code itself when the file is saved.  But they would be written when a documentation command like rst3 is executed.  Obviously the big issue here is how to store the special nodes, since they could not exist in a @clean file.
2. Allow sections of documentation within a node that would otherwise be code.  They would be saved when the Leo file is saved, but either not be written, or be escaped, in the code file when that is written.  I suppose that the @...@c mechanism would be a prototype for this kind of thing.  Again, the documentation would be picked up when a rst3 type command is issued.

I like @clean files, but I would be willing to use a command to write clean files from an @file or some new @... type of file, if it meant that I could get the documentation parts written out.

One complication for both the two approaches above is that when I write documentation, I don't always want to include all the code, but just some parts of it.  I'm not sure how this wish fits into the above.  Rst has a mechanism for identifying parts of a document so they can be inserted by reference.  Maybe we could use something like that.  In the rst framework we would identify a section, say "code-03".  In the code node we want to include in the docs, we would insert something like:

    @rst-ref code-03
    #.... code here will be included in the documentation, but
    # the @ lines will not be in the code output (or will be escaped).
    @c
    # code continues here and will not be copied into the documentation.

**Comment by vitalije** [comment]
I have just added new plugin md_docer in the devel branch.

This plugin adds two new commands to Leo: `md-write-files` and `md-copy-leo-gnx`.

`md-write-files` searches outline for the nodes with headline like `md:<filename>`. For each found node it writes its subtree as a markdown document replacing all lines like `LEOGNX:<some gnx>` with the lines from the node whose gnx follows `LEOGNX:` prefix.

The other command `md-copy-leo-gnx` copies to clipboard currently selected node in the above defined form `LEOGNX:<gnx>`. 

Using this link it is possible to force code sample to be in sync with the real source code. Just select node in the source tree and execute `md-copy-leo-gnx` and then paste link to document where you wish this code sample to appear. Usually in **```** block.

In the Leo document containing documentation you can insert at-buttons nodes to execute this commands or to bind them to some shortcut.

Vitalije

**Comment by vitalije** [comment]
@maparent I think plugin commands give you exactly what you asked for. Just replace <<<cloned node snippet>> with LEOGNX:<gnx of node>. This replacement text you get by selecting the node with code sample, executing mini-buffer command `md-copy-leo-gnx` and then pasting text to node with the documentation in place where you want code snippet to be. Currently it produces markdown but if you need rst I can add command for this also.
Vitalije

**Comment by maparent** [comment]
Ah, I finally understand how this works. Yes, that makes sense and could work. Thank you!

That said, I think it is unfortunate that the `md:`filename cannot reuse the existing `@clean` filename mechanism (or any of the existing @ directives).

(Also, it forces my node title to be unique, rather than the contextually-defined `<<documentation>>` that I could make local by cloning. But that was likely to be an issue anyway.)

What I see now is the generic need for a non-local reference: eg allow `<<< global node name >>>` to coexist with the existing `<< child node name >>`. This could be part of the leo substitution machinery for all `@file` types.

We could even have `<<< name | name | name >>>` to paths that refine context.

Thoughts?

**Comment by vitalije** [comment]
Sorry, I don't understand what you mean by 
> it forces my node title to be unique

Node headlines appear only in mark down files as headings. Cloned snippets of code appear in markdown files without headline (if you don't explicitly write one yourself). Only code in body of cloned nodes is copied to the markdown file.
If you want to have markdown file you don't have to use at-clean at all. You might want to use it for source code files or for some other purposes. Mark down files are generated from the outline.

Why I didn't use at-clean? Because at-clean and at-file files are read by Leo and their nodes are updated from the content of file. So if you put there LEOGNX:<some gnx> and this line was replaced by the content of another node, then next time you open outline this link is gone and replaced with the fixed text. If you later edit code in the original node, those changes you will have to manually port to documentation file. By using md: in headline, we achieve only one directional flow of data: from outline to generated file. So your link stays unchanged, but the actual code snippet in the file content gets synchronized with the source code.

Perhaps this sounds too complicated, but if you try to write some document using this technique you will most certainly understand how it works.

**Comment by vitalije** [comment]
Also, if body of any node in md subtree, startswith '#' its headline wont be used. In that case plugin assumes you have written heading yourself in body.

**Comment by maparent** [comment]
Node title to be unique: I realize that I expected the gnx reference to be based on node title, not identifier. My misunderstanding. Forget I said that.

I understand what you mean about unidirectional data flow, and I agree it's a perfectly fine workflow; but I would actually be happier with the workflow where a change to the changed text in either file would change the text in both files. Now, I realize there may be subtle issues here.

**Comment by vitalije** [comment]
Do you use other editor to edit mark-down files or just Leo? If you are using just Leo, then you will never change content of mark-down file or at least the part with the code example. The only way to change it is by changing the body in the source code node. Text in the markdown code sample is just a view into source code. There is no text there that you can change and propagate changes back to source code.

If you want bi-directional link then you have to use clones in both source code and mark down subtree, but then you will have to find a way to indent this node and suppress its headline in the output. Most likely it would be possible to achieve this with different script, but then again you won't be able to use at-file nor at-clean nodes for this.

**Comment by maparent** [comment]
I use another editor, and I care about the round-trip.
With a `<< title >>` section, I do not have to worry about the headline. (Did verify.) So the clone method works, if only outside of the `@/@c` mechanism.

**Comment by vitalije** [comment]
Do you use other editor to edit mark-down files or just Leo? If you are using just Leo, then you will never change content of mark-down file or at least the part with the code example. The only way to change it is by changing the body in the source code node. Text in the markdown code sample is just a view into source code. There is no text there that you can change and propagate changes back to source code.

If you want bi-directional link then you have to use clones in both source code and mark down subtree, but then you will have to find a way to indent this node and suppress its headline in the output. Most likely it would be possible to achieve this with different script, but then again you won't be able to use at-file nor at-clean nodes for this.

**Comment by vitalije** [comment]
Rev 4121e39 contains updated version of md_docer plugin.

It now supports two new kind of nodes:
  * `@transformer <name>` nodes
  * `@transform-node <transformername>(<srcgnx>)`

`@transformer` node define a transformer script with given name. This script has predefined symbols c, g, v and out. The last one `out` is a file like object and `v` is source node. Script can access body of source node and transform it  and write transformed text to the `out`.

`@transform-node <tr name>(<srcgnx>)` will have its body updated after every synchronization (which by default is done before save command, but may be performed using new `md-sync-transformations` command at any time). Body of these kind of nodes will contain transformed version of its source vnode body.

Now, if I understand correctly your problem, you wish to have same code in documentation file and in source code file, but using just clone is not enough because those files use different syntax. You wish that node in source code gets commented out using correct comments for the given language, and in documentation you wish the same text without comments. Am I correct?

If so, you can define your own transformer to do the job. For example let's say you are writing markdown document about python code. In mark-down document '#' at the beginning of line will be treated as headline mark, but in source code you wish this to be part of comment section and '#' is necessary.

Then you may write code example in mark-down file in one node. Copy gnx of this node and in the source code insert new node with the headline `@transform-node pycomment(<paste gnx here>)`.
Then add anywhere in the outline node with the headline `@transformer pycomment` and body like this:

```python
   for line in v.b.splitlines(True):
        out.write('# %s'%line)
```

Then before you save the outline, this node will be updated and its content will be commented out python example. You can go in the opposite direction too. Write code example in the python file, and put the `@transform-node` in the documentation file, and use different transformer to remove the comments.

There still won't be round-trip in both directions, so you will have to choose which direction better suits you.

**Comment by maparent** [comment]
First, thank you, this really seems extremely useful in other cases.
Great work generalizing your original plugin.

As for your assessment of my problem, not at all. Clone is perfectly adequate for my needs, actually. My only problem was that `<<...>>` node expansion does not work in the `@` section of a `@/@c` pair. But there's no question that your work there goes beyond my initial statement, and is useful at this point.

I still think that a syntax for global (non-child) node name expansion might be independently useful, but that's a different concern, and I suspect your solution cover more cases.

Regards,
Marc-Antoine

**Comment by vitalije** [comment]
I still don't understand why you need `<<...>>` to work inside `@/@c` pair. You can always split this `@/@c` block in two parts: before and after `<<...>>` and put another pair of `@/@c` in the child node.

**Comment by maparent** [comment]
I do not understand what you propose exactly, but it's clear there are many usage scenarios other than my original pattern. My current workaround (`/** << ... >> */`) is one of them. Your plugin is another.

Simply, I expect my original pattern to work, and its failure is a broken expectation.

Maybe the solution is simply to state in the leo documentation that `<<...>>` fails in the first half of a `@/@c` pair. But I'm quite sure that the failure would be surprising to most users, and that should be reason enough.

**Comment by vitalije** [comment]
> Maybe the solution is simply to state in the leo documentation that `<<...>>` fails in the first half of a `@/@c` pair. 
I think you are right. I couldn't find anything in documentation about this restriction.

**Comment by edreamleo** [comment]
I have just created #950 to handle the problem of section references in `@doc` parts.

It's not clear whether #950 can be done with a reasonable amount of work, but I'll investigate next.

**Comment by tbpassin** [comment]
I'm not sure if this is helpful or not, but I have found that the tree-walking code for ``@file`` files will ignore (that is, will not output) a named section if you add a comment ("#") to its reference.  For example, if you have in a node the following:
```
   # some code ...
   @others
   #<<main>>
```
Then the ``<<main>>`` section  will not be written to the output file, and there will be no error.  This is for Leo 5.3, Python 2.7, Windows.  

If the same basic code is used for walking the tree for markdown, etc, output then at least it would be easy to switch named sections in and out in this way.  The code might have to be adjusted not to output ``#<<main>>`` as a section headline...

**Comment by edreamleo** [comment]
On Tue, Aug 7, 2018 at 4:11 PM, tbpassin <notifications@github.com> wrote:

> I'm not sure if this is helpful or not, but I have found that the
> tree-walking code for @file files will ignore (that is, will not output)
> a named section if you add a comment ("#") to its reference. For example,
> if you have in a node the following:
>
>    # some code ...
>    @others
>    #<<main>>
>
> Then the <<main>> section will not be written to the output file, and
> there will be no error. This is for Leo 5.3, Python 2.7, Windows.
>
This would be shocking, if true.  In my tests, the only way to avoid an
error is to provide a (possibly empty) section definition node for <<main>>.

Without such a definition node, the following gives the expected error, in
"devel" for both @clean and @file files:

print('hi')
@others
#<<main>>
print('done')

Edward

**Comment by tbpassin** [comment]
Well, yes, the file I was working on when I found this behavior *did* have a section node with a headline \<\<main>>.  Sorry I wasn't clear about that.  I had taken it for granted that there would be no reason to comment out a section reference if there were no section with that name.

**Comment by tbpassin** [comment]
Ah, I see...What I wrote earlier about commenting out a section reference was wrong.   I'm sorry about that.  What seems to have happened is that, because of the order that I had for the section references, when I "commented out" one of them by adding a leading "#" character, that section still got inserted into the file, but in the serial order in which that section appeared.  That was far enough away that when I checked the saved file of code, the contents of that section had moved too far off the screen for me to see it.  Just now I rechecked by doing a string search for the content, and it was there but in the new position.

So I mixed myself up, and I apologize for the premature and wrong statement.

**Comment by edreamleo** [comment]
On Thu, Aug 9, 2018 at 8:49 AM, tbpassin <notifications@github.com> wrote:

> Ah, I see...What I wrote earlier about commenting out a section reference
> was wrong. I'm sorry about that. What seems to have happened is that,
> because of the order that I had for the section references, when I
> "commented out" one of them by adding a leading "#" character, that section
> still got inserted into the file, but in the serial order in which that
> section appeared. That was far enough away that when I checked the saved
> file of code, the contents of that section had moved too far off the screen
> for me to see it. Just now I rechecked by doing a string search for the
> content, and it was there but in the new position.
>
> So I mixed myself up, and I apologize for the premature and wrong
> statement.
>
It's not a problem.  I have made many such statements myself ;-)

Edward

**Comment by edreamleo** [comment]
I am going to close this issue. I have no further plans in this aread.

**Comment by edreamleo** [comment]
I am going to reopen this because of new ideas.

**Comment by edreamleo** [comment]
[User filters](http://leoeditor.com/customizing.html#customizing-the-rst3-command) for the rst3 command, described in [this post](https://groups.google.com/g/leo-editor/c/WXIQUPr88Xw/m/8-SL-BMKBwAJ) render this topic obsolete.

To summarize: plugins or scripts may define user filters that rst3 applies to all nodes. This is the simplest, most general solution.
